// site/src/components/exercises/layouts/ExerciseHeader.tsx
import { X } from '@phosphor-icons/react'
import { Progress } from '@/components/ui/progress'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

export interface ExerciseHeaderProps {
  /** Current progress percentage (0-100) */
  progress: number
  /** Callback when close button is clicked */
  onClose: () => void
  /** Optional className for the container */
  className?: string
  /** Show close button (default: true) */
  showCloseButton?: boolean
}

export function ExerciseHeader({
  progress,
  onClose,
  className,
  showCloseButton = true,
}: ExerciseHeaderProps) {
  return (
    <div
      className={cn(
        'fixed top-0 left-0 right-0 z-10 bg-neutral-900/95 backdrop-blur-sm border-b border-neutral-700',
        className
      )}
    >
      <div className="w-full max-w-2xl mx-auto px-6 py-4">
        <div className="flex items-center gap-4">
          {/* Close button */}
          {showCloseButton && (
            <Button
              variant="ghost"
              size="icon"
              onClick={onClose}
              className="text-neutral-400 hover:text-white shrink-0"
              aria-label="Close"
            >
              <X size={24} weight="bold" />
            </Button>
          )}

          {/* Progress bar */}
          <div className="flex-1">
            <Progress value={progress} className="h-2" />
          </div>
        </div>
      </div>
    </div>
  )
}

// solidjs-app/src/components/exercises/ExerciseHeader.tsx
import { type Component, createEffect } from 'solid-js'
import { Progress } from '@/components/ui/progress'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

export interface ExerciseHeaderProps {
  /** Current progress percentage (0-100) */
  progress: number
  /** Callback when close button is clicked */
  onClose: () => void
  /** Optional className for the container */
  class?: string
  /** Show close button (default: true) */
  showCloseButton?: boolean
  /** Optional stats to display */
  stats?: {
    currentCard: number
    totalCards: number
    newToday: number
    newRemaining: number
    reviewCount: number
    learningCount: number
  }
}

export const ExerciseHeader: Component<ExerciseHeaderProps> = (props) => {
  // Log stats to console instead of displaying in UI
  createEffect(() => {
    if (props.stats) {
      console.log('[ExerciseHeader]', {
        today: `${props.stats.newToday}/15 new`,
        review: `${props.stats.reviewCount} review`,
        learning: props.stats.learningCount > 0 ? `${props.stats.learningCount} learning` : undefined,
        card: `${props.stats.currentCard}/${props.stats.totalCards}`,
        progress: `${props.progress}%`
      })
    }
  })

  return (
    <div
      class={cn(
        'flex items-center gap-3 w-full',
        props.class
      )}
    >
      {/* Close button */}
      {(props.showCloseButton ?? true) && (
        <Button
          variant="ghost"
          size="icon"
          onClick={props.onClose}
          class="text-muted-foreground hover:text-foreground shrink-0"
          aria-label="Close"
        >
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </Button>
      )}

      {/* Progress bar */}
      <div class="flex-1">
        <Progress value={props.progress} />
      </div>
    </div>
  )
}
