// root/app/src/components/exercises/SayItBackExercise.tsx
import { AudioButton } from '@/components/ui/audio-button'

// Simple text similarity scoring (can be enhanced with phoneme matching later)
export function calculateTextSimilarity(expected: string, actual: string): number {
  const normalize = (text: string) => text.toLowerCase().replace(/[^\w\s]/g, '').trim()
  const expectedNorm = normalize(expected)
  const actualNorm = normalize(actual)

  if (expectedNorm === actualNorm) return 100

  // Simple word-based similarity
  const expectedWords = expectedNorm.split(/\s+/)
  const actualWords = actualNorm.split(/\s+/)

  let matches = 0
  for (const word of expectedWords) {
    if (actualWords.includes(word)) matches++
  }

  return Math.round((matches / expectedWords.length) * 100)
}

export interface SayItBackExerciseProps {
  /** The text the user should say */
  expectedText: string
  /** The user's transcribed speech (when available) */
  transcript?: string
  /** Score 0-100 (when available) */
  score?: number | null
  /** Number of attempts */
  attempts?: number
  /** Whether recording is in progress */
  isRecording?: boolean
  /** Whether transcription is processing */
  isProcessing?: boolean
  /** Whether the exercise can record (Lit + wallet ready) */
  canRecord?: boolean
  /** Status message to show */
  statusMessage?: string
  /** Callbacks */
  onStartRecording?: () => void
  onStopRecording?: () => void
}

export function SayItBackExercise({
  expectedText,
  transcript,
  score = null,
  attempts = 0,
  isRecording = false,
  isProcessing = false,
  canRecord = true,
  statusMessage,
  onStartRecording,
  onStopRecording,
}: SayItBackExerciseProps) {
  const isCorrect = score !== null && score >= 70
  const showResults = transcript !== undefined

  const handlePlayAudio = () => {
    console.log('[TTS] Would play:', expectedText)
    // Future: Implement TTS playback
  }

  return (
    <div className="space-y-6">
      {/* Target text section */}
      <div className="text-left space-y-3">
        <div className="text-muted-foreground text-base font-medium">
          Say it back:
        </div>
        <div className="flex items-center gap-4">
          <AudioButton onClick={handlePlayAudio} aria-label="Play audio" />
          <div className="text-xl font-medium text-foreground leading-relaxed">
            {expectedText}
          </div>
        </div>
      </div>


      {/* User's transcript (shown after speaking) */}
      {showResults && (
        <div className="text-left space-y-3">
          <div className="text-muted-foreground text-base font-medium">
            You said:
          </div>
          <div className="text-xl font-medium text-foreground leading-relaxed">
            {transcript}
          </div>
        </div>
      )}
    </div>
  )
}

// solidjs-app/src/components/exercises/SayItBackExercise.tsx
import { type Component, Show } from 'solid-js'
import { AudioButton } from '@/components/media/AudioButton'

export interface SayItBackExerciseProps {
  /** The text the user should say */
  expectedText: string
  /** The user's transcribed speech (when available) */
  transcript?: string
  /** Score 0-100 (when available) */
  score?: number | null
  /** Grade message ("Excellent!", "Nice try!", etc.) */
  gradeMessage?: string
  /** Number of attempts */
  attempts?: number
  /** Whether recording is in progress */
  isRecording?: boolean
  /** Whether transcription is processing */
  isProcessing?: boolean
  /** Whether the exercise can record (Lit + wallet ready) */
  canRecord?: boolean
  /** Status message to show */
  statusMessage?: string
  /** Optional TTS audio URL for playback */
  ttsAudioUrl?: string
  /** Callbacks */
  onStartRecording?: () => void
  onStopRecording?: () => void
}

export const SayItBackExercise: Component<SayItBackExerciseProps> = (props) => {
  let audioRef: HTMLAudioElement | undefined

  const showResults = () => props.transcript !== undefined

  const handlePlayAudio = () => {
    if (props.ttsAudioUrl && audioRef) {
      audioRef.src = props.ttsAudioUrl
      audioRef.play().catch(err => {
        console.error('[TTS] Failed to play audio:', err)
      })
    }
  }

  return (
    <div class="space-y-6">
      {/* Target text section */}
      <div class="text-left space-y-3">
        <div class="text-muted-foreground text-lg sm:text-xl font-medium">
          Say it back:
        </div>
        <div class="flex items-start gap-4">
          {/* Play button - only show if we have audio */}
          <Show when={props.ttsAudioUrl}>
            <AudioButton
              onClick={handlePlayAudio}
              aria-label="Play audio"
              class="mt-1 shrink-0"
            />
          </Show>
          {/* Main exercise text */}
          <div class="text-xl sm:text-2xl font-semibold text-foreground leading-relaxed break-words flex-1">
            {props.expectedText}
          </div>
        </div>
      </div>

      {/* Results (shown after speaking) */}
      <Show when={showResults()}>
        <div class="space-y-4">
          {/* Grade message */}
          <Show when={props.gradeMessage}>
            <div class="text-2xl sm:text-3xl font-bold text-primary">
              {props.gradeMessage}
            </div>
          </Show>

          {/* User's transcript */}
          <div class="text-left space-y-3">
            <div class="text-muted-foreground text-lg sm:text-xl font-medium">
              You said:
            </div>
            <div class="text-xl sm:text-2xl font-semibold text-foreground leading-relaxed break-words">
              {props.transcript}
            </div>
          </div>
        </div>
      </Show>

      {/* Hidden audio element for playback */}
      <audio ref={audioRef} />
    </div>
  )
}
