// solidjs-app/src/pages/WalletPage.tsx
/**
 * WalletPage - Container component for wallet functionality
 * Handles data fetching and connects to presentational components
 */

import { type Component, Show, Switch, Match } from 'solid-js'
import { useAuth } from '@/contexts/AuthContext'
import { usePKPBalances } from '@/hooks/usePKPBalances'
import { WalletPageView } from '@/components/wallet/WalletPageView'
import { Button } from '@/components/ui/button'
import { SignOut } from '@/components/icons'

export const WalletPage: Component = () => {
  const auth = useAuth()
  const { balances, isLoading, error, refetch } = usePKPBalances()

  const handleCopyAddress = async () => {
    const address = auth.pkpAddress()
    if (!address) return

    try {
      await navigator.clipboard.writeText(address)
      console.log('PKP address copied to clipboard')
    } catch (err) {
      console.error('Failed to copy address:', err)
    }
  }

  return (
    <Switch>
      {/* Loading skeleton while checking stored session */}
      <Match when={auth.isCheckingSession()}>
        <WalletPageView
          tokens={[]}
          walletAddress=""
          onCopyAddress={() => {}}
          isLoading={true}
        />
      </Match>

      {/* Not connected state */}
      <Match when={!auth.isPKPReady()}>
        <div class="flex flex-col items-center justify-center h-screen gap-4 px-4">
          <h2 class="text-2xl font-bold text-center">Sign Up</h2>
          <p class="text-muted-foreground text-center">
            Create an account to access your wallet and purchases
          </p>
          <Button onClick={() => auth.openAuthDialog()}>
            Sign Up
          </Button>
        </div>
      </Match>

      {/* Error state */}
      <Match when={error()}>
        <div class="max-w-2xl mx-auto px-4 md:px-8 py-8 md:py-12">
          <div class="text-center">
            <h2 class="text-xl font-semibold mb-4 text-destructive">
              Error Loading Balances
            </h2>
            <p class="text-muted-foreground mb-4">{error()?.message}</p>
            <Button onClick={refetch} variant="outline">
              Retry
            </Button>
          </div>
        </div>
      </Match>

      {/* Connected state */}
      <Match when={auth.isPKPReady()}>
        <div>
          <WalletPageView
            tokens={balances()}
            walletAddress={auth.pkpAddress() || ''}
            onCopyAddress={handleCopyAddress}
            isLoading={isLoading()}
          />

          {/* Disconnect Button */}
          <div class="max-w-2xl mx-auto px-4 md:px-8 pb-8">
            <Button
              onClick={() => auth.logout()}
              variant="outline"
              class="w-full gap-2"
            >
              <SignOut class="h-5 w-5" />
              Disconnect
            </Button>
          </div>
        </div>
      </Match>
    </Switch>
  )
}

// app/src/pages/WalletPage.tsx
import { useTranslation } from 'react-i18next'
import { WalletPageView } from '@/components/wallet/WalletPageView'
import { useAuth } from '@/contexts/AuthContext'
import { usePKPBalances } from '@/hooks/usePKPBalances'
import { Button } from '@/components/ui/button'

/**
 * WalletPage - Container component for wallet page
 * Handles wallet data fetching and state management
 */
export function WalletPage({ onConnectWallet }: { onConnectWallet?: () => void }) {
  const { t } = useTranslation()
  const { pkpAddress, lensAccount, isPKPReady, isCheckingSession } = useAuth()
  const { balances, error } = usePKPBalances()

  // Get username from lens account if available
  const currentUsername = lensAccount?.username?.localName || undefined

  const handleCopyAddress = async () => {
    if (!pkpAddress) return
    
    try {
      await navigator.clipboard.writeText(pkpAddress)
      console.log('PKP address copied to clipboard')
    } catch (err) {
      console.error('Failed to copy address:', err)
    }
  }

  const handleCheckUsernameAvailability = async (username: string): Promise<boolean> => {
    // TODO: Check against Lens Protocol
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 500))

    // Mock: some usernames are taken
    const takenUsernames = ['alice', 'bob', 'charlie', 'test', 'admin', 'karaoke']
    return !takenUsernames.includes(username.toLowerCase())
  }

  const handlePurchaseUsername = async (username: string): Promise<boolean> => {
    // TODO: Implement username purchase with Lens Protocol
    console.log('Purchasing username:', username)

    // Simulate purchase
    await new Promise(resolve => setTimeout(resolve, 2000))

    console.log(`Username @${username} purchased successfully!`)

    return true
  }

  // Show skeleton while checking for stored session
  if (isCheckingSession) {
    return (
      <WalletPageView
        tokens={[]}
        walletAddress=""
        onCopyAddress={() => {}}
        isLoading={true}
      />
    )
  }

  // Show sign up state when PKP is not ready
  if (!isPKPReady) {
    return (
      <div className="flex flex-col items-center justify-center h-screen gap-4 px-4">
        <h2 className="text-2xl font-bold text-center">{t('study.signUp')}</h2>
        <p className="text-muted-foreground text-center">{t('study.signUpDescription')}</p>
        <Button onClick={onConnectWallet}>
          {t('study.signUp')}
        </Button>
      </div>
    )
  }

  // Show error state if balance fetching failed
  if (error) {
    return (
      <div className="max-w-2xl mx-auto px-4 md:px-8 py-8 md:py-12">
        <div className="text-center">
          <h2 className="text-xl font-semibold mb-4 text-destructive">{t('wallet.errorLoadingBalances')}</h2>
          <p className="text-muted-foreground mb-4">{error.message}</p>
          <button
            onClick={() => window.location.reload()}
            className="px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90"
          >
            {t('common.retry')}
          </button>
        </div>
      </div>
    )
  }

  return (
    <WalletPageView
      tokens={balances}
      walletAddress={pkpAddress || ''}
      currentUsername={currentUsername}
      onCopyAddress={handleCopyAddress}
      onCheckUsernameAvailability={handleCheckUsernameAvailability}
      onPurchaseUsername={handlePurchaseUsername}
    />
  )
}
