// solidjs-app/src/components/feed/VerticalVideoFeed.tsx
import { createSignal, createEffect, onMount, onCleanup, For, Show, type Component } from 'solid-js'
import { useNavigate } from '@solidjs/router'
import { VideoPost } from './VideoPost'
import { useSongPrefetch } from '@/hooks/usePrefetch'
import type { VideoPostData } from './types'

export interface VerticalVideoFeedProps {
  videos: VideoPostData[]
  isLoading?: boolean
  onLoadMore?: () => void
  hasMore?: boolean
  initialVideoId?: string
  hasMobileFooter?: boolean
  onLikeClick?: (videoId: string) => void
  onFollowClick?: (videoId: string) => void
  onProfileClick?: (username: string) => void
  /** Show back button on videos */
  showBackButton?: boolean
  /** Back button click handler */
  onBack?: () => void
  /** Called when video has been watched for 3+ seconds */
  onVideoViewed?: (postId: string) => void
}

/**
 * VerticalVideoFeed - TikTok-style vertical scrolling video feed
 * Features snap scrolling and keyboard navigation
 */
export const VerticalVideoFeed: Component<VerticalVideoFeedProps> = (props) => {
  let containerRef: HTMLDivElement | undefined
  const [activeIndex, setActiveIndex] = createSignal(0)
  const navigate = useNavigate()
  const { prefetch: prefetchSong } = useSongPrefetch()

  // Prefetch song data when active video changes
  createEffect(() => {
    const video = props.videos[activeIndex()]
    if (video?.spotifyTrackId) {
      prefetchSong(video.spotifyTrackId)
    }
  })

  // Scroll to initial video on mount
  onMount(() => {
    if (props.initialVideoId && containerRef && props.videos.length > 0) {
      const index = props.videos.findIndex(v => v.id === props.initialVideoId)
      if (index >= 0) {
        containerRef.scrollTo({
          top: index * containerRef.clientHeight,
          behavior: 'auto'
        })
        setActiveIndex(index)
      }
    }
  })

  // Handle scroll to update active index
  const handleScroll = () => {
    if (!containerRef) return

    const scrollTop = containerRef.scrollTop
    const viewportHeight = containerRef.clientHeight
    const newIndex = Math.round(scrollTop / viewportHeight)

    if (newIndex !== activeIndex() && newIndex >= 0 && newIndex < props.videos.length) {
      setActiveIndex(newIndex)
    }

    // Load more when approaching the end
    if (props.hasMore && newIndex >= props.videos.length - 2) {
      props.onLoadMore?.()
    }
  }

  // Attach scroll listener
  onMount(() => {
    containerRef?.addEventListener('scroll', handleScroll)
    onCleanup(() => containerRef?.removeEventListener('scroll', handleScroll))
  })

  // Keyboard navigation
  onMount(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!containerRef) return

      if (e.key === 'ArrowDown' && activeIndex() < props.videos.length - 1) {
        e.preventDefault()
        const nextIndex = activeIndex() + 1
        containerRef.scrollTo({
          top: nextIndex * containerRef.clientHeight,
          behavior: 'smooth'
        })
      } else if (e.key === 'ArrowUp' && activeIndex() > 0) {
        e.preventDefault()
        const prevIndex = activeIndex() - 1
        containerRef.scrollTo({
          top: prevIndex * containerRef.clientHeight,
          behavior: 'smooth'
        })
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    onCleanup(() => window.removeEventListener('keydown', handleKeyDown))
  })

  return (
    <Show
      when={props.videos.length > 0 || props.isLoading}
      fallback={
        <div class="h-vh-screen md:h-screen w-full flex items-center justify-center bg-background">
          <div class="text-foreground text-lg">No videos available</div>
        </div>
      }
    >
      <div
        ref={containerRef}
        class="h-vh-screen md:h-screen w-full overflow-y-scroll snap-y snap-mandatory scrollbar-hide"
        style={{ 'scrollbar-width': 'none', '-ms-overflow-style': 'none' }}
      >
        <For each={props.videos}>
          {(video, index) => {
            // Determine if this video should autoplay
            const isActive = () => index() === activeIndex()

            return (
              <div class="h-vh-screen md:h-screen w-full snap-start snap-always">
                <VideoPost
                  id={video.id}
                  videoUrl={video.videoUrl}
                  thumbnailUrl={video.thumbnailUrl}
                  username={video.username}
                  userAvatar={video.userAvatar}
                  authorAddress={video.authorAddress}
                  grade={video.grade}
                  musicTitle={video.musicTitle}
                  musicAuthor={video.musicAuthor}
                  musicImageUrl={video.musicImageUrl}
                  artistSlug={video.artistSlug}
                  songSlug={video.songSlug}
                  spotifyTrackId={video.spotifyTrackId}
                  likes={video.likes}
                  shares={video.shares}
                  isLiked={video.isLiked}
                  isFollowing={video.isFollowing}
                  canInteract={video.canInteract}
                  autoplay={isActive()}
                  priorityLoad={index() === 0}
                  hasMobileFooter={props.hasMobileFooter}
                  showBackButton={props.showBackButton}
                  onBack={props.onBack}
                  onLikeClick={() => props.onLikeClick?.(video.id)}
                  onFollowClick={() => props.onFollowClick?.(video.id)}
                  onProfileClick={() => {
                    props.onProfileClick?.(video.username)
                    navigate(`/u/${video.username}`)
                  }}
                  onViewed={props.onVideoViewed}
                />
              </div>
            )
          }}
        </For>

        {/* Loading indicator at bottom */}
        <Show when={props.isLoading}>
          <div class="h-20 flex items-center justify-center">
            <div class="w-8 h-8 border-4 border-primary border-t-transparent rounded-full animate-spin" />
          </div>
        </Show>
      </div>
    </Show>
  )
}

// app/src/components/feed/VerticalVideoFeed.tsx
import { useRef, useState, useCallback, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { VideoPost } from './VideoPost'
import type { VideoPostData } from './types'

export interface VerticalVideoFeedProps {
  videos: VideoPostData[]
  isLoading?: boolean
  onLoadMore?: () => void
  hasMore?: boolean
}

/**
 * VerticalVideoFeed - TikTok-style vertical scrolling video feed
 * Custom implementation with snap scrolling and keyboard navigation
 */
export function VerticalVideoFeed({
  videos,
  isLoading = false,
  onLoadMore,
  hasMore = false,
}: VerticalVideoFeedProps) {
  const containerRef = useRef<HTMLDivElement>(null)
  const [activeIndex, setActiveIndex] = useState(0)
  const navigate = useNavigate()

  // Handle scroll to detect active video
  useEffect(() => {
    const container = containerRef.current
    if (!container) return

    const handleScroll = () => {
      const scrollTop = container.scrollTop
      const viewportHeight = container.clientHeight
      const newIndex = Math.round(scrollTop / viewportHeight)

      if (newIndex !== activeIndex && newIndex >= 0 && newIndex < videos.length) {
        setActiveIndex(newIndex)

        // Load more when approaching end of feed
        if (newIndex >= videos.length - 3 && hasMore && onLoadMore) {
          onLoadMore()
        }
      }
    }

    container.addEventListener('scroll', handleScroll)
    return () => container.removeEventListener('scroll', handleScroll)
  }, [activeIndex, videos.length, hasMore, onLoadMore])

  // Handle keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      const container = containerRef.current
      if (!container) return

      if (e.key === 'ArrowDown' && activeIndex < videos.length - 1) {
        e.preventDefault()
        const nextIndex = activeIndex + 1
        container.scrollTo({
          top: nextIndex * container.clientHeight,
          behavior: 'smooth'
        })
      } else if (e.key === 'ArrowUp' && activeIndex > 0) {
        e.preventDefault()
        const prevIndex = activeIndex - 1
        container.scrollTo({
          top: prevIndex * container.clientHeight,
          behavior: 'smooth'
        })
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [activeIndex, videos.length])

  if (isLoading && videos.length === 0) {
    return (
      <div className="h-screen w-full flex items-center justify-center bg-neutral-900">
        <div className="text-white text-lg">Loading feed...</div>
      </div>
    )
  }

  if (videos.length === 0) {
    return (
      <div className="h-screen w-full flex items-center justify-center bg-neutral-900">
        <div className="text-white text-lg">No videos available</div>
      </div>
    )
  }

  return (
    <div
      ref={containerRef}
      className="h-screen w-full overflow-y-scroll snap-y snap-mandatory scrollbar-hide"
      style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}
    >
      {videos.map((video, index) => (
          <div key={video.id} className="h-screen w-full snap-start snap-always">
            <VideoPost
              {...video}
              autoplay={index === activeIndex}
              onLikeClick={() => {
                console.log('[VerticalVideoFeed] Like clicked:', video.id)
                // TODO: Implement like mutation
              }}
              onCommentClick={() => {
                console.log('[VerticalVideoFeed] Comment clicked:', video.id)
                // TODO: Handle comment sheet
              }}
              onShareClick={() => {
                console.log('[VerticalVideoFeed] Share clicked:', video.id)
                // TODO: Handle share sheet
              }}
              onFollowClick={() => {
                console.log('[VerticalVideoFeed] Follow clicked:', video.username)
                // TODO: Implement follow mutation
              }}
              onProfileClick={() => {
                console.log('[VerticalVideoFeed] Profile clicked:', video.username)
                navigate(`/u/${video.username}`)
              }}
              onAudioClick={() => {
                console.log('[VerticalVideoFeed] Audio clicked:', video.geniusId)
                if (video.geniusId) {
                  navigate(`/song/${video.geniusId}`)
                }
              }}
            />
          </div>
      ))}

      {/* Loading indicator for infinite scroll */}
      {isLoading && videos.length > 0 && (
        <div className="fixed bottom-4 left-1/2 transform -translate-x-1/2 bg-black/60 text-white px-4 py-2 rounded-full text-sm z-50">
          Loading more...
        </div>
      )}
    </div>
  )
}
