// solidjs-app/src/components/leaderboard/Leaderboard.tsx
/**
 * Leaderboard - Reusable leaderboard component for displaying student rankings
 * SolidJS implementation
 */

import { type Component, Show, For } from 'solid-js'
import { cn } from '@/lib/utils'
import { Spinner } from '@/components/ui/spinner'
import { useTranslation } from '@/lib/i18n'
import { Icon } from '@/components/icons'

export interface LeaderboardEntry {
  rank: number
  username: string
  score: number
  avatarUrl?: string
  isCurrentUser?: boolean
}

export interface LeaderboardProps {
  entries: LeaderboardEntry[]
  currentUser?: LeaderboardEntry
  isLoading?: boolean
  emptyMessage?: string
  class?: string
  showTitle?: boolean
}

/**
 * Reusable leaderboard component for displaying student rankings
 * Used by SongPage and ArtistPage
 */
export const Leaderboard: Component<LeaderboardProps> = (props) => {
  const { t } = useTranslation()

  return (
    <>
      {/* Loading state */}
      <Show when={props.isLoading}>
        <div class={cn('flex items-center justify-center py-12', props.class)}>
          <Spinner size="lg" />
        </div>
      </Show>

      {/* Empty state */}
      <Show when={!props.isLoading && props.entries.length === 0 && !props.currentUser}>
        <div class={cn('flex flex-col items-center justify-center py-12 text-center', props.class)}>
          {/* Title with crown icon */}
          <Show when={props.showTitle !== false}>
            <div class="flex items-center gap-2 mb-6">
              <Icon name="crown-cross" weight="fill" class="text-2xl text-yellow-500" />
              <h2 class="text-xl font-bold">{t('leaderboard.rankings')}</h2>
            </div>
          </Show>
          <p class="text-muted-foreground">
            {props.emptyMessage || 'No students yet. Be the first to practice!'}
          </p>
        </div>
      </Show>

      {/* Leaderboard list */}
      <Show when={!props.isLoading && (props.entries.length > 0 || props.currentUser)}>
        <div class={props.class}>
          {/* Title with crown icon */}
          <Show when={props.showTitle !== false}>
            <div class="flex items-center gap-2 mb-4">
              <Icon name="crown-cross" weight="fill" class="text-2xl text-yellow-500" />
              <h2 class="text-xl font-bold">{t('leaderboard.rankings')}</h2>
            </div>
          </Show>
          <div class="space-y-2">
            <For each={props.entries}>
              {(entry) => (
                <div
                  class={cn(
                    'flex items-center gap-4 px-5 py-4 rounded-2xl',
                    entry.isCurrentUser ? 'bg-muted/50' : 'bg-muted/30'
                  )}
                >
                  <div class="w-10 text-center text-lg font-bold text-muted-foreground">
                    #{entry.rank}
                  </div>
                  <Show when={entry.avatarUrl}>
                    <img
                      src={entry.avatarUrl}
                      alt={entry.username}
                      class="w-12 h-12 rounded-full object-cover"
                    />
                  </Show>
                  <p class="flex-1 min-w-0 text-lg font-semibold truncate">
                    {entry.username}
                  </p>
                  <p class="text-lg font-bold tabular-nums">
                    {entry.score.toLocaleString()}
                  </p>
                </div>
              )}
            </For>
          </div>

          {/* Current user (if not in top 10) */}
          <Show when={props.currentUser && !props.entries.some((e) => e.isCurrentUser)}>
            <div class="mt-4 pt-4 border-t border-border">
              <div class="flex items-center gap-4 px-5 py-4 rounded-2xl bg-primary/10">
                <div class="w-10 text-center text-lg font-bold text-muted-foreground">
                  #{props.currentUser!.rank}
                </div>
                <Show when={props.currentUser!.avatarUrl}>
                  <img
                    src={props.currentUser!.avatarUrl}
                    alt={props.currentUser!.username}
                    class="w-12 h-12 rounded-full object-cover"
                  />
                </Show>
                <p class="flex-1 min-w-0 text-lg font-semibold truncate">
                  {props.currentUser!.username}
                </p>
                <p class="text-lg font-bold tabular-nums">
                  {props.currentUser!.score.toLocaleString()}
                </p>
              </div>
            </div>
          </Show>
        </div>
      </Show>
    </>
  )
}

// root/app/src/components/school/Leaderboard.tsx
import { cn } from '@/lib/utils'

export type LeaderboardEntry = {
  rank: number
  username: string
  score: number
  avatarUrl?: string
  isCurrentUser?: boolean
}

export type LeaderboardProps = {
  entries: LeaderboardEntry[]
  currentUser?: LeaderboardEntry
  className?: string
}

// Minimalistic leaderboard: top 3 + current user as 4th slot
export function Leaderboard({
  entries,
  currentUser,
  className,
}: LeaderboardProps) {
  // Get top 3 entries
  const topThree = entries.slice(0, 3)

  // Display entries: top 3 + current user (if provided and not in top 3)
  const displayEntries = [...topThree]
  if (currentUser && !topThree.find(e => e.username === currentUser.username)) {
    displayEntries.push(currentUser)
  }

  return (
    <div className={cn('w-full', className)}>
      <div className="space-y-0.5">
        {displayEntries.map((entry, index) => (
          <div
            key={`${entry.rank}-${entry.username}`}
            className="flex items-center gap-3 py-2 pr-3 rounded-lg bg-neutral-900/50 transition-colors"
          >
            {/* Avatar */}
            <div className="w-12 h-12 rounded-lg bg-gradient-to-br from-pink-400 to-purple-600 flex-shrink-0">
              {entry.avatarUrl ? (
                <img
                  src={entry.avatarUrl}
                  alt={entry.username}
                  className="w-full h-full rounded-lg object-cover"
                />
              ) : (
                <div className="w-full h-full rounded-lg bg-neutral-700" />
              )}
            </div>

            {/* Username */}
            <div className="flex-1 min-w-0">
              <p className="font-medium text-white truncate">
                {entry.username}
              </p>
            </div>

            {/* Score */}
            <div className="font-semibold text-neutral-300">
              {entry.score.toLocaleString()}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
