// solidjs-app/src/components/search/LibraryView.tsx
/**
 * LibraryView Component
 *
 * Displays songs organized into horizontal scrolling sections
 * (e.g., by artist, trending, etc.)
 */

import { Component, For, Show, splitProps } from 'solid-js'
import { cn } from '@/lib/utils'
import { Skeleton } from '@/components/ui/skeleton'

export interface LibrarySong {
  id: string
  title: string
  artist: string
  artworkUrl?: string
}

export interface LibrarySection {
  id: string
  title: string
  songs: LibrarySong[]
  /** Show artist name on each tile (default: true for mixed sections like Trending) */
  showArtist?: boolean
}

export interface LibraryViewProps {
  sections: LibrarySection[]
  isLoading?: boolean
  onSongClick?: (song: LibrarySong) => void
  class?: string
}

// ============================================================
// Song Tile
// ============================================================

interface SongTileProps {
  song: LibrarySong
  onClick?: () => void
  showArtist?: boolean
}

const SongTile: Component<SongTileProps> = (props) => {
  return (
    <button
      onClick={props.onClick}
      class="shrink-0 w-28 sm:w-32 md:w-36 text-left cursor-pointer group"
    >
      <div class="relative aspect-square w-full overflow-hidden rounded-2xl bg-muted">
        <Show
          when={props.song.artworkUrl}
          fallback={
            <div class="w-full h-full bg-gradient-to-br from-pink-400 to-purple-600" />
          }
        >
          <img
            src={props.song.artworkUrl}
            alt=""
            class="w-full h-full object-cover transition-transform group-hover:scale-105"
          />
        </Show>
      </div>
      <p class="mt-2 text-base font-semibold truncate">{props.song.title}</p>
      <Show when={props.showArtist ?? true}>
        <p class="text-base text-muted-foreground truncate">{props.song.artist}</p>
      </Show>
    </button>
  )
}

// ============================================================
// Skeletons
// ============================================================

const SongTileSkeleton: Component = () => {
  return (
    <div class="shrink-0 w-28 sm:w-32 md:w-36">
      <Skeleton class="aspect-square w-full rounded-2xl" />
      <Skeleton class="h-5 w-3/4 mt-2" />
      <Skeleton class="h-5 w-1/2 mt-1" />
    </div>
  )
}

const SectionSkeleton: Component = () => {
  return (
    <div class="space-y-3">
      <Skeleton class="h-6 w-32 mx-4" />
      <div class="flex gap-2 sm:gap-3 px-4">
        <For each={[1, 2, 3, 4]}>{() => <SongTileSkeleton />}</For>
      </div>
    </div>
  )
}

// ============================================================
// Section Row
// ============================================================

interface SectionRowProps {
  section: LibrarySection
  onSongClick?: (song: LibrarySong) => void
}

const LibrarySectionRow: Component<SectionRowProps> = (props) => {
  return (
    <div class="space-y-3">
      <h2 class="text-lg font-semibold px-4">{props.section.title}</h2>
      <div class="w-full overflow-x-auto scrollbar-hide">
        <div class="flex gap-2 sm:gap-3 px-4 pb-2">
          <For each={props.section.songs}>
            {(song) => (
              <SongTile
                song={song}
                onClick={() => props.onSongClick?.(song)}
                showArtist={props.section.showArtist ?? true}
              />
            )}
          </For>
        </div>
      </div>
    </div>
  )
}

// ============================================================
// Main Component
// ============================================================

export const LibraryView: Component<LibraryViewProps> = (props) => {
  const [local, others] = splitProps(props, ['sections', 'isLoading', 'onSongClick', 'class'])

  return (
    <Show
      when={!local.isLoading}
      fallback={
        <div class={cn('min-h-screen bg-background py-4', local.class)} {...others}>
          <div class="max-w-4xl mx-auto w-full px-4 sm:px-6 md:px-8 space-y-6">
            <SectionSkeleton />
            <SectionSkeleton />
            <SectionSkeleton />
          </div>
        </div>
      }
    >
      <div class={cn('min-h-screen bg-background py-4', local.class)} {...others}>
        <div class="max-w-4xl mx-auto w-full px-4 sm:px-6 md:px-8 space-y-6">
          <For each={local.sections}>
            {(section) => (
              <LibrarySectionRow
                section={section}
                onSongClick={local.onSongClick}
              />
            )}
          </For>
        </div>
      </div>
    </Show>
  )
}

export default LibraryView

// app/src/components/search/LibraryView.tsx
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area'
import { Skeleton } from '@/components/ui/skeleton'
import { cn } from '@/lib/utils'

export interface LibrarySong {
  id: string
  title: string
  artist: string
  artworkUrl?: string
}

export interface LibrarySection {
  id: string
  title: string
  songs: LibrarySong[]
  /** Show artist name on each tile (default: true for mixed sections like Trending) */
  showArtist?: boolean
}

export interface LibraryViewProps {
  sections: LibrarySection[]
  isLoading?: boolean
  onSongClick?: (song: LibrarySong) => void
}

function SongTile({
  song,
  onClick,
  showArtist = true,
}: {
  song: LibrarySong
  onClick?: () => void
  showArtist?: boolean
}) {
  return (
    <button
      onClick={onClick}
      className="shrink-0 w-28 sm:w-32 md:w-36 text-left cursor-pointer group"
    >
      <div className="relative aspect-square w-full overflow-hidden rounded-2xl bg-muted">
        {song.artworkUrl ? (
          <img
            src={song.artworkUrl}
            alt=""
            className="w-full h-full object-cover transition-transform group-hover:scale-105"
          />
        ) : (
          <div className="w-full h-full bg-gradient-to-br from-pink-400 to-purple-600" />
        )}
      </div>
      <p className="mt-2 text-base font-semibold truncate">{song.title}</p>
      {showArtist && (
        <p className="text-base text-muted-foreground truncate">{song.artist}</p>
      )}
    </button>
  )
}

function SongTileSkeleton() {
  return (
    <div className="shrink-0 w-28 sm:w-32 md:w-36">
      <Skeleton className="aspect-square w-full rounded-2xl" />
      <Skeleton className="h-5 w-3/4 mt-2" />
      <Skeleton className="h-5 w-1/2 mt-1" />
    </div>
  )
}

function SectionSkeleton() {
  return (
    <div className="space-y-3">
      <Skeleton className="h-6 w-32 mx-4" />
      <div className="flex gap-2 sm:gap-3 px-4">
        {Array.from({ length: 4 }).map((_, i) => (
          <SongTileSkeleton key={i} />
        ))}
      </div>
    </div>
  )
}

function LibrarySectionRow({
  section,
  onSongClick,
}: {
  section: LibrarySection
  onSongClick?: (song: LibrarySong) => void
}) {
  return (
    <div className="space-y-3">
      <h2 className="text-lg font-semibold px-4">{section.title}</h2>
      <ScrollArea className="w-full">
        <div className="flex gap-2 sm:gap-3 px-4 pb-2">
          {section.songs.map((song) => (
            <SongTile
              key={song.id}
              song={song}
              onClick={() => onSongClick?.(song)}
              showArtist={section.showArtist ?? true}
            />
          ))}
        </div>
        <ScrollBar orientation="horizontal" />
      </ScrollArea>
    </div>
  )
}

export function LibraryView({
  sections,
  isLoading = false,
  onSongClick,
}: LibraryViewProps) {
  if (isLoading) {
    return (
      <div className="min-h-screen bg-background py-4">
        <div className="max-w-6xl mx-auto w-full space-y-6">
          <SectionSkeleton />
          <SectionSkeleton />
          <SectionSkeleton />
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background py-4">
      <div className="max-w-6xl mx-auto w-full space-y-6">
        {sections.map((section) => (
          <LibrarySectionRow
            key={section.id}
            section={section}
            onSongClick={onSongClick}
          />
        ))}
      </div>
    </div>
  )
}
