// app/src/components/wallet/WalletPageView.tsx
import { Copy } from '@phosphor-icons/react'
import { Button } from '@/components/ui/button'
import { Item, ItemMedia, ItemContent, ItemTitle, ItemDescription } from '@/components/ui/item'
import { UsernameUpgradeSection } from './UsernameUpgradeSection'

// Icon component that renders currency logo with chain indicator
function TokenIcon({ 
  currencyIcon, 
  chainIcon, 
  className = "" 
}: { 
  currencyIcon?: string
  chainIcon?: string
  className?: string 
}) {
  return (
    <div className={`relative w-12 h-12 md:w-14 md:h-14 ${className}`}>
      {/* Currency icon with white background */}
      {currencyIcon && (
        <div className="w-full h-full rounded-full bg-white p-2 flex items-center justify-center shadow-sm border border-gray-200">
          <img 
            src={`/images/${currencyIcon}`} 
            alt="Currency"
            className="w-full h-full object-contain"
            onError={(e) => {
              // Fallback to symbol text if image fails to load
              const target = e.target as HTMLImageElement;
              target.style.display = 'none';
              const parent = target.parentElement;
              if (parent) {
                parent.innerHTML = '<span class="text-xs font-bold text-gray-600">?</span>';
              }
            }}
          />
        </div>
      )}
      
      {/* Chain indicator in top right */}
      {chainIcon && (
        <div className="absolute -top-2 -right-2 w-8 h-8 flex items-center justify-center">
          <img
            src={`/images/${chainIcon}`}
            alt="Chain"
            className="w-full h-full object-contain"
            style={{
              width: chainIcon === 'base-chain.svg' ? '75%' :
                     chainIcon === 'ethereum-chain.svg' ? '65%' :
                     chainIcon === 'arbitrum-chain.svg' ? '75%' :
                     chainIcon === 'optimism-chain.svg' ? '70%' :
                     chainIcon === 'bsc-chain.svg' ? '100%' :
                     chainIcon === 'polygon-chain.svg' ? '100%' :
                     '100%',
              height: chainIcon === 'base-chain.svg' ? '75%' :
                      chainIcon === 'ethereum-chain.svg' ? '65%' :
                      chainIcon === 'arbitrum-chain.svg' ? '75%' :
                      chainIcon === 'optimism-chain.svg' ? '70%' :
                      chainIcon === 'bsc-chain.svg' ? '100%' :
                      chainIcon === 'polygon-chain.svg' ? '100%' :
                      '100%',
              objectFit: 'contain',
              objectPosition: 'center',
              flexShrink: 0
            }}
            onError={(e) => {
              // Fallback if chain icon fails to load
              const target = e.target as HTMLImageElement;
              target.style.display = 'none';
            }}
          />
        </div>
      )}
    </div>
  )
}

export interface TokenBalance {
  symbol: string
  name: string
  balance: string
  network: string
  icon?: string // URL or component
  usdValue?: string
  currencyIcon?: string // Currency logo filename
  chainIcon?: string // Chain indicator filename
}

export interface WalletPageViewProps {
  tokens: TokenBalance[]
  walletAddress: string
  currentUsername?: string
  onCopyAddress: () => void
  onCheckUsernameAvailability?: (username: string) => Promise<boolean>
  onPurchaseUsername?: (username: string) => Promise<boolean>
}

export function WalletPageView({
  tokens,
  walletAddress,
  currentUsername,
  onCopyAddress,
  onCheckUsernameAvailability,
  onPurchaseUsername,
}: WalletPageViewProps) {
  // Group tokens by network
  const tokensByNetwork = tokens.reduce((acc, token) => {
    if (!acc[token.network]) {
      acc[token.network] = []
    }
    acc[token.network].push(token)
    return acc
  }, {} as Record<string, TokenBalance[]>)

  // Order networks logically
  const networkOrder = ['Base', 'Binance Smart Chain', 'Ethereum', 'Polygon']
  const sortedNetworks = Object.keys(tokensByNetwork).sort((a, b) => {
    const aIndex = networkOrder.indexOf(a)
    const bIndex = networkOrder.indexOf(b)
    if (aIndex === -1 && bIndex === -1) return a.localeCompare(b)
    if (aIndex === -1) return 1
    if (bIndex === -1) return -1
    return aIndex - bIndex
  })

  return (
    <div className="max-w-2xl mx-auto px-4 md:px-8 py-8 md:py-12">
      {/* Wallet Address */}
      <div className="mb-8">
        <h2 className="text-base font-medium text-muted-foreground mb-3">Wallet Address</h2>
        <div className="flex items-center gap-3">
          <div className="flex-1 w-0 bg-secondary rounded-full h-11 px-4 flex items-center">
            <div className="font-mono text-base text-foreground">
              {walletAddress.slice(0, 10)}...{walletAddress.slice(-8)}
            </div>
          </div>
          <Button
            onClick={onCopyAddress}
            variant="secondary"
            size="icon"
          >
            <Copy className="h-5 w-5" />
          </Button>
        </div>
      </div>

      {/* Username Upgrade Section */}
      <div className="mb-8">
        <UsernameUpgradeSection
          currentUsername={currentUsername}
          onCheckAvailability={onCheckUsernameAvailability}
          onPurchase={onPurchaseUsername}
        />
      </div>

      {/* Token Balances - Grouped by Network */}
      <div>
        <h2 className="text-base font-medium text-muted-foreground mb-3">Balances</h2>
        <div className="space-y-6">
          {sortedNetworks.map((network) => (
            <div key={network} className="space-y-2">
              {/* Network Header */}
              <div className="flex items-center gap-2 mb-3">
                <h3 className="text-sm font-semibold text-foreground uppercase tracking-wider">
                  {network}
                </h3>
                <div className="flex-1 h-px bg-border"></div>
              </div>
              
              {/* Tokens for this network */}
              <div className="space-y-2">
                {tokensByNetwork[network].map((token, index) => (
                  <Item
                    key={`${token.symbol}-${token.network}-${index}`}
                    variant="muted"
                  >
                    {/* Token Icon */}
                    <ItemMedia>
                      <TokenIcon 
                        currencyIcon={token.currencyIcon} 
                        chainIcon={token.chainIcon} 
                      />
                    </ItemMedia>

                    {/* Token Info */}
                    <ItemContent>
                      <ItemTitle>
                        {token.symbol}
                      </ItemTitle>
                    </ItemContent>

                    {/* Balance */}
                    <ItemContent className="items-end">
                      <ItemTitle>
                        {token.balance}
                      </ItemTitle>
                      {token.usdValue && (
                        <ItemDescription>
                          ${token.usdValue}
                        </ItemDescription>
                      )}
                    </ItemContent>
                  </Item>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

// solidjs-app/src/components/wallet/WalletPageView.tsx
/**
 * WalletPageView - Presentational component for wallet page
 * Shows wallet address, language settings, and token balances
 */

import { For, Show, createMemo, type Component } from 'solid-js'
import { Icon } from '@/components/icons'
import { Button } from '@/components/ui/button'
import { Item, ItemMedia, ItemContent, ItemTitle, ItemDescription } from '@/components/ui/item'
import { Skeleton } from '@/components/ui/skeleton'
import { LanguageSwitcher } from '@/components/settings/LanguageSwitcher'
import { useTranslation } from '@/lib/i18n'
import type { TokenBalance } from '@/hooks/usePKPBalances'

// Token icon with chain overlay
const TokenIcon: Component<{
  currencyIcon?: string
  chainIcon?: string
}> = (props) => {
  return (
    <div class="relative w-12 h-12 md:w-14 md:h-14">
      <Show when={props.currencyIcon}>
        <div class="w-full h-full rounded-full bg-white p-2 flex items-center justify-center shadow-sm border border-gray-200">
          <img
            src={`/images/${props.currencyIcon}`}
            alt="Currency"
            class="w-full h-full object-contain"
            onError={(e) => {
              const target = e.target as HTMLImageElement
              target.style.display = 'none'
            }}
          />
        </div>
      </Show>

      <Show when={props.chainIcon}>
        <div class="absolute -top-2 -right-2 w-8 h-8 flex items-center justify-center">
          <img
            src={`/images/${props.chainIcon}`}
            alt="Chain"
            class="w-3/4 h-3/4 object-contain"
            onError={(e) => {
              const target = e.target as HTMLImageElement
              target.style.display = 'none'
            }}
          />
        </div>
      </Show>
    </div>
  )
}

// Loading skeleton for token items
const TokenSkeleton: Component = () => {
  return (
    <Item variant="muted">
      <ItemMedia>
        <Skeleton class="w-12 h-12 md:w-14 md:h-14 rounded-full" />
      </ItemMedia>
      <ItemContent>
        <Skeleton class="h-5 w-16 mb-1" />
      </ItemContent>
      <ItemContent class="items-end">
        <Skeleton class="h-5 w-24 mb-1" />
        <Skeleton class="h-4 w-16" />
      </ItemContent>
    </Item>
  )
}

export interface WalletPageViewProps {
  tokens: TokenBalance[]
  walletAddress: string
  onCopyAddress: () => void
  isLoading?: boolean
}

export const WalletPageView: Component<WalletPageViewProps> = (props) => {
  const { t } = useTranslation()

  // Group tokens by network
  const tokensByNetwork = createMemo(() => {
    const grouped: Record<string, TokenBalance[]> = {}
    for (const token of props.tokens) {
      if (!grouped[token.network]) {
        grouped[token.network] = []
      }
      grouped[token.network].push(token)
    }
    return grouped
  })

  // Sort networks
  const sortedNetworks = createMemo(() => {
    const networkOrder = ['Base', 'Ethereum', 'Polygon', 'Arbitrum']
    return Object.keys(tokensByNetwork()).sort((a, b) => {
      const aIndex = networkOrder.indexOf(a)
      const bIndex = networkOrder.indexOf(b)
      if (aIndex === -1 && bIndex === -1) return a.localeCompare(b)
      if (aIndex === -1) return 1
      if (bIndex === -1) return -1
      return aIndex - bIndex
    })
  })

  // Loading state
  if (props.isLoading && props.tokens.length === 0) {
    return (
      <div class="max-w-2xl mx-auto px-4 md:px-8 py-8 md:py-12 space-y-8">
        <div>
          <h2 class="text-base font-medium text-muted-foreground mb-3">{t('wallet.walletAddress')}</h2>
          <div class="flex items-center gap-3">
            <Skeleton class="flex-1 h-11 rounded-full" />
            <Skeleton class="w-11 h-11 rounded-full" />
          </div>
        </div>

        <div>
          <h2 class="text-base font-medium text-muted-foreground mb-3">{t('wallet.balances')}</h2>
          <div class="space-y-2">
            <TokenSkeleton />
            <TokenSkeleton />
            <TokenSkeleton />
          </div>
        </div>
      </div>
    )
  }

  return (
    <div class="max-w-2xl mx-auto px-4 md:px-8 py-8 md:py-12">
      {/* Wallet Address */}
      <div class="mb-8">
        <h2 class="text-base font-medium text-muted-foreground mb-3">{t('wallet.walletAddress')}</h2>
        <div class="flex items-center gap-3">
          <div class="flex-1 w-0 bg-secondary rounded-full h-11 px-4 flex items-center">
            <div class="font-mono text-base text-foreground">
              {props.walletAddress.slice(0, 10)}...{props.walletAddress.slice(-8)}
            </div>
          </div>
          <Button
            onClick={props.onCopyAddress}
            variant="secondary"
            size="icon"
          >
            <Icon name="copy" class="text-xl" />
          </Button>
        </div>
      </div>

      {/* Language Settings */}
      <div class="mb-8">
        <LanguageSwitcher />
      </div>

      {/* Token Balances - Grouped by Network */}
      <div>
        <h2 class="text-base font-medium text-muted-foreground mb-3">{t('wallet.balances')}</h2>
        <div class="space-y-6">
          <For each={sortedNetworks()}>
            {(network) => (
              <div class="space-y-2">
                {/* Network Header */}
                <div class="flex items-center gap-2 mb-3">
                  <h3 class="text-sm font-semibold text-foreground uppercase tracking-wider">
                    {network}
                  </h3>
                  <div class="flex-1 h-px bg-border" />
                </div>

                {/* Tokens for this network */}
                <div class="space-y-2">
                  <For each={tokensByNetwork()[network]}>
                    {(token) => (
                      <Show
                        when={!token.isLoading}
                        fallback={<TokenSkeleton />}
                      >
                        <Item variant="muted">
                          <ItemMedia>
                            <TokenIcon
                              currencyIcon={token.currencyIcon}
                              chainIcon={token.chainIcon}
                            />
                          </ItemMedia>

                          <ItemContent>
                            <ItemTitle>{token.symbol}</ItemTitle>
                          </ItemContent>

                          <ItemContent class="items-end">
                            <ItemTitle>{token.balance}</ItemTitle>
                            <Show when={token.usdValue}>
                              <ItemDescription>${token.usdValue}</ItemDescription>
                            </Show>
                          </ItemContent>
                        </Item>
                      </Show>
                    )}
                  </For>
                </div>
              </div>
            )}
          </For>
        </div>
      </div>
    </div>
  )
}
