// app/src/components/leaderboard/Leaderboard.tsx
import { useTranslation } from 'react-i18next'
import { Spinner } from '@/components/ui/spinner'
import { cn } from '@/lib/utils'

export interface LeaderboardEntry {
  rank: number
  username: string
  score: number
  avatarUrl?: string
  isCurrentUser?: boolean
}

export interface LeaderboardProps {
  entries: LeaderboardEntry[]
  currentUser?: LeaderboardEntry
  isLoading?: boolean
  emptyMessage?: string
  className?: string
}

/**
 * Reusable leaderboard component for displaying student rankings
 * Used by SongPage and ArtistPage
 */
export function Leaderboard({
  entries,
  currentUser,
  isLoading,
  emptyMessage,
  className,
}: LeaderboardProps) {
  const { t } = useTranslation()

  if (isLoading) {
    return (
      <div className={cn('flex items-center justify-center py-12', className)}>
        <Spinner size="lg" />
      </div>
    )
  }

  if (entries.length === 0 && !currentUser) {
    return (
      <div className={cn('flex flex-col items-center justify-center py-12 text-center', className)}>
        <p className="text-muted-foreground">
          {emptyMessage || t('song.noStudentsYet')}
        </p>
      </div>
    )
  }

  return (
    <div className={className}>
      <div className="space-y-2">
        {entries.map((entry) => (
          <div
            key={entry.username}
            className={cn(
              'flex items-center gap-4 px-5 py-4 rounded-2xl',
              entry.isCurrentUser ? 'bg-muted/50' : 'bg-muted/30'
            )}
          >
            <div className="w-10 text-center text-lg font-bold text-muted-foreground">
              #{entry.rank}
            </div>
            {entry.avatarUrl && (
              <img
                src={entry.avatarUrl}
                alt={entry.username}
                className="w-12 h-12 rounded-full object-cover"
              />
            )}
            <p className="flex-1 min-w-0 text-lg font-semibold truncate">
              {entry.username}
            </p>
            <p className="text-lg font-bold tabular-nums">
              {entry.score.toLocaleString()}
            </p>
          </div>
        ))}
      </div>

      {currentUser && !entries.some((e) => e.isCurrentUser) && (
        <div className="mt-4 pt-4 border-t border-border">
          <div className="flex items-center gap-4 px-5 py-4 rounded-2xl bg-primary/10">
            <div className="w-10 text-center text-lg font-bold text-muted-foreground">
              #{currentUser.rank}
            </div>
            {currentUser.avatarUrl && (
              <img
                src={currentUser.avatarUrl}
                alt={currentUser.username}
                className="w-12 h-12 rounded-full object-cover"
              />
            )}
            <p className="flex-1 min-w-0 text-lg font-semibold truncate">
              {currentUser.username}
            </p>
            <p className="text-lg font-bold tabular-nums">
              {currentUser.score.toLocaleString()}
            </p>
          </div>
        </div>
      )}
    </div>
  )
}

// solidjs-app/src/components/leaderboard/Leaderboard.tsx
/**
 * Leaderboard - Reusable leaderboard component for displaying student rankings
 * SolidJS implementation
 */

import { type Component, Show, For } from 'solid-js'
import { cn } from '@/lib/utils'
import { Spinner } from '@/components/ui/spinner'
import { useTranslation } from '@/lib/i18n'
import { Icon } from '@/components/icons'

export interface LeaderboardEntry {
  rank: number
  username: string
  score: number
  avatarUrl?: string
  isCurrentUser?: boolean
}

export interface LeaderboardProps {
  entries: LeaderboardEntry[]
  currentUser?: LeaderboardEntry
  isLoading?: boolean
  emptyMessage?: string
  class?: string
  showTitle?: boolean
}

/**
 * Reusable leaderboard component for displaying student rankings
 * Used by SongPage and ArtistPage
 */
export const Leaderboard: Component<LeaderboardProps> = (props) => {
  const { t } = useTranslation()

  return (
    <>
      {/* Loading state */}
      <Show when={props.isLoading}>
        <div class={cn('flex items-center justify-center py-12', props.class)}>
          <Spinner size="lg" />
        </div>
      </Show>

      {/* Empty state */}
      <Show when={!props.isLoading && props.entries.length === 0 && !props.currentUser}>
        <div class={cn('flex flex-col items-center justify-center py-12 text-center', props.class)}>
          {/* Title with crown icon */}
          <Show when={props.showTitle !== false}>
            <div class="flex items-center gap-2 mb-6">
              <Icon name="crown-cross" weight="fill" class="text-2xl text-yellow-500" />
              <h2 class="text-xl font-bold">{t('leaderboard.rankings')}</h2>
            </div>
          </Show>
          <p class="text-muted-foreground">
            {props.emptyMessage || 'No students yet. Be the first to practice!'}
          </p>
        </div>
      </Show>

      {/* Leaderboard list */}
      <Show when={!props.isLoading && (props.entries.length > 0 || props.currentUser)}>
        <div class={props.class}>
          {/* Title with crown icon */}
          <Show when={props.showTitle !== false}>
            <div class="flex items-center gap-2 mb-4">
              <Icon name="crown-cross" weight="fill" class="text-2xl text-yellow-500" />
              <h2 class="text-xl font-bold">{t('leaderboard.rankings')}</h2>
            </div>
          </Show>
          <div class="space-y-2">
            <For each={props.entries}>
              {(entry) => (
                <div
                  class={cn(
                    'flex items-center gap-4 px-5 py-4 rounded-2xl',
                    entry.isCurrentUser ? 'bg-muted/50' : 'bg-muted/30'
                  )}
                >
                  <div class="w-10 text-center text-lg font-bold text-muted-foreground">
                    #{entry.rank}
                  </div>
                  <Show when={entry.avatarUrl}>
                    <img
                      src={entry.avatarUrl}
                      alt={entry.username}
                      class="w-12 h-12 rounded-full object-cover"
                    />
                  </Show>
                  <p class="flex-1 min-w-0 text-lg font-semibold truncate">
                    {entry.username}
                  </p>
                  <p class="text-lg font-bold tabular-nums">
                    {entry.score.toLocaleString()}
                  </p>
                </div>
              )}
            </For>
          </div>

          {/* Current user (if not in top 10) */}
          <Show when={props.currentUser && !props.entries.some((e) => e.isCurrentUser)}>
            <div class="mt-4 pt-4 border-t border-border">
              <div class="flex items-center gap-4 px-5 py-4 rounded-2xl bg-primary/10">
                <div class="w-10 text-center text-lg font-bold text-muted-foreground">
                  #{props.currentUser!.rank}
                </div>
                <Show when={props.currentUser!.avatarUrl}>
                  <img
                    src={props.currentUser!.avatarUrl}
                    alt={props.currentUser!.username}
                    class="w-12 h-12 rounded-full object-cover"
                  />
                </Show>
                <p class="flex-1 min-w-0 text-lg font-semibold truncate">
                  {props.currentUser!.username}
                </p>
                <p class="text-lg font-bold tabular-nums">
                  {props.currentUser!.score.toLocaleString()}
                </p>
              </div>
            </div>
          </Show>
        </div>
      </Show>
    </>
  )
}
