// solidjs-app/src/components/layout/AuthDialog.tsx
/**
 * AuthDialog for SolidJS
 * Simplified authentication dialog with passkey support
 */

import { createSignal, createEffect, Show, type Component } from 'solid-js'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Spinner } from '@/components/ui/spinner'
import { Key, CheckCircle, AlertCircle, ChevronLeft } from '@/components/icons'
import { useTranslation } from '@/lib/i18n'

type AuthStep = 'select-method' | 'passkey-intro' | 'username' | 'processing' | 'complete'

interface AuthDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void

  // Context state
  currentStep: string
  authMode?: 'register' | 'login' | 'eoa' | null
  isAuthenticating: boolean
  statusMessage: string
  errorMessage: string

  // Actions
  onRegister: () => void
  onRegisterWithUsername: (username: string) => void
  onLogin: () => void
  onUsernameBack: () => void
}

export const AuthDialog: Component<AuthDialogProps> = (props) => {
  const { t } = useTranslation()
  const [view, setView] = createSignal<AuthStep>('select-method')
  const [username, setUsername] = createSignal('')
  const [showErrorDetails, setShowErrorDetails] = createSignal(false)
  const [pendingAuth, setPendingAuth] = createSignal(false)

  // Sync context step to view
  createEffect(() => {
    if (props.currentStep === 'complete') {
      setView('complete')
      setPendingAuth(false)
    }
    if (props.currentStep === 'username') setView('username')
    if (props.currentStep === 'webauthn' || props.currentStep === 'session' ||
        props.currentStep === 'social' || props.currentStep === 'processing') {
      setView('processing')
    }
  })

  // Handle authentication finishing (only when we're not pending and auth stops)
  createEffect(() => {
    // Only fall back if auth finished AND we weren't in a pending state AND there's an error
    if (view() === 'processing' && !props.isAuthenticating && !pendingAuth() && props.errorMessage) {
      setView('passkey-intro')
    }
  })

  // Reset view when closed
  createEffect(() => {
    if (!props.open) {
      setTimeout(() => {
        setView('select-method')
        setUsername('')
        setShowErrorDetails(false)
        setPendingAuth(false)
      }, 300)
    }
  })

  const handleBack = () => {
    if (view() === 'passkey-intro') {
      setView('select-method')
    } else if (view() === 'username') {
      props.onUsernameBack()
      setUsername('')
      setView('passkey-intro')
    }
  }

  const handleUsernameSubmit = (e: Event) => {
    e.preventDefault()
    if (username().trim().length >= 6) {
      setPendingAuth(true)
      setView('processing')
      props.onRegisterWithUsername(username().trim())
    }
  }

  const getTitle = () => {
    switch (view()) {
      case 'passkey-intro':
        return t('auth.usePasskey')
      case 'username':
        return t('auth.chooseUsername')
      case 'processing':
        return t('auth.authenticating')
      case 'complete':
        return t('auth.success')
      default:
        return t('auth.signIn')
    }
  }

  return (
    <Dialog open={props.open} onOpenChange={props.onOpenChange}>
      <DialogContent class="sm:max-w-[400px]">
        <DialogHeader>
          <DialogTitle class="text-2xl text-center">
            {getTitle()}
          </DialogTitle>
        </DialogHeader>

        <div class="py-4">
          {/* ERROR DISPLAY */}
          <Show when={props.errorMessage}>
            <div class="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-sm">
              <div class="flex items-start gap-2">
                <AlertCircle class="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
                <div class="flex-1 min-w-0">
                  <p class="text-red-700">{props.errorMessage}</p>
                  <Show when={props.errorMessage.length > 100}>
                    <button
                      type="button"
                      onClick={() => setShowErrorDetails(!showErrorDetails())}
                      class="mt-2 text-xs text-red-500 hover:text-red-700"
                    >
                      {showErrorDetails() ? t('auth.hideDetails') : t('auth.showDetails')}
                    </button>
                    <Show when={showErrorDetails()}>
                      <pre class="mt-2 p-2 bg-red-100 rounded text-xs text-red-600 overflow-x-auto whitespace-pre-wrap break-all max-h-32 overflow-y-auto">
                        {props.errorMessage}
                      </pre>
                    </Show>
                  </Show>
                </div>
              </div>
            </div>
          </Show>

          {/* STEP 1: METHOD SELECTION */}
          <Show when={view() === 'select-method'}>
            <div class="space-y-3">
              <Button
                onClick={() => setView('passkey-intro')}
                variant="outline"
                class="w-full h-14 justify-start px-4 text-base font-medium gap-3"
              >
                <Key class="w-6 h-6 text-orange-500" />
                <div class="flex flex-col items-start">
                  <span>{t('auth.passkeyRecommended')}</span>
                  <span class="text-xs text-muted-foreground font-normal">{t('auth.noPasswordSecure')}</span>
                </div>
              </Button>
            </div>
          </Show>

          {/* STEP 2A: PASSKEY INTRO */}
          <Show when={view() === 'passkey-intro'}>
            <div class="space-y-4">
              <Button
                onClick={() => {
                  setView('username')
                }}
                class="w-full h-12"
                size="lg"
              >
                {t('auth.createNewAccount')}
              </Button>

              <div class="relative">
                <div class="absolute inset-0 flex items-center">
                  <div class="w-full border-t border-border"></div>
                </div>
                <div class="relative flex justify-center text-xs uppercase">
                  <span class="bg-background px-2 text-muted-foreground">{t('auth.or')}</span>
                </div>
              </div>

              <Button
                onClick={() => {
                  setPendingAuth(true)
                  setView('processing')
                  props.onLogin()
                }}
                variant="outline"
                class="w-full h-12"
              >
                {t('auth.signIn')}
              </Button>

              <Button variant="ghost" size="sm" onClick={handleBack} class="w-full text-muted-foreground">
                <ChevronLeft class="mr-2 h-4 w-4" /> {t('auth.back')}
              </Button>
            </div>
          </Show>

          {/* STEP 2B: USERNAME INPUT */}
          <Show when={view() === 'username'}>
            <form onSubmit={handleUsernameSubmit} class="space-y-4">
              <div class="space-y-2">
                <Input
                  placeholder={t('auth.usernamePlaceholder')}
                  value={username()}
                  onInput={(e) => setUsername(e.currentTarget.value)}
                  minLength={6}
                  class="h-12"
                  autofocus
                />
                <Show when={username().length >= 6}>
                  <span class="text-xs text-green-600 flex items-center gap-1">
                    <CheckCircle class="w-4 h-4" /> {t('auth.validFormat')}
                  </span>
                </Show>
              </div>

              <div class="flex gap-3">
                <Button type="button" variant="outline" onClick={handleBack} class="flex-1">
                  {t('auth.back')}
                </Button>
                <Button
                  type="submit"
                  class="flex-1"
                  disabled={username().length < 6}
                >
                  {t('auth.next')}
                </Button>
              </div>
            </form>
          </Show>

          {/* PROCESSING STATE */}
          <Show when={view() === 'processing'}>
            <div class="flex flex-col items-center py-8 space-y-4 text-center">
              <Spinner size="lg" />
              <p class="text-muted-foreground animate-pulse">
                {props.statusMessage || t('auth.processing')}
              </p>
            </div>
          </Show>

          {/* COMPLETE STATE */}
          <Show when={view() === 'complete'}>
            <div class="flex flex-col items-center py-6 space-y-4">
              <CheckCircle class="w-16 h-16 text-green-500" />
              <p class="text-center text-muted-foreground">
                {t('auth.allSet')}
              </p>
              <Button onClick={() => props.onOpenChange(false)} class="w-full">
                {t('auth.startLearning')}
              </Button>
            </div>
          </Show>
        </div>
      </DialogContent>
    </Dialog>
  )
}

// archived/reference-app/src/components/layout/AuthDialog.tsx
/**
 * AuthDialog
 * Clear two-button authentication with step indicators
 * Separates "Create Account" vs "Sign In" flows
 */

import { useState } from 'react'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Spinner } from '@/components/ui/spinner'
import { CheckCircle } from '@phosphor-icons/react'

/**
 * Auth Step
 */
type AuthStep = 'idle' | 'username' | 'webauthn' | 'session' | 'social' | 'complete'

/**
 * Auth Mode
 */
type AuthMode = 'register' | 'login' | null

export interface AuthDialogProps {
  /** Whether the dialog is open */
  open: boolean
  /** Called when the dialog should close */
  onOpenChange: (open: boolean) => void
  /** Current auth step */
  currentStep: AuthStep
  /** Whether currently authenticating */
  isAuthenticating?: boolean
  /** Current auth mode (register or login) */
  authMode?: AuthMode
  /** Status message for current step */
  statusMessage?: string
  /** Error message */
  errorMessage?: string
  /** Whether PKP is ready */
  isPKPReady?: boolean
  /** Whether user has connected social account */
  hasSocialAccount?: boolean
  /** Username availability status */
  usernameAvailability?: 'checking' | 'available' | 'unavailable' | null
  /** Called when user clicks "Create Account" (shows username input) */
  onRegister?: () => void
  /** Called when user submits username and starts registration */
  onRegisterWithUsername?: (username: string) => void
  /** Called when user clicks "Sign In" */
  onLogin?: () => void
  /** Called when user clicks back from username input */
  onUsernameBack?: () => void
  /** Called when username input changes */
  onUsernameChange?: (username: string) => void
  /** Called when user clicks "Connect Social Account" */
  onConnectSocial?: () => void
}

export function AuthDialog({
  open,
  onOpenChange,
  currentStep,
  isAuthenticating = false,
  authMode = null,
  statusMessage = '',
  errorMessage = '',
  usernameAvailability = null,
  // isPKPReady, // TODO: Use when adding PKP status indicator
  // hasSocialAccount, // TODO: Use when showing social account status
  onRegister,
  onRegisterWithUsername,
  onLogin,
  onUsernameBack,
  onUsernameChange,
  // onConnectSocial, // TODO: Use when adding social account connection
}: AuthDialogProps) {
  // Internal state for username input
  const [username, setUsername] = useState('')

  // Call onUsernameChange when username changes
  const handleUsernameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newUsername = e.target.value
    setUsername(newUsername)
    if (onUsernameChange) {
      onUsernameChange(newUsername)
    }
  }

  // Determine current state
  const isComplete = currentStep === 'complete' && authMode === null
  const isUsernameInput = currentStep === 'username'

  // Handle username submission
  const handleUsernameSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (username.trim().length >= 6 && onRegisterWithUsername) {
      onRegisterWithUsername(username.trim())
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader className="text-left">
          <DialogTitle className="text-2xl">
            {isUsernameInput ? 'Choose Username' : 'Welcome to K-School'}
          </DialogTitle>
          <p className="text-base text-muted-foreground">
            {isUsernameInput
              ? 'Must be 6+ characters, shorter usernames available for payment.'
              : 'Karaoke to 13M+ songs to learn English!'}
          </p>
        </DialogHeader>

        <div className="space-y-4 py-6">
          {/* Initial Choice: Register or Login */}
          {!authMode && !isAuthenticating && !isComplete && !isUsernameInput && (
            <div className="space-y-4">
              <Button
                onClick={onRegister}
                disabled={isAuthenticating}
                className="w-full h-14 text-base"
                variant="default"
                size="lg"
              >
                Create Account
              </Button>

              <div className="relative">
                <div className="absolute inset-0 flex items-center">
                  <div className="w-full border-t border-border"></div>
                </div>
                <div className="relative flex justify-center text-base">
                  <span className="bg-background px-4 text-muted-foreground">or</span>
                </div>
              </div>

              <Button
                onClick={onLogin}
                disabled={isAuthenticating}
                className="w-full h-14 text-base"
                variant="outline"
                size="lg"
              >
                Sign In
              </Button>
            </div>
          )}

          {/* Username Input - shown after "Create Account" */}
          {isUsernameInput && (
            <form onSubmit={handleUsernameSubmit} className="space-y-6">
              <div className="space-y-2">
                <Input
                  id="username"
                  type="text"
                  placeholder="alice"
                  value={username}
                  onChange={handleUsernameChange}
                  className="h-12 text-base"
                  autoFocus
                  minLength={6}
                  maxLength={26}
                  pattern="[a-zA-Z0-9_\-]+"
                  disabled={isAuthenticating}
                  required
                />

                {/* Availability Indicator */}
                {username.trim().length >= 6 && (
                  <div className="flex items-center gap-2 text-sm">
                    {usernameAvailability === 'checking' && (
                      <>
                        <Spinner className="size-3" />
                        <span className="text-muted-foreground">Checking availability...</span>
                      </>
                    )}
                    {usernameAvailability === 'available' && (
                      <span className="text-green-500">✓ Available</span>
                    )}
                    {usernameAvailability === 'unavailable' && (
                      <span className="text-destructive">✗ Not Available</span>
                    )}
                  </div>
                )}
              </div>

              <div className="flex gap-3 w-full">
                <Button
                  type="button"
                  onClick={onUsernameBack}
                  disabled={isAuthenticating}
                  className="flex-1 h-14 text-base"
                  variant="outline"
                  size="lg"
                >
                  Back
                </Button>

                <Button
                  type="submit"
                  disabled={
                    username.trim().length < 6 ||
                    isAuthenticating ||
                    usernameAvailability === 'checking' ||
                    usernameAvailability === 'unavailable'
                  }
                  className="flex-1 h-14 text-base"
                  variant="default"
                  size="lg"
                >
                  {isAuthenticating && <Spinner size="sm" />}
                  Continue
                </Button>
              </div>
            </form>
          )}

          {/* Progress/Loading State - show during any auth flow (except username input) */}
          {(authMode || isAuthenticating) && !isComplete && !isUsernameInput && (
            <div className="space-y-4 py-8">
              <div className="flex flex-col items-center gap-4">
                <Spinner className="w-12 h-12" />
                {statusMessage && (
                  <p className="text-base text-center text-muted-foreground">
                    {statusMessage}
                  </p>
                )}
              </div>

              {/* Error Message */}
              {errorMessage && (
                <div className="text-base text-center p-4 bg-destructive/10 text-destructive rounded-lg break-words" style={{ overflowWrap: 'anywhere' }}>
                  {errorMessage}
                </div>
              )}
            </div>
          )}

          {/* Complete State */}
          {isComplete && (
            <div className="space-y-4">
              <div className="text-center py-4">
                <CheckCircle className="w-16 h-16 text-green-500 mx-auto mb-4" weight="fill" />
                <p className="text-base text-muted-foreground">
                  You're all set!
                </p>
              </div>

              <Button
                onClick={() => onOpenChange(false)}
                className="w-full h-14 text-base"
                variant="default"
                size="lg"
              >
                Continue
              </Button>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  )
}
