// app/src/components/artist/ArtistPage.tsx
import { useTranslation } from 'react-i18next'
import { DotsThree, MusicNote } from '@phosphor-icons/react'
import { BackButton } from '@/components/ui/back-button'
import { Button } from '@/components/ui/button'
import { Spinner } from '@/components/ui/spinner'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import { Leaderboard, type LeaderboardEntry } from '@/components/leaderboard/Leaderboard'
import { cn } from '@/lib/utils'

export interface ArtistSong {
  id: string
  title: string
  coverUrl?: string
  onClick?: () => void
}

// Re-export LeaderboardEntry as StudentEntry for backwards compatibility
export type StudentEntry = LeaderboardEntry

export interface ArtistPageProps {
  artistName: string
  imageUrl?: string
  songs: ArtistSong[]
  isLoadingSongs?: boolean
  students: StudentEntry[]
  isLoadingStudents?: boolean
  currentUser?: StudentEntry
  onBack?: () => void
  onSongClick?: (song: ArtistSong) => void
  onStudentsTabClick?: () => void
  className?: string
}

/**
 * Artist detail page with songs and student leaderboard
 * Matches SongPage structure with tabs
 */
export function ArtistPage({
  artistName,
  imageUrl,
  songs,
  isLoadingSongs,
  students,
  isLoadingStudents,
  currentUser,
  onBack,
  onSongClick,
  onStudentsTabClick,
  className,
}: ArtistPageProps) {
  const { t } = useTranslation()

  const handleTabChange = (value: string) => {
    if (value === 'students' && onStudentsTabClick) {
      onStudentsTabClick()
    }
  }

  return (
    <div className={cn('relative w-full h-screen bg-background flex items-center justify-center', className)}>
      <div className="relative w-full h-full md:max-w-6xl flex flex-col">
        {/* Header */}
        <div className="absolute top-0 left-0 right-0 z-50">
          <div className="flex items-center justify-between h-12 px-4">
            <BackButton onClick={onBack} variant="floating" />
            <Button
              variant="ghost"
              size="icon"
              className="shrink-0 opacity-0 pointer-events-none"
              aria-hidden
            >
              <DotsThree className="w-6 h-6" weight="bold" />
            </Button>
          </div>
        </div>

        {/* Main content */}
        <div className="flex-1 overflow-y-auto overflow-x-hidden">
          {/* Artist Hero */}
          <div className="relative w-full" style={{ height: 'min(384px, 40vh)' }}>
            {imageUrl ? (
              <img
                src={imageUrl}
                alt={artistName}
                className="w-full h-full object-cover"
              />
            ) : (
              <div className="w-full h-full bg-gradient-to-br from-primary/30 to-primary/10 flex items-center justify-center">
                <MusicNote className="w-24 h-24 text-primary/40" weight="fill" />
              </div>
            )}
            <div
              className="absolute inset-0"
              style={{
                background: 'linear-gradient(to bottom, rgba(0,0,0,0) 0%, rgba(0,0,0,0.6) 50%, rgba(0,0,0,0.95) 100%)'
              }}
            />
            <div className="absolute bottom-0 left-0 right-0 p-6">
              <div className="flex items-center gap-3">
                <div className="flex-1 min-w-0">
                  <h1 className="text-foreground text-2xl md:text-4xl font-bold">
                    {artistName}
                  </h1>
                </div>
              </div>
            </div>
          </div>

          <div className="px-4 mt-4 space-y-4 pb-8">
            {/* Tabs: Songs | Students */}
            <Tabs defaultValue="songs" className="w-full" onValueChange={handleTabChange}>
              <TabsList className="w-full grid grid-cols-2 bg-muted/50">
                <TabsTrigger value="songs">{t('artist.songsTab', 'Songs')}</TabsTrigger>
                <TabsTrigger value="students">{t('artist.studentsTab', 'Students')}</TabsTrigger>
              </TabsList>

              <TabsContent value="songs" className="mt-4">
                {isLoadingSongs ? (
                  <div className="flex items-center justify-center py-12">
                    <Spinner size="lg" />
                  </div>
                ) : songs.length === 0 ? (
                  <div className="text-center py-12 text-muted-foreground">
                    {t('artist.noSongs', 'No songs available')}
                  </div>
                ) : (
                  <div className="space-y-2">
                    {songs.map((song) => (
                      <button
                        key={song.id}
                        onClick={() => {
                          song.onClick?.()
                          onSongClick?.(song)
                        }}
                        className="w-full flex items-center gap-4 p-3 rounded-xl hover:bg-muted/50 transition-colors text-left"
                      >
                        {/* Song Cover */}
                        <div className="w-14 h-14 rounded-lg bg-muted flex-shrink-0 overflow-hidden">
                          {song.coverUrl ? (
                            <img
                              src={song.coverUrl}
                              alt={song.title}
                              className="w-full h-full object-cover"
                            />
                          ) : (
                            <div className="w-full h-full flex items-center justify-center">
                              <MusicNote className="w-6 h-6 text-muted-foreground" />
                            </div>
                          )}
                        </div>

                        {/* Song Info */}
                        <div className="flex-1 min-w-0">
                          <p className="font-medium truncate">{song.title}</p>
                        </div>
                      </button>
                    ))}
                  </div>
                )}
              </TabsContent>

              <TabsContent value="students" className="mt-4">
                <Leaderboard
                  entries={students}
                  currentUser={currentUser}
                  isLoading={isLoadingStudents}
                />
              </TabsContent>
            </Tabs>
          </div>
        </div>
      </div>
    </div>
  )
}

// solidjs-app/src/pages/ArtistPage.tsx
import { type Component, Show, For, createMemo } from 'solid-js'
import { useParams, useNavigate } from '@solidjs/router'
import { useArtist } from '@/hooks/useArtist'
import { useArtistLeaderboard } from '@/hooks/useArtistLeaderboard'
import { Leaderboard } from '@/components/leaderboard/Leaderboard'
import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import { Icon } from '@/components/icons'
import { convertGroveUri } from '@/lib/lens/utils'
import { cn } from '@/lib/utils'
import { useTranslation } from '@/lib/i18n'

/**
 * Skeleton loading state for ArtistPage
 * Matches the layout to prevent content jump
 */
export const ArtistPageSkeleton: Component<{ class?: string }> = (props) => {
  return (
    <div class={cn('relative w-full h-screen bg-background flex items-center justify-center', props.class)}>
      <div class="relative w-full h-full md:max-w-6xl flex flex-col">
        {/* Header skeleton */}
        <div class="absolute top-0 left-0 right-0 z-50">
          <div class="flex items-center justify-between h-12 px-4">
            <Skeleton class="w-10 h-10 rounded-full" />
            <div class="w-10 h-10" /> {/* Spacer for hidden button */}
          </div>
        </div>

        {/* Main content */}
        <div class="flex-1 overflow-y-auto overflow-x-hidden">
          {/* Artist Hero skeleton */}
          <div class="relative w-full" style={{ height: 'min(384px, 40vh)' }}>
            <Skeleton class="w-full h-full" />
            <div
              class="absolute inset-0"
              style={{
                background: 'linear-gradient(to bottom, rgba(0,0,0,0) 0%, rgba(0,0,0,0.6) 50%, rgba(0,0,0,0.95) 100%)'
              }}
            />
            <div class="absolute bottom-0 left-0 right-0 p-6">
              <Skeleton class="h-8 w-48 md:h-10 md:w-64 rounded-lg" />
            </div>
          </div>

          <div class="px-4 mt-4 space-y-4 pb-8">
            {/* Tabs skeleton */}
            <div class="w-full">
              <Skeleton class="w-full h-10 rounded-lg" />

              {/* Songs list skeleton - matches song item layout */}
              <div class="mt-4 space-y-2">
                <For each={[1, 2, 3, 4, 5]}>
                  {() => (
                    <div class="flex items-center gap-4 p-3 rounded-xl">
                      <Skeleton class="w-14 h-14 rounded-lg flex-shrink-0" />
                      <Skeleton class="flex-1 h-5 rounded-lg" />
                    </div>
                  )}
                </For>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

/**
 * Artist Page (SolidJS)
 *
 * Route: /:artistSlug (e.g., /queen, /eminem, /britney-spears)
 *
 * Displays artist info and their songs.
 */
export const ArtistPage: Component = () => {
  const params = useParams<{ artistSlug: string }>()
  const navigate = useNavigate()
  const { t } = useTranslation()

  const artist = useArtist(() => params.artistSlug)

  // Extract spotify track IDs for leaderboard query
  const spotifyTrackIds = createMemo(() =>
    artist.data?.songs?.map(s => s.spotifyTrackId) ?? []
  )

  // Lazy-loaded leaderboard
  const { leaderboard, isLoading: isLoadingLeaderboard, hasLoaded, refetch: fetchLeaderboard } = useArtistLeaderboard(spotifyTrackIds)

  // Handle Rankings tab click - lazy load
  const handleRankingsTabClick = () => {
    if (!hasLoaded() && !isLoadingLeaderboard() && spotifyTrackIds().length > 0) {
      fetchLeaderboard()
    }
  }

  // Transform songs for display
  const songs = createMemo(() => {
    if (!artist.data?.songs) return []

    return artist.data.songs.map((song) => {
      const coverUrl = song.coverUri
        ? song.coverUri.startsWith('https://')
          ? song.coverUri
          : convertGroveUri(song.coverUri)
        : undefined

      return {
        id: song.spotifyTrackId,
        title: song.title,
        coverUrl,
        artistSlug: song.artistSlug,
        songSlug: song.songSlug,
      }
    })
  })

  const handleBack = () => navigate(-1)

  const handleSongClick = (song: { artistSlug: string; songSlug: string }) => {
    navigate(`/${song.artistSlug}/${song.songSlug}`)
  }

  return (
    <>
      {/* Loading */}
      <Show when={artist.isLoading}>
        <ArtistPageSkeleton />
      </Show>

      {/* Error / Not found */}
      <Show when={!artist.isLoading && (artist.error || !artist.data)}>
        <div class="flex flex-col items-center justify-center h-screen gap-4 px-4">
          <h1 class="text-xl sm:text-2xl font-bold text-center">Artist not found</h1>
          <p class="text-muted-foreground text-center">
            No artist found for "{params.artistSlug}"
          </p>
          <button onClick={() => navigate('/')} class="text-primary hover:underline">
            Go home
          </button>
        </div>
      </Show>

      {/* Artist Page */}
      <Show when={!artist.isLoading && artist.data}>
        <div class="relative w-full h-screen bg-background flex items-center justify-center">
          <div class="relative w-full h-full md:max-w-6xl flex flex-col">
            {/* Header */}
            <div class="absolute top-0 left-0 right-0 z-50 pt-safe">
              <div class="flex items-center justify-between p-4">
                <button
                  onClick={handleBack}
                  class="w-10 h-10 rounded-full flex items-center justify-center bg-black/30 hover:bg-black/50 transition-colors"
                >
                  <Icon name="caret-left" class="text-2xl text-white" />
                </button>
                {/* Placeholder for symmetry */}
                <div class="w-10 h-10" />
              </div>
            </div>

            {/* Main content */}
            <div class="flex-1 overflow-y-auto overflow-x-hidden">
              {/* Artist Hero */}
              <div class="relative w-full" style={{ height: 'min(384px, 40vh)' }}>
                <Show
                  when={artist.data!.imageUrl}
                  fallback={
                    <div class="w-full h-full bg-gradient-to-br from-primary/30 to-primary/10 flex items-center justify-center">
                      <Icon name="music-note" class="text-8xl text-primary/40" />
                    </div>
                  }
                >
                  <img
                    src={artist.data!.imageUrl}
                    alt={artist.data!.name}
                    class="w-full h-full object-cover"
                  />
                </Show>
                <div
                  class="absolute inset-0"
                  style={{
                    background: 'linear-gradient(to bottom, rgba(0,0,0,0) 0%, rgba(0,0,0,0.6) 50%, rgba(0,0,0,0.95) 100%)'
                  }}
                />
                <div class="absolute bottom-0 left-0 right-0 p-6">
                  <div class="flex items-center gap-3">
                    <div class="flex-1 min-w-0">
                      <h1 class="text-foreground text-2xl md:text-4xl font-bold">
                        {artist.data!.name}
                      </h1>
                    </div>
                  </div>
                </div>
              </div>

              <div class="px-4 mt-4 space-y-4 pb-8">
                {/* Tabs: Songs | Rankings */}
                <Tabs defaultValue="songs" class="w-full" onChange={(val) => val === 'rankings' && handleRankingsTabClick()}>
                  <TabsList class="w-full grid grid-cols-2 bg-muted/50">
                    <TabsTrigger value="songs">{t('nav.songs')}</TabsTrigger>
                    <TabsTrigger value="rankings">{t('leaderboard.rankings')}</TabsTrigger>
                  </TabsList>

                  <TabsContent value="songs" class="mt-4">
                    <Show
                      when={songs().length > 0}
                      fallback={
                        <div class="text-center py-12 text-muted-foreground">
                          No songs available
                        </div>
                      }
                    >
                      <div class="space-y-2">
                        <For each={songs()}>
                          {(song) => (
                            <button
                              onClick={() => handleSongClick(song)}
                              class="w-full flex items-center gap-4 p-3 rounded-xl hover:bg-muted/50 transition-colors text-left"
                            >
                              {/* Song Cover */}
                              <div class="w-14 h-14 rounded-lg bg-muted flex-shrink-0 overflow-hidden">
                                <Show
                                  when={song.coverUrl}
                                  fallback={
                                    <div class="w-full h-full flex items-center justify-center">
                                      <Icon name="music-note" class="text-xl text-muted-foreground" />
                                    </div>
                                  }
                                >
                                  <img
                                    src={song.coverUrl}
                                    alt={song.title}
                                    class="w-full h-full object-cover"
                                  />
                                </Show>
                              </div>

                              {/* Song Info */}
                              <div class="flex-1 min-w-0">
                                <p class="font-medium truncate">{song.title}</p>
                              </div>
                            </button>
                          )}
                        </For>
                      </div>
                    </Show>
                  </TabsContent>

                  <TabsContent value="rankings" class="mt-4">
                    <Leaderboard
                      entries={leaderboard().map(e => ({
                        rank: e.rank,
                        username: e.username,
                        score: e.totalPoints,
                      }))}
                      isLoading={isLoadingLeaderboard()}
                      showTitle={false}
                      emptyMessage="No students yet. Be the first to practice!"
                    />
                  </TabsContent>
                </Tabs>
              </div>
            </div>
          </div>
        </div>
      </Show>
    </>
  )
}
