// app/src/components/leaderboard/Leaderboard.tsx
/**
 * Leaderboard - Reusable leaderboard component for displaying student rankings
 * SolidJS implementation
 */

import { type Component, Show, For } from 'solid-js'
import { cn } from '@/lib/utils'
import { Spinner } from '@/components/ui/spinner'
import { useTranslation } from '@/lib/i18n'
import { Icon } from '@/components/icons'

// Use the shared display type
export type { LeaderboardDisplayEntry as LeaderboardEntry } from '@/types/leaderboard'
import type { LeaderboardDisplayEntry } from '@/types/leaderboard'

type LeaderboardEntry = LeaderboardDisplayEntry

export interface LeaderboardProps {
  entries: LeaderboardEntry[]
  currentUser?: LeaderboardEntry
  isLoading?: boolean
  emptyMessage?: string
  class?: string
  showTitle?: boolean
  /** Called when a user entry is clicked */
  onUserClick?: (entry: LeaderboardEntry) => void
}

/**
 * Reusable leaderboard component for displaying student rankings
 * Used by SongPage and ArtistPage
 */
export const Leaderboard: Component<LeaderboardProps> = (props) => {
  const { t } = useTranslation()

  return (
    <>
      {/* Loading state */}
      <Show when={props.isLoading}>
        <div class={cn('flex items-center justify-center py-12', props.class)}>
          <Spinner size="lg" />
        </div>
      </Show>

      {/* Empty state */}
      <Show when={!props.isLoading && props.entries.length === 0 && !props.currentUser}>
        <div class={cn('flex flex-col items-center justify-center py-12 text-center', props.class)}>
          {/* Title with crown icon */}
          <Show when={props.showTitle !== false}>
            <div class="flex items-center gap-2 mb-6">
              <Icon name="crown-cross" weight="fill" class="text-2xl text-yellow-500" />
              <h2 class="text-xl font-bold">{t('leaderboard.rankings')}</h2>
            </div>
          </Show>
          <p class="text-muted-foreground">
            {props.emptyMessage || t('leaderboard.noStudentsYet')}
          </p>
        </div>
      </Show>

      {/* Leaderboard list */}
      <Show when={!props.isLoading && (props.entries.length > 0 || props.currentUser)}>
        <div class={props.class}>
          {/* Title with crown icon */}
          <Show when={props.showTitle !== false}>
            <div class="flex items-center gap-2 mb-4">
              <Icon name="crown-cross" weight="fill" class="text-2xl text-yellow-500" />
              <h2 class="text-xl font-bold">{t('leaderboard.rankings')}</h2>
            </div>
          </Show>
          <div class="space-y-2">
            <For each={props.entries}>
              {(entry) => {
                const isClickable = () => props.onUserClick && (entry.handle || entry.username)
                const handleClick = () => {
                  if (isClickable()) {
                    props.onUserClick?.(entry)
                  }
                }

                return (
                  <div
                    class={cn(
                      'flex items-center gap-4 px-5 py-4 rounded-2xl',
                      entry.isCurrentUser ? 'bg-muted/50' : 'bg-muted/30',
                      isClickable() && 'cursor-pointer hover:bg-muted/60 transition-colors'
                    )}
                    onClick={handleClick}
                  >
                    <div class="w-10 flex justify-center text-lg font-bold text-muted-foreground">
                      <Show when={entry.rank === 1} fallback={`#${entry.rank}`}>
                        <Icon name="crown-cross" weight="fill" class="text-2xl text-yellow-500" />
                      </Show>
                    </div>
                    <Show when={entry.avatarUrl}>
                      <img
                        src={entry.avatarUrl}
                        alt={entry.username}
                        class="w-12 h-12 rounded-full object-cover"
                      />
                    </Show>
                    <p class="flex-1 min-w-0 text-lg font-semibold truncate">
                      {entry.username}
                    </p>
                    <p class="text-lg font-bold tabular-nums">
                      {entry.score.toLocaleString()}
                    </p>
                  </div>
                )
              }}
            </For>
          </div>

          {/* Current user (if not in top 10) */}
          <Show when={props.currentUser && !props.entries.some((e) => e.isCurrentUser)}>
            {(() => {
              const currentUserEntry = props.currentUser!
              const isClickable = () => props.onUserClick && (currentUserEntry.handle || currentUserEntry.username)
              const handleClick = () => {
                if (isClickable()) {
                  props.onUserClick?.(currentUserEntry)
                }
              }

              return (
                <div class="mt-4 pt-4 border-t border-border">
                  <div
                    class={cn(
                      'flex items-center gap-4 px-5 py-4 rounded-2xl bg-primary/10',
                      isClickable() && 'cursor-pointer hover:bg-primary/20 transition-colors'
                    )}
                    onClick={handleClick}
                  >
                    <div class="w-10 flex justify-center text-lg font-bold text-muted-foreground">
                      <Show when={currentUserEntry.rank === 1} fallback={`#${currentUserEntry.rank}`}>
                        <Icon name="crown-cross" weight="fill" class="text-2xl text-yellow-500" />
                      </Show>
                    </div>
                    <Show when={currentUserEntry.avatarUrl}>
                      <img
                        src={currentUserEntry.avatarUrl}
                        alt={currentUserEntry.username}
                        class="w-12 h-12 rounded-full object-cover"
                      />
                    </Show>
                    <p class="flex-1 min-w-0 text-lg font-semibold truncate">
                      {currentUserEntry.username}
                    </p>
                    <p class="text-lg font-bold tabular-nums">
                      {currentUserEntry.score.toLocaleString()}
                    </p>
                  </div>
                </div>
              )
            })()}
          </Show>
        </div>
      </Show>
    </>
  )
}

// app/src/components/school/Leaderboard.tsx
import { cn } from '@/lib/utils'
import { Item, ItemMedia, ItemContent, ItemTitle, ItemActions } from '@/components/ui/item'

export type LeaderboardEntry = {
  rank: number
  username: string
  score: number
  avatarUrl?: string
  isCurrentUser?: boolean
  onProfileClick?: () => void
}

export type LeaderboardProps = {
  entries: LeaderboardEntry[]
  currentUser?: LeaderboardEntry
  className?: string
}

// Minimalistic leaderboard: top 3 + current user as 4th slot
export function Leaderboard({
  entries,
  currentUser,
  className,
}: LeaderboardProps) {
  // Get top 3 entries
  const topThree = entries.slice(0, 3)

  // Display entries: top 3 + current user (if provided and not in top 3)
  const displayEntries = [...topThree]
  if (currentUser && !topThree.find(e => e.username === currentUser.username)) {
    displayEntries.push(currentUser)
  }

  return (
    <div className={cn('w-full', className)}>
      <div className="space-y-0.5">
        {displayEntries.map((entry) => (
          <Item
            key={`${entry.rank}-${entry.username}`}
            variant="default"
            asChild
            className="gap-3 p-2 hover:bg-secondary/50 transition-colors"
          >
            <button onClick={entry.onProfileClick} className="w-full cursor-pointer">
              {/* Rank */}
              <div className="flex items-center justify-center w-6 flex-shrink-0">
                <span className="text-base font-semibold text-muted-foreground">
                  {entry.rank}
                </span>
              </div>

              {/* Avatar */}
              <ItemMedia variant="image" className="size-12 self-center translate-y-0">
                {entry.avatarUrl ? (
                  <img
                    src={entry.avatarUrl}
                    alt={entry.username}
                    className="w-full h-full rounded-sm object-cover"
                  />
                ) : (
                  <div className="w-full h-full rounded-sm bg-gradient-to-br from-pink-400 to-purple-600" />
                )}
              </ItemMedia>

              {/* Username */}
              <ItemContent className="min-w-0">
                <ItemTitle className="w-full truncate text-left text-base font-semibold">
                  {entry.username}
                </ItemTitle>
              </ItemContent>

              {/* Score */}
              <ItemActions>
                <div className="font-semibold text-muted-foreground text-base">
                  {entry.score.toLocaleString()}
                </div>
              </ItemActions>
            </button>
          </Item>
        ))}
      </div>
    </div>
  )
}
