// app/src/components/profile/VideoGrid.tsx
import { cn } from '@/lib/utils'
import { VideoThumbnail } from '../feed/VideoThumbnail'

export interface Video {
  id: string
  thumbnailUrl: string
  playCount: number
  videoUrl?: string
}

export interface VideoGridProps {
  videos: Video[]
  onVideoClick?: (video: Video) => void
  isLoading?: boolean
  className?: string
}

/**
 * VideoGrid - Clean responsive grid for profile videos
 * 3 columns on mobile, 4-6 columns on desktop based on viewport width
 * Caps at 6 columns max (like TikTok)
 */
export function VideoGrid({
  videos,
  onVideoClick,
  isLoading = false,
  className
}: VideoGridProps) {
  // Loading skeleton
  if (isLoading) {
    return (
      <div className={cn('px-4 md:px-6', className)}>
        <div className="grid grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-1 md:gap-2">
          {Array.from({ length: 12 }).map((_, i) => (
            <div
              key={i}
              className="aspect-[9/16] bg-neutral-800 rounded-md animate-pulse"
            />
          ))}
        </div>
      </div>
    )
  }

  // Empty state
  if (videos.length === 0) {
    return (
      <div className={cn('px-4 md:px-6', className)}>
        <div className="flex flex-col items-center justify-center py-16 text-center">
          <div className="w-24 h-24 bg-neutral-800 rounded-full flex items-center justify-center mb-4">
            <svg
              className="w-12 h-12 text-neutral-600"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"
              />
            </svg>
          </div>
          <p className="text-neutral-400 text-base">No videos yet</p>
        </div>
      </div>
    )
  }

  // Video grid
  return (
    <div className={cn('px-4 md:px-6', className)}>
      <div className="grid grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-1 md:gap-2">
        {videos.map((video) => (
          <VideoThumbnail
            key={video.id}
            thumbnailUrl={video.thumbnailUrl}
            playCount={video.playCount}
            onClick={() => onVideoClick?.(video)}
          />
        ))}
      </div>
    </div>
  )
}

// solidjs-app/src/components/video/VideoGrid.tsx
/**
 * VideoGrid - Responsive grid for video posts
 * SolidJS implementation
 */

import { type Component, Show, For } from 'solid-js'
import { cn } from '@/lib/utils'
import { VideoThumbnail } from '@/components/ui/video-thumbnail'
import { Play } from '@/components/icons'

export interface VideoPost {
  id: string
  thumbnailUrl: string
  username: string
}

export interface VideoGridProps {
  videos: VideoPost[]
  onVideoClick?: (video: VideoPost) => void
  isLoading?: boolean
  showUsernames?: boolean
  class?: string
}

/**
 * VideoGrid - Responsive grid for video posts
 * - Mobile: 3 columns
 * - Desktop: 4-6 columns based on viewport width (like TikTok)
 * - No lock state, just clean video thumbnails
 */
export const VideoGrid: Component<VideoGridProps> = (props) => {
  return (
    <>
      {/* Loading skeleton */}
      <Show when={props.isLoading}>
        <div class={cn(props.class)}>
          <div class="grid grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-1 md:gap-2">
            <For each={[1, 2, 3]}>
              {() => (
                <div class="aspect-[9/16] bg-neutral-800 rounded-md animate-pulse" />
              )}
            </For>
          </div>
        </div>
      </Show>

      {/* Empty state */}
      <Show when={!props.isLoading && props.videos.length === 0}>
        <div class={cn(props.class)}>
          <div class="flex flex-col items-center justify-center py-16 text-center">
            <div class="w-24 h-24 bg-neutral-800 rounded-full flex items-center justify-center mb-4">
              <Play class="w-12 h-12 text-neutral-600" />
            </div>
            <p class="text-neutral-400 text-base">No videos yet</p>
          </div>
        </div>
      </Show>

      {/* Video grid */}
      <Show when={!props.isLoading && props.videos.length > 0}>
        <div class={cn(props.class)}>
          <div class="grid grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-1 md:gap-2">
            <For each={props.videos}>
              {(video) => (
                <div class="relative">
                  <VideoThumbnail
                    src={video.thumbnailUrl}
                    alt={`Video by ${video.username}`}
                    aspectRatio="9/16"
                    onClick={() => props.onVideoClick?.(video)}
                  />
                  <Show when={props.showUsernames !== false}>
                    <div class="absolute bottom-0 left-0 right-0 p-1 bg-gradient-to-t from-black/70 to-transparent">
                      <p class="text-white text-xs truncate">@{video.username}</p>
                    </div>
                  </Show>
                </div>
              )}
            </For>
          </div>
        </div>
      </Show>
    </>
  )
}
