// solidjs-app/src/App.tsx
import { Router, Route, useLocation, useNavigate } from '@solidjs/router'
import { createSignal, createEffect, onMount, type Component, type ParentComponent } from 'solid-js'
import { preloadChatImages } from '@/hooks/usePrefetch'

// Providers
import { QueryProvider } from '@/providers/QueryProvider'
import { LensProvider } from '@/providers/LensProvider'
import { Web3Provider } from '@/providers/Web3Provider'
import { AuthProvider, useAuth } from '@/contexts/AuthContext'
import { LanguagePreferenceProvider } from '@/contexts/LanguagePreferenceContext'
import { VideoPlaybackProvider } from '@/contexts/VideoPlaybackContext'
import { CurrencyProvider } from '@/contexts/CurrencyContext'
import { I18nProvider } from '@/lib/i18n'

// Layout
import { AppLayout } from '@/components/layout/AppLayout'
import { ConnectedAuthDialog } from '@/components/layout/ConnectedAuthDialog'
import { Toaster } from '@/components/ui/sonner'

// Pages
import { HomePage } from '@/pages/HomePage'
import { SearchPage } from '@/pages/SearchPage'
import { ChatPage } from '@/pages/ChatPage'
import { StudyPage } from '@/pages/StudyPage'
import { StudySessionPage } from '@/pages/StudySessionPage'
import { WalletPage } from '@/pages/WalletPage'
import { SongDetailPage } from '@/pages/SongDetailPage'
import { SongPlayPage } from '@/pages/SongPlayPage'
import { ArtistPage } from '@/pages/ArtistPage'
import { FeedPage } from '@/pages/FeedPage'
import { UserProfilePage } from '@/pages/UserProfilePage'

const AppShell: ParentComponent = (props) => {
  const location = useLocation()
  const navigate = useNavigate()
  const [activeTab, setActiveTab] = createSignal<'home' | 'study' | 'songs' | 'chat' | 'wallet' | 'none'>('home')
  const [showAuthDialog, setShowAuthDialog] = createSignal(false)

  const auth = useAuth()

  // Preload chat images on app mount
  onMount(() => {
    preloadChatImages()
  })

  // Register the auth dialog opener
  createEffect(() => {
    auth.setAuthDialogOpener(() => setShowAuthDialog(true))
  })

  // Update active tab based on route
  createEffect(() => {
    const pathToTab: Record<string, 'home' | 'study' | 'songs' | 'chat' | 'wallet'> = {
      '/': 'home',
      '/songs': 'songs',
      '/study': 'study',
      '/chat': 'chat',
      '/wallet': 'wallet',
    }

    const pathParts = location.pathname.split('/').filter(Boolean)
    const reservedPaths = ['songs', 'study', 'chat', 'wallet', 'u', 'song']

    if (location.pathname.startsWith('/song/') || location.pathname.startsWith('/u/') ||
        (pathParts.length === 1 && !reservedPaths.includes(pathParts[0])) ||
        (pathParts.length >= 2 && !reservedPaths.includes(pathParts[0]))) {
      setActiveTab('none')
    } else if (location.pathname.startsWith('/chat')) {
      setActiveTab('chat')
    } else {
      setActiveTab(pathToTab[location.pathname] || 'home')
    }
  })

  const handleTabChange = (tab: 'home' | 'study' | 'songs' | 'chat' | 'wallet') => {
    const routes = {
      home: '/',
      study: '/study',
      songs: '/songs',
      chat: '/chat',
      wallet: '/wallet',
    }
    navigate(routes[tab])
  }

  // Determine if footer should be hidden
  const hideMobileFooter = () => {
    const pathParts = location.pathname.split('/').filter(Boolean)
    const reservedPaths = ['songs', 'study', 'chat', 'wallet', 'u', 'song']

    return (
      !!location.pathname.match(/^\/song\//) ||
      !!location.pathname.match(/^\/u\/[^/]+\/video\//) ||
      (pathParts.length === 1 && !reservedPaths.includes(pathParts[0])) ||
      (pathParts.length >= 2 && !reservedPaths.includes(pathParts[0])) ||
      (location.pathname.startsWith('/chat/') && pathParts.length >= 2)
    )
  }

  return (
    <>
      <AppLayout
        activeTab={activeTab()}
        onTabChange={handleTabChange}
        isConnected={auth.isPKPReady()}
        isCheckingSession={auth.isCheckingSession()}
        walletAddress={auth.pkpAddress() || undefined}
        onConnectWallet={() => setShowAuthDialog(true)}
        hideMobileFooter={hideMobileFooter()}
      >
        {props.children}
      </AppLayout>

      <ConnectedAuthDialog
        open={showAuthDialog()}
        onOpenChange={setShowAuthDialog}
      />

      <Toaster />
    </>
  )
}

const App: Component = () => {
  return (
    <QueryProvider>
      <LensProvider>
        <Web3Provider>
          <CurrencyProvider>
            <I18nProvider>
              <AuthProvider>
                <LanguagePreferenceProvider>
                  <VideoPlaybackProvider>
                    <Router root={AppShell}>
                      <Route path="/" component={FeedPage} />
                      <Route path="/library" component={HomePage} />
                      <Route path="/songs" component={SearchPage} />
                      <Route path="/study" component={StudyPage} />
                      <Route path="/study/session" component={StudySessionPage} />
                      <Route path="/chat" component={ChatPage} />
                      <Route path="/chat/:scenarioId" component={ChatPage} />
                      <Route path="/wallet" component={WalletPage} />
                      {/* User profile page (e.g., /u/scarlett-ks) */}
                      <Route path="/u/:handle" component={UserProfilePage} />
                      {/* Artist page (e.g., /queen, /eminem) */}
                      <Route path="/:artistSlug" component={ArtistPage} />
                      {/* Song detail pages (shows info + Study/Karaoke buttons) */}
                      <Route path="/song/:spotifyTrackId" component={SongDetailPage} />
                      <Route path="/:artistSlug/:songSlug" component={SongDetailPage} />
                      {/* Song study pages (exercise session) */}
                      <Route path="/song/:workId/study" component={StudySessionPage} />
                      <Route path="/:artistSlug/:songSlug/study" component={StudySessionPage} />
                      {/* Song play pages (karaoke player with lyrics) */}
                      <Route path="/song/:spotifyTrackId/play" component={SongPlayPage} />
                      <Route path="/song/:spotifyTrackId/karaoke" component={SongPlayPage} />
                      <Route path="/:artistSlug/:songSlug/play" component={SongPlayPage} />
                      <Route path="/:artistSlug/:songSlug/karaoke" component={SongPlayPage} />
                      <Route path="*" component={FeedPage} />
                    </Router>
                  </VideoPlaybackProvider>
                </LanguagePreferenceProvider>
              </AuthProvider>
            </I18nProvider>
          </CurrencyProvider>
        </Web3Provider>
      </LensProvider>
    </QueryProvider>
  )
}

export default App

// app/src/App.tsx
import { HashRouter, Routes, Route, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { useState, useEffect } from 'react'
import { HomePage } from '@/pages/HomePage'
import { WalletPage } from '@/pages/WalletPage'
import { SearchPage } from '@/pages/SearchPage'
import { AccountPageContainer } from '@/pages/AccountPageContainer'
import { VideoDetailPage } from '@/pages/VideoDetailPage'
import { SongPageContainer } from '@/pages/SongPageContainer'
import { SlugSongPageContainer } from '@/pages/SlugSongPageContainer'
import { ArtistPageContainer } from '@/pages/ArtistPageContainer'
import { MediaPageContainer } from '@/pages/MediaPageContainer'
import { ProfilePageContainer } from '@/pages/ProfilePageContainer'
import { ClassPage } from '@/pages/ClassPage'
import { StudySessionPage } from '@/pages/StudySessionPage'
import { AppLayout } from '@/components/layout/AppLayout'
import { ConnectedAuthDialog } from '@/components/layout/ConnectedAuthDialog'
import { Toaster } from '@/components/ui/sonner'
import { AuthProvider, useAuth } from '@/contexts/AuthContext'
import { LanguagePreferenceProvider } from '@/contexts/LanguagePreferenceContext'
import { VideoPlaybackProvider } from '@/contexts/VideoPlaybackContext'
import { Web3Provider } from '@/providers/Web3Provider'

function AppRouter() {
  const location = useLocation()
  const navigate = useNavigate()
  const [activeTab, setActiveTab] = useState<'home' | 'study' | 'search' | 'wallet' | 'profile' | 'none'>('home')

  const { isPKPReady, pkpAddress, setAuthDialogOpener } = useAuth()
  const [showAuthDialog, setShowAuthDialog] = useState(false)

  // Register the auth dialog opener with AuthContext so any component can trigger it
  useEffect(() => {
    setAuthDialogOpener(() => setShowAuthDialog(true))
  }, [setAuthDialogOpener])

  useEffect(() => {
    const pathToTab: Record<string, 'home' | 'study' | 'search' | 'wallet' | 'profile' | 'none'> = {
      '/': 'home',
      '/search': 'search',
      '/study': 'study',
      '/wallet': 'wallet',
      '/profile': 'profile',
    }

    // Hide tab bar on song pages (slug-based or legacy), user pages, and artist pages
    const pathParts = location.pathname.split('/').filter(Boolean)
    const reservedPaths = ['search', 'study', 'wallet', 'profile', 'u', 'song']

    if (location.pathname.startsWith('/song/') || location.pathname.startsWith('/u/') ||
        // Artist pages: /:artistSlug (single segment, not reserved)
        (pathParts.length === 1 && !reservedPaths.includes(pathParts[0])) ||
        // Slug-based song routes: /:artistSlug/:songSlug
        (pathParts.length >= 2 && !reservedPaths.includes(pathParts[0]))) {
      setActiveTab('none')
    } else {
      const tab = pathToTab[location.pathname] || 'home'
      setActiveTab(tab)
    }
  }, [location.pathname])

  const handleTabChange = (tab: 'home' | 'study' | 'search' | 'wallet' | 'profile') => {
    const routes = {
      home: '/',
      study: '/study',
      search: '/search',
      wallet: '/wallet',
      profile: '/profile'
    }
    navigate(routes[tab])
  }

  // Hide footer on song pages (both slug-based and legacy), video detail pages, and artist pages
  const footerPathParts = location.pathname.split('/').filter(Boolean)
  const footerReservedPaths = ['search', 'study', 'wallet', 'profile', 'u', 'song']

  const hideMobileFooter =
    location.pathname.match(/^\/song\//) ||
    location.pathname.match(/^\/u\/[^/]+\/video\//) ||
    // Artist pages: /:artistSlug (single segment, not reserved)
    (footerPathParts.length === 1 && !footerReservedPaths.includes(footerPathParts[0])) ||
    // Slug-based routes: /:artistSlug/:songSlug
    (footerPathParts.length >= 2 && !footerReservedPaths.includes(footerPathParts[0]))

  return (
    <>
      <AppLayout
        activeTab={activeTab}
        onTabChange={handleTabChange}
        isConnected={isPKPReady}
        walletAddress={pkpAddress || undefined}
        onConnectWallet={() => setShowAuthDialog(true)}
        hideMobileFooter={!!hideMobileFooter}
      >
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/search" element={<SearchPage />} />
          <Route path="/u/:lenshandle" element={<AccountPageContainer />} />
          <Route path="/u/:lenshandle/video/:postId" element={<VideoDetailPage />} />

          {/* Artist page (e.g., /queen, /eminem) */}
          <Route path="/:artistSlug" element={<ArtistPageContainer />} />

          {/* Primary song routes - slug-based (e.g., /eminem/lose-yourself) */}
          <Route path="/:artistSlug/:songSlug" element={<SlugSongPageContainer />} />
          <Route path="/:artistSlug/:songSlug/play" element={<MediaPageContainer />} />
          <Route path="/:artistSlug/:songSlug/karaoke" element={<MediaPageContainer variant="practice" />} />
          <Route path="/:artistSlug/:songSlug/study" element={<StudySessionPage onConnectWallet={() => setShowAuthDialog(true)} />} />

          {/* Legacy song routes - redirect to search (no longer supported) */}
          <Route path="/song/:workId" element={<SongPageContainer />} />
          <Route path="/song/:workId/play" element={<MediaPageContainer />} />
          <Route path="/song/:workId/karaoke" element={<MediaPageContainer variant="practice" />} />
          <Route path="/song/:workId/study" element={<StudySessionPage onConnectWallet={() => setShowAuthDialog(true)} />} />

          <Route path="/study/session" element={<StudySessionPage onConnectWallet={() => setShowAuthDialog(true)} />} />
          <Route path="/study" element={<ClassPage onConnectWallet={() => setShowAuthDialog(true)} />} />

          <Route path="/wallet" element={<WalletPage onConnectWallet={() => setShowAuthDialog(true)} />} />
          <Route path="/profile" element={<ProfilePageContainer onConnectWallet={() => setShowAuthDialog(true)} />} />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </AppLayout>

      <ConnectedAuthDialog
        open={showAuthDialog}
        onOpenChange={setShowAuthDialog}
      />

      <Toaster />
    </>
  )
}

function App() {
  return (
    <Web3Provider>
      <HashRouter>
        <AuthProvider>
          <LanguagePreferenceProvider>
            <VideoPlaybackProvider>
              <AppRouter />
            </VideoPlaybackProvider>
          </LanguagePreferenceProvider>
        </AuthProvider>
      </HashRouter>
    </Web3Provider>
  )
}

export default App
