// reference-app/src/contexts/AuthContext.tsx
/**
 * Unified Authentication Context (Lit WebAuthn + Lens)
 * Orchestrates Lit WebAuthn (wallet) and Lens (social) authentication
 *
 * Auth Flow:
 * 1. User creates account (2 signatures: WebAuthn + PKP mint) OR signs in (1 signature)
 * 2. PKP wallet is initialized with auth context
 * 3. User logs into Lens using PKP as signer
 * 4. User creates Lens account if needed (PKP signs transaction)
 *
 * Benefits:
 * - Zero signatures for Lit Actions (PKP auth context persists)
 * - Native biometric auth (Face ID, Touch ID, Windows Hello)
 * - No wallet extensions needed
 * - Session persistence
 *
 * Refactored Architecture:
 * - Credits managed by CreditsContext (separate concern)
 * - Capabilities computed by useAuthCapabilities hook
 * - Auth flows extracted to auth-services
 */

import { createContext, useContext, useState, useEffect, useMemo, useCallback, type ReactNode } from 'react'
import type { Address, WalletClient } from 'viem'
import type { SessionClient, Account } from '@lens-protocol/client'
import { usePKPWallet, type UsePKPWalletResult } from '@/hooks/usePKPWallet'
import { useLensSession, useLensAccount } from '@/lib/lens/hooks'
import { useAuthCapabilities } from '@/hooks/useAuthCapabilities'
import { CreditsProvider, useCredits } from '@/contexts/CreditsContext'
import {
  getExistingAccounts,
  createLensAccount,
} from '@/lib/lens/auth'
import {
  registerWithPasskeyFlow,
  signInWithPasskeyFlow,
  loginLensStandalone,
} from '@/lib/auth/auth-services'
import type { PKPInfo, PKPAuthContext } from '@/lib/lit-webauthn'
import type { AuthCapabilities } from '@/features/post-flow/types'

/**
 * Authentication State
 */
interface AuthState {
  // Lit WebAuthn (Layer 1: Identity + Wallet)
  pkpInfo: PKPInfo | null
  pkpAddress: Address | null
  pkpWalletClient: WalletClient | null
  pkpAuthContext: PKPAuthContext | null
  authData: any | null
  isPKPReady: boolean

  // Lens (Layer 2: Social Identity)
  lensSession: SessionClient | null
  lensAccount: Account | null
  hasLensAccount: boolean

  // Credits & Capabilities
  credits: number
  capabilities: AuthCapabilities

  // Overall state
  isAuthenticating: boolean
  authError: Error | null
  authStep: 'idle' | 'username' | 'webauthn' | 'session' | 'social' | 'complete'
  authMode: 'register' | 'login' | null
  authStatus: string
  lensSetupStatus: 'pending' | 'complete' | 'failed'
}

/**
 * Authentication Actions
 */
interface AuthActions {
  // WebAuthn (replaces wallet connection)
  registerWithPasskey: (username?: string) => Promise<void>
  signInWithPasskey: () => Promise<void>
  logout: () => void

  // Flow control
  showUsernameInput: () => void
  resetAuthFlow: () => void

  // Lens
  loginLens: () => Promise<void>
  createLensAccountWithUsername: (username: string, metadataUri: string) => Promise<void>
  refreshLensAccount: () => Promise<void>
  ensureLensAccount: () => Promise<boolean>

  // Reset
  reset: () => void
}

type AuthContextType = AuthState & AuthActions

const AuthContext = createContext<AuthContextType | null>(null)

/**
 * Auth Provider Core Component
 * Contains all auth logic, wrapped by CreditsProvider
 */
function AuthProviderCore({ children, pkpWallet }: { children: ReactNode; pkpWallet: UsePKPWalletResult }) {
  // Layer 1: Lit WebAuthn + PKP (passed as prop to avoid duplicate hook call)

  // Layer 2: Lens Protocol
  const { sessionClient, setSessionClient } = useLensSession()
  const { account, setAccount } = useLensAccount()

  // Overall state
  const [isAuthenticating, setIsAuthenticating] = useState(false)
  const [authError, setAuthError] = useState<Error | null>(null)
  const [authStep, setAuthStep] = useState<AuthState['authStep']>('idle')
  const [authMode, setAuthMode] = useState<AuthState['authMode']>(null)
  const [authStatus, setAuthStatus] = useState<string>('')
  const [lensSetupStatus, setLensSetupStatus] = useState<'pending' | 'complete' | 'failed'>('pending')

  /**
   * Auto-restore Lens session if PKP is ready
   */
  useEffect(() => {
    const restoreSession = async () => {
      // If PKP is ready and we have a Lens session, auto-restore account
      if (pkpWallet.isConnected && sessionClient && pkpWallet.address) {
        try {
          const existingAccounts = await getExistingAccounts(pkpWallet.address)

          if (existingAccounts.length > 0 && !account) {
            setAccount(existingAccounts[0].account)
            setAuthStep('complete')
            setLensSetupStatus('complete')
          } else if (existingAccounts.length === 0) {
            setLensSetupStatus('failed')
            // Don't block - user can still use PKP features
          }
        } catch (error) {
          console.error('[Auth] Session restore error (non-critical):', error)
          setLensSetupStatus('failed')
          // Don't block - user can still use PKP features
        }
      }
    }

    restoreSession()
  }, [pkpWallet.isConnected, pkpWallet.address, sessionClient, account])

  /**
   * Show username input screen
   * Called when user clicks "Create Account"
   */
  const showUsernameInput = useCallback(() => {
    setAuthMode('register')
    setAuthStep('username')
    setAuthError(null)
    setAuthStatus('')
    setIsAuthenticating(false)
  }, [])

  /**
   * Reset auth flow
   * Called when user clicks back from username input
   */
  const resetAuthFlow = useCallback(() => {
    setAuthMode(null)
    setAuthStep('idle')
    setAuthError(null)
    setAuthStatus('')
    setIsAuthenticating(false)
  }, [])

  /**
   * Register with passkey (create new account)
   * Uses extracted auth service for cleaner flow
   * @param username - Optional username for passkey and Lens account
   */
  const registerWithPasskey = useCallback(async (username?: string) => {
    setIsAuthenticating(true)
    setAuthError(null)
    setAuthMode('register')
    setAuthStep('webauthn')

    try {
      // Use extracted registration service
      const result = await registerWithPasskeyFlow(username, (status) => {
        setAuthStatus(status)
        // Update step based on status message
        if (status.includes('passkey')) {
          setAuthStep('webauthn')
        } else if (status.includes('session') || status.includes('wallet')) {
          setAuthStep('session')
        } else if (status.includes('social') || status.includes('Lens')) {
          setAuthStep('social')
        }
      })

      // Initialize PKP wallet (for context state)
      pkpWallet.initialize(result.pkpInfo, result.authData)

      // Set Lens state from result
      console.log('[AuthContext] Registration result:', {
        hasSession: !!result.lensSession,
        hasAccount: !!result.lensAccount,
        accountAddress: result.lensAccount?.address,
        setupStatus: result.lensSetupStatus,
      })

      if (result.lensSession) {
        console.log('[AuthContext] Setting session client from registration')
        setSessionClient(result.lensSession)
      }
      if (result.lensAccount) {
        console.log('[AuthContext] Setting account from registration:', result.lensAccount.address)
        setAccount(result.lensAccount)
      }
      setLensSetupStatus(result.lensSetupStatus)

      setAuthStep('complete')
      setAuthMode(null)
    } catch (error) {
      console.error('[Auth] Registration error:', error)
      setAuthError(error as Error)
      setAuthStep('idle')
      setAuthMode(null)
      setAuthStatus('')
      throw error
    } finally {
      setIsAuthenticating(false)
    }
  }, [pkpWallet, setSessionClient, setAccount])

  /**
   * Sign in with passkey (existing account)
   * Uses extracted auth service for cleaner flow
   */
  const signInWithPasskey = useCallback(async () => {
    setIsAuthenticating(true)
    setAuthError(null)
    setAuthMode('login')
    setAuthStep('webauthn')

    try {
      // Use extracted login service
      const result = await signInWithPasskeyFlow((status) => {
        setAuthStatus(status)
        // Update step based on status message
        if (status.includes('authenticate') || status.includes('device') || status.includes('sign in')) {
          setAuthStep('webauthn')
        } else if (status.includes('wallet') || status.includes('Restoring')) {
          setAuthStep('session')
        } else if (status.includes('social') || status.includes('Lens')) {
          setAuthStep('social')
        }
      })

      // Initialize PKP wallet (for context state)
      pkpWallet.initialize(result.pkpInfo, result.authData)

      // Set Lens state from result
      console.log('[AuthContext] Login result:', {
        hasSession: !!result.lensSession,
        hasAccount: !!result.lensAccount,
        accountAddress: result.lensAccount?.address,
        setupStatus: result.lensSetupStatus,
      })

      if (result.lensSession) {
        console.log('[AuthContext] Setting session client from login')
        setSessionClient(result.lensSession)
      }
      if (result.lensAccount) {
        console.log('[AuthContext] Setting account from login:', result.lensAccount.address)
        setAccount(result.lensAccount)
      }
      setLensSetupStatus(result.lensSetupStatus)

      setAuthStep('complete')
      setAuthMode(null)
    } catch (error) {
      console.error('[Auth] Login error:', error)
      setAuthError(error as Error)
      setAuthStep('idle')
      setAuthMode(null)
      setAuthStatus('')
      throw error
    } finally {
      setIsAuthenticating(false)
    }
  }, [pkpWallet, setSessionClient, setAccount])

  /**
   * Login to Lens Protocol
   * Uses PKP as signer (standalone - for just-in-time Lens connection)
   */
  const loginLens = useCallback(async (walletClient?: WalletClient, address?: Address) => {
    const client = walletClient || pkpWallet.walletClient
    const addr = address || pkpWallet.address

    if (!client || !addr) {
      throw new Error('PKP wallet not ready')
    }

    try {
      setIsAuthenticating(true)
      setAuthStep('social')
      setAuthError(null)

      // Use extracted Lens login service
      const result = await loginLensStandalone(client, addr, (status) => {
        setAuthStatus(status)
      })

      setSessionClient(result.session)
      setAccount(result.account)

      // Account is always created (either existing or new without username)
      setAuthStep('complete')
      setAuthStatus('All set!')
      setAuthMode(null)
      setLensSetupStatus('complete')
    } catch (error) {
      console.error('[Auth] Lens login error:', error)
      setAuthError(error as Error)
      setAuthStatus('')
      throw error
    } finally {
      setIsAuthenticating(false)
    }
  }, [pkpWallet.walletClient, pkpWallet.address, setSessionClient, setAccount])

  /**
   * Create Lens account with username
   * Uses PKP to sign transaction
   */
  const createLensAccountWithUsername = useCallback(async (username: string, metadataUri: string) => {
    if (!sessionClient || !pkpWallet.walletClient) {
      throw new Error('Not ready to create account')
    }

    try {
      setIsAuthenticating(true)
      setAuthError(null)

      // Create account (gas sponsored by Lens app)
      const newAccount = await createLensAccount(
        sessionClient,
        pkpWallet.walletClient,
        username,
        metadataUri
      )

      setAccount(newAccount)
    } catch (error) {
      console.error('[Auth] Create Lens account error:', error)
      setAuthError(error as Error)
      throw error
    } finally {
      setIsAuthenticating(false)
    }
  }, [sessionClient, pkpWallet.walletClient, setAccount])

  /**
   * Refresh Lens account
   * Check for newly created accounts
   */
  const refreshLensAccount = useCallback(async () => {
    if (!pkpWallet.address) {
      throw new Error('PKP wallet not connected')
    }

    try {
      setIsAuthenticating(true)
      setAuthError(null)

      const existingAccounts = await getExistingAccounts(pkpWallet.address)

      if (existingAccounts.length > 0) {
        setAccount(existingAccounts[0].account)
        setLensSetupStatus('complete')
      }
    } catch (error) {
      console.error('[Auth] Refresh account error:', error)
      setAuthError(error as Error)
      throw error
    } finally {
      setIsAuthenticating(false)
    }
  }, [pkpWallet.address, setAccount])

  /**
   * Ensure Lens account is set up (just-in-time)
   * Can be called when user attempts social features
   * Returns true (accounts are always auto-created now)
   */
  const ensureLensAccount = useCallback(async (): Promise<boolean> => {
    if (!pkpWallet.isConnected || !pkpWallet.address) {
      throw new Error('PKP wallet not connected')
    }

    // Already have account
    if (account) {
      return true
    }

    try {
      // loginLens now auto-creates account if none exists
      await loginLens()
      return true
    } catch (error) {
      console.error('[Auth] Ensure Lens account error:', error)
      setLensSetupStatus('failed')
      return false
    }
  }, [pkpWallet.isConnected, pkpWallet.address, account, loginLens])

  /**
   * Logout and reset all auth state
   */
  const logout = useCallback(() => {
    pkpWallet.reset()
    setSessionClient(null)
    setAccount(null)
    setAuthStep('idle')
    setAuthMode(null)
    setAuthError(null)
    setAuthStatus('')
  }, [pkpWallet, setSessionClient, setAccount])

  /**
   * Reset (alias for logout)
   */
  const reset = logout

  // Get credits from CreditsContext (injected by wrapper)
  const { credits } = useCredits()

  // Compute capabilities using extracted hook
  const capabilities = useAuthCapabilities({
    isPKPReady: pkpWallet.isConnected,
    pkpAuthContext: pkpWallet.authContext,
    hasLensSession: !!sessionClient,
    hasLensAccount: !!account,
    credits,
  })

  const value: AuthContextType = useMemo(() => {
    // Debug logging
    if (account || sessionClient) {
      console.log('[AuthContext] Value update:', {
        hasAccount: !!account,
        accountAddress: account?.address,
        hasSession: !!sessionClient,
        sessionType: sessionClient?.type,
      })
    }

    return {
      // PKP State
      pkpInfo: pkpWallet.pkpInfo,
      pkpAddress: pkpWallet.address,
      pkpWalletClient: pkpWallet.walletClient,
      pkpAuthContext: pkpWallet.authContext,
      authData: pkpWallet.authData,
      isPKPReady: pkpWallet.isConnected,

      // Lens State
      lensSession: sessionClient,
      lensAccount: account,
      hasLensAccount: !!account,

      // Credits & Capabilities
      credits,
      capabilities,

      // Overall State
      isAuthenticating: isAuthenticating || pkpWallet.isInitializing,
      authError: authError || pkpWallet.error,
      authStep,
      authMode,
      authStatus,
      lensSetupStatus,

      // Actions
      registerWithPasskey,
      signInWithPasskey,
      logout,
      showUsernameInput,
      resetAuthFlow,
      loginLens,
      createLensAccountWithUsername,
      refreshLensAccount,
      ensureLensAccount,
      reset,
    }
  }, [
    pkpWallet.pkpInfo,
    pkpWallet.address,
    pkpWallet.walletClient,
    pkpWallet.authContext,
    pkpWallet.authData,
    pkpWallet.isConnected,
    pkpWallet.isInitializing,
    pkpWallet.error,
    sessionClient,
    account,
    credits,
    capabilities,
    isAuthenticating,
    authError,
    authStep,
    authMode,
    authStatus,
    lensSetupStatus,
    registerWithPasskey,
    signInWithPasskey,
    logout,
    showUsernameInput,
    resetAuthFlow,
    loginLens,
    createLensAccountWithUsername,
    refreshLensAccount,
    ensureLensAccount,
    reset,
  ])

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>
}

/**
 * Main Auth Provider with Credits integration
 * Wraps AuthProviderCore with CreditsProvider
 */
export function AuthProvider({ children }: { children: ReactNode }) {
  const pkpWallet = usePKPWallet()

  return (
    <CreditsProvider pkpAddress={pkpWallet.address} isConnected={pkpWallet.isConnected}>
      <AuthProviderCore pkpWallet={pkpWallet}>{children}</AuthProviderCore>
    </CreditsProvider>
  )
}

/**
 * Hook to access auth context
 */
export function useAuth() {
  const context = useContext(AuthContext)
  if (!context) {
    throw new Error('useAuth must be used within AuthProvider')
  }
  return context
}

// solidjs-app/src/contexts/AuthContext.tsx
/**
 * Auth Context for SolidJS
 * Manages PKP wallet + Lens session state
 */

import {
  createContext,
  useContext,
  createSignal,
  onMount,
  type ParentComponent,
  type Accessor,
} from 'solid-js'
import type { Address, WalletClient } from 'viem'
import type { SessionClient, Account } from '@lens-protocol/client'
import type { PKPInfo, AuthData, PKPAuthContext } from '@/lib/lit'
import { LIT_SESSION_STORAGE_KEY } from '@/lib/lit/constants'

// Auth State
interface AuthState {
  pkpInfo: Accessor<PKPInfo | null>
  pkpAddress: Accessor<Address | null>
  pkpWalletClient: Accessor<WalletClient | null>
  pkpAuthContext: Accessor<PKPAuthContext | null>
  authData: Accessor<AuthData | null>
  isPKPReady: Accessor<boolean>
  isCheckingSession: Accessor<boolean>

  lensSession: Accessor<SessionClient | null>
  lensAccount: Accessor<Account | null>
  hasLensAccount: Accessor<boolean>

  isAuthenticating: Accessor<boolean>
  authError: Accessor<Error | null>
  authStep: Accessor<'idle' | 'username' | 'webauthn' | 'session' | 'social' | 'processing' | 'complete'>
  authMode: Accessor<'register' | 'login' | 'eoa' | null>
  authStatus: Accessor<string>
  lensSetupStatus: Accessor<'pending' | 'complete' | 'failed'>
}

interface AuthActions {
  register: (username?: string) => Promise<void>
  signIn: () => Promise<void>
  loginWithGoogle: (username?: string) => Promise<void>
  loginWithDiscord: (username?: string) => Promise<void>
  retryEoaWithUsername: (username: string) => Promise<void>
  logout: () => void
  showUsernameInput: () => void
  resetAuthFlow: () => void
  openAuthDialog: () => void
  setAuthDialogOpener: (opener: () => void) => void
  expectWalletConnection: () => void
}

type AuthContextType = AuthState & AuthActions

const AuthContext = createContext<AuthContextType>()

// Dynamic loaders for code splitting
type LitModule = typeof import('@/lib/lit')
let litPromise: Promise<LitModule> | null = null

function loadLit(): Promise<LitModule> {
  if (!litPromise) {
    litPromise = import('@/lib/lit')
  }
  return litPromise
}

function hasLikelyValidStoredSession(): boolean {
  if (typeof window === 'undefined') return false

  try {
    const raw = window.localStorage.getItem(LIT_SESSION_STORAGE_KEY)
    if (!raw) return false

    const session = JSON.parse(raw)
    if (!session || typeof session !== 'object') return false
    if (!session.expiresAt || Date.now() >= session.expiresAt) return false
    if (!session.pkpInfo) return false

    return true
  } catch {
    return false
  }
}

export const AuthProvider: ParentComponent = (props) => {
  // PKP Wallet State
  const [walletClient, setWalletClient] = createSignal<WalletClient | null>(null)
  const [authContext, setAuthContext] = createSignal<PKPAuthContext | null>(null)
  const [pkpInfo, setPkpInfo] = createSignal<PKPInfo | null>(null)
  const [authData, setAuthData] = createSignal<AuthData | null>(null)
  const [isInitializing, setIsInitializing] = createSignal(false)
  const [isCheckingSession, setIsCheckingSession] = createSignal(true)

  // Lens State
  const [sessionClient, setSessionClient] = createSignal<SessionClient | null>(null)
  const [account, setAccount] = createSignal<Account | null>(null)

  // Flow state
  const [isAuthenticating, setIsAuthenticating] = createSignal(false)
  const [authError, setAuthError] = createSignal<Error | null>(null)
  const [authStep, setAuthStep] = createSignal<AuthState['authStep']['prototype']>('idle')
  const [authMode, setAuthMode] = createSignal<'register' | 'login' | 'eoa' | null>(null)
  const [authStatus, setAuthStatus] = createSignal('')
  const [lensSetupStatus, setLensSetupStatus] = createSignal<'pending' | 'complete' | 'failed'>('pending')

  // Auth dialog opener ref
  let authDialogOpener: (() => void) | null = null

  // Derived state
  const address = () => walletClient()?.account?.address || null
  const isConnected = () => !!walletClient() && !!authContext()

  // Initialize PKP
  const initializePKP = async (info: PKPInfo, data: AuthData) => {
    setIsInitializing(true)

    try {
      console.log('[Auth] Initializing PKP wallet:', info.ethAddress)
      const lit = await loadLit()

      let context = lit.getCachedAuthContext(info.publicKey)
      if (!context) {
        console.log('[Auth] Creating PKP auth context...')
        context = await lit.createPKPAuthContext(info, data)
      }

      console.log('[Auth] Creating wallet client...')
      const client = await lit.createPKPWalletClient(info, context)

      setAuthContext(context)
      setWalletClient(client)
      setPkpInfo(info)
      setAuthData(data)

      console.log('[Auth] ✓ PKP wallet initialized')
    } catch (err) {
      console.error('[Auth] Initialization failed:', err)
      throw err
    } finally {
      setIsInitializing(false)
    }
  }

  // Auto-initialize from stored session
  onMount(async () => {
    if (walletClient() || isInitializing()) return

    if (!hasLikelyValidStoredSession()) {
      console.log('[Auth] No stored session')
      setIsCheckingSession(false)
      return
    }

    try {
      const { getAuthStatus, clearSession } = await loadLit()
      const status = getAuthStatus()

      if (status.isAuthenticated && status.pkpInfo && status.authData) {
        console.log('[Auth] Auto-initializing from stored session...')
        await initializePKP(status.pkpInfo, status.authData)
      } else {
        clearSession()
      }
    } catch (error) {
      console.error('[Auth] Auto-initialization failed:', error)
    } finally {
      setIsCheckingSession(false)
    }
  })

  // Actions
  const showUsernameInput = () => {
    setAuthMode('register')
    setAuthStep('username')
    setAuthError(null)
    setAuthStatus('')
    setIsAuthenticating(false)
  }

  const resetAuthFlow = () => {
    setAuthMode(null)
    setAuthStep('idle')
    setAuthError(null)
    setAuthStatus('')
    setIsAuthenticating(false)
  }

  const openAuthDialog = () => {
    if (authDialogOpener) {
      authDialogOpener()
    } else {
      console.warn('[Auth] Auth dialog opener not set')
    }
  }

  const setAuthDialogOpener = (opener: () => void) => {
    authDialogOpener = opener
  }

  const expectWalletConnection = () => {
    // For EOA wallet flow
  }

  const register = async (username?: string) => {
    try {
      const { registerWithPasskeyFlow } = await import('@/lib/auth/flows')

      setIsAuthenticating(true)
      setAuthError(null)
      setAuthMode('register')
      setAuthStep('webauthn')

      const result = await registerWithPasskeyFlow(username, (status) => {
        setAuthStatus(status)
        if (status.includes('passkey')) setAuthStep('webauthn')
        else if (status.includes('session')) setAuthStep('session')
        else if (status.includes('Lens')) setAuthStep('social')
      })

      setAuthContext(result.pkpAuthContext)
      setWalletClient(result.walletClient)
      setPkpInfo(result.pkpInfo)
      setAuthData(result.authData)
      setSessionClient(result.lensSession)
      setAccount(result.lensAccount)
      setLensSetupStatus(result.lensSetupStatus)

      setAuthStep('complete')
      setAuthMode(null)
      setAuthStatus('')
    } catch (error) {
      console.error('[Auth] Registration error:', error)
      setAuthError(error as Error)
      setAuthStep('idle')
      setAuthMode(null)
      throw error
    } finally {
      setIsAuthenticating(false)
    }
  }

  const signIn = async () => {
    try {
      const { signInWithPasskeyFlow } = await import('@/lib/auth/flows')

      setIsAuthenticating(true)
      setAuthMode('login')
      setAuthStep('webauthn')
      setAuthError(null)

      const result = await signInWithPasskeyFlow((status) => {
        setAuthStatus(status)
        if (status.includes('authenticate')) setAuthStep('webauthn')
        else if (status.includes('wallet')) setAuthStep('session')
        else if (status.includes('Lens')) setAuthStep('social')
      })

      setAuthContext(result.pkpAuthContext)
      setWalletClient(result.walletClient)
      setPkpInfo(result.pkpInfo)
      setAuthData(result.authData)
      setSessionClient(result.lensSession)
      setAccount(result.lensAccount)
      setLensSetupStatus(result.lensSetupStatus)

      setAuthStep('complete')
      setAuthMode(null)
      setAuthStatus('')
    } catch (error) {
      console.error('[Auth] Login error:', error)
      setAuthError(error as Error)
      setAuthStep('idle')
      setAuthMode(null)
      throw error
    } finally {
      setIsAuthenticating(false)
    }
  }

  const loginWithGoogle = async (_username?: string) => {
    // TODO: Implement Google OAuth flow
    console.log('[Auth] Google login not yet implemented')
  }

  const loginWithDiscord = async (_username?: string) => {
    // TODO: Implement Discord OAuth flow
    console.log('[Auth] Discord login not yet implemented')
  }

  const retryEoaWithUsername = async (_username: string) => {
    // TODO: Implement EOA retry flow
    console.log('[Auth] EOA retry not yet implemented')
  }

  const logout = () => {
    loadLit()
      .then(({ clearSession }) => clearSession())
      .catch((err) => console.error('[Auth] Failed to clear session:', err))

    setWalletClient(null)
    setAuthContext(null)
    setPkpInfo(null)
    setAuthData(null)
    setSessionClient(null)
    setAccount(null)
    setAuthStep('idle')
    setAuthMode(null)
    setAuthError(null)
    setAuthStatus('')
    setLensSetupStatus('pending')
  }

  const value: AuthContextType = {
    // State (all as accessors)
    pkpInfo,
    pkpAddress: address,
    pkpWalletClient: walletClient,
    pkpAuthContext: authContext,
    authData,
    isPKPReady: isConnected,
    isCheckingSession,
    lensSession: sessionClient,
    lensAccount: account,
    hasLensAccount: () => !!account(),
    isAuthenticating: () => isAuthenticating() || isInitializing(),
    authError,
    authStep,
    authMode,
    authStatus,
    lensSetupStatus,

    // Actions
    register,
    signIn,
    loginWithGoogle,
    loginWithDiscord,
    retryEoaWithUsername,
    logout,
    showUsernameInput,
    resetAuthFlow,
    openAuthDialog,
    setAuthDialogOpener,
    expectWalletConnection,
  }

  return <AuthContext.Provider value={value}>{props.children}</AuthContext.Provider>
}

export function useAuth(): AuthContextType {
  const context = useContext(AuthContext)
  if (!context) {
    throw new Error('useAuth must be used within AuthProvider')
  }
  return context
}
