// root/app/src/components/feed/VideoThumbnail.tsx
import { Play } from '@phosphor-icons/react'
import { cn } from '@/lib/utils'

export interface VideoThumbnailProps {
  thumbnailUrl: string
  playCount: number
  onClick?: () => void
  className?: string
}

/**
 * VideoThumbnail - Thumbnail for profile video grid
 * Shows thumbnail image with play count overlay and hover effect
 */
export function VideoThumbnail({
  thumbnailUrl,
  playCount,
  onClick,
  className
}: VideoThumbnailProps) {
  // Format play count with K/M suffixes
  const formatPlayCount = (count: number): string => {
    if (count >= 1000000) {
      return `${(count / 1000000).toFixed(1)}M`
    }
    if (count >= 1000) {
      return `${(count / 1000).toFixed(1)}K`
    }
    return count.toString()
  }

  return (
    <div
      className={cn(
        'relative aspect-[9/16] bg-neutral-900 overflow-hidden cursor-pointer group md:rounded-md',
        className
      )}
      onClick={onClick}
    >
      {/* Thumbnail Image */}
      <img
        src={thumbnailUrl}
        alt="Video thumbnail"
        className="w-full h-full object-cover"
        loading="lazy"
      />

      {/* Play Count Overlay - bottom left */}
      <div className="absolute bottom-2 left-2 flex items-center gap-1 text-white text-base font-semibold">
        <Play weight="fill" className="w-4 h-4" />
        <span>{formatPlayCount(playCount)}</span>
      </div>

      {/* Hover Overlay - desktop only */}
      <div className="hidden md:flex absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity duration-200 items-center justify-center">
        <div className="w-16 h-16 bg-white/20 backdrop-blur-sm rounded-full flex items-center justify-center">
          <Play className="w-8 h-8 text-white ml-1" weight="fill" />
        </div>
      </div>
    </div>
  )
}

// solidjs-app/src/components/ui/video-thumbnail.tsx
/**
 * VideoThumbnail - thumbnail with play indicator overlay
 */

import { Show, type Component } from 'solid-js'
import { cn } from '@/lib/utils'
import { Play } from '../icons'

interface VideoThumbnailProps {
  src?: string
  alt?: string
  aspectRatio?: '16/9' | '9/16' | '1/1' | '4/3'
  showPlayButton?: boolean
  duration?: string
  class?: string
  onClick?: () => void
}

const VideoThumbnail: Component<VideoThumbnailProps> = (props) => {
  const aspectClass = () => {
    switch (props.aspectRatio) {
      case '16/9': return 'aspect-video'
      case '9/16': return 'aspect-[9/16]'
      case '4/3': return 'aspect-[4/3]'
      default: return 'aspect-square'
    }
  }

  return (
    <button
      type="button"
      onClick={props.onClick}
      class={cn(
        'relative w-full overflow-hidden rounded-xl bg-muted cursor-pointer group',
        aspectClass(),
        props.class
      )}
    >
      <Show
        when={props.src}
        fallback={
          <div class="w-full h-full bg-gradient-to-br from-pink-400 to-purple-600" />
        }
      >
        <img
          src={props.src}
          alt={props.alt ?? 'Video thumbnail'}
          class="w-full h-full object-cover transition-transform group-hover:scale-105"
        />
      </Show>

      {/* Play button overlay */}
      <Show when={props.showPlayButton !== false}>
        <div class="absolute inset-0 flex items-center justify-center bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity">
          <div class="w-12 h-12 rounded-full bg-white/90 flex items-center justify-center shadow-lg">
            <Play class="w-5 h-5 text-black ml-0.5" />
          </div>
        </div>
      </Show>

      {/* Duration badge */}
      <Show when={props.duration}>
        <div class="absolute bottom-2 right-2 px-1.5 py-0.5 rounded bg-black/70 text-white text-xs font-medium">
          {props.duration}
        </div>
      </Show>
    </button>
  )
}

export { VideoThumbnail }
