// solidjs-app/src/components/chat/ChatContainer.tsx
/**
 * ChatContainer - Main chat orchestrator
 *
 * Handles:
 * - Scenario list view (personality selection)
 * - Individual chat view
 * - Navigation between them
 * - Message persistence (IDB for default, React state for roleplay)
 * - Translation, TTS, and audio recording
 *
 * Each AI personality has exactly one ongoing conversation (default)
 * plus ephemeral roleplay scenarios.
 */

import {
  Component,
  Show,
  createSignal,
  createMemo,
  createEffect,
  onCleanup,
  splitProps,
} from 'solid-js'
import { createStore } from 'solid-js/store'
import { ChatPage, type ChatItem } from './ChatPage'
import { ScenarioPicker, type PersonalityGroup, type ScenarioItem } from './ScenarioPicker'
import {
  useChatContext,
  getThread,
  getOrCreateConversation,
  addMessage as addStoredMessage,
  addMessagesBatch,
  markThreadRead,
  translateText,
  synthesizeSpeech,
  getWelcomeMessageKey,
  createAudioPlayback,
  buildHighlightedContent,
  type Message,
  type PersonalityId,
  type UserContext,
  type TTSWord,
  AI_PERSONALITIES,
} from '@/lib/chat'
import type { PKPAuthContext } from '@/lib/lit/types'
import { createAudioRecorder } from '@/hooks/useAudioRecorder'
import { useUnlockSubscription } from '@/hooks/useUnlockSubscription'
import { useTranslation } from '@/lib/i18n'
import { PremiumUpgradeDialog } from '@/components/purchase/PremiumUpgradeDialog'
import { PREMIUM_AI_LOCK } from '@/lib/contracts/addresses'

// ============================================================
// Scenario Definitions
// ============================================================

interface ScenarioDef {
  id: string
  titleKey: string
  descriptionKey: string
  image: string
  isAdult?: boolean
  /** Roleplays are ephemeral (signal state only), default chats persist to IDB */
  isRoleplay?: boolean
}

const SCARLETT_SCENARIO_DEFS: ScenarioDef[] = [
  {
    id: 'scarlett-chat',
    titleKey: 'Default Chat',
    descriptionKey: 'Learn English through music and casual conversation',
    image: '/images/scarlett/default.webp',
    isRoleplay: false,
  },
  {
    id: 'scarlett-surfing',
    titleKey: 'Beach Day',
    descriptionKey: 'Join Scarlett for a day at the beach! Practice casual conversation while learning to surf.',
    image: '/images/scarlett/beach.webp',
    isRoleplay: true,
  },
  {
    id: 'scarlett-cafe',
    titleKey: 'Coffee Shop',
    descriptionKey: 'Meet Scarlett at a cozy café. Practice ordering and small talk.',
    image: '/images/scarlett/cafe.webp',
    isRoleplay: true,
  },
]

const VIOLET_SCENARIO_DEFS: ScenarioDef[] = [
  {
    id: 'violet-chat',
    titleKey: 'Default Chat',
    descriptionKey: 'Chat about anime, gaming, and Japanese culture',
    image: '/images/violet/default.webp',
    isRoleplay: false,
  },
  {
    id: 'violet-nightclub',
    titleKey: 'Late Night',
    descriptionKey: 'A more mature conversation setting for adult learners.',
    image: '/images/violet/nightclub.webp',
    isAdult: true,
    isRoleplay: true,
  },
  {
    id: 'violet-ramen',
    titleKey: 'Ramen Shop',
    descriptionKey: 'Visit a cozy ramen shop with Violet. Learn food vocabulary!',
    image: '/images/violet/ramen.webp',
    isRoleplay: true,
  },
]

const ALL_SCENARIOS: ScenarioDef[] = [...SCARLETT_SCENARIO_DEFS, ...VIOLET_SCENARIO_DEFS]

/** Get scenario definition by ID */
function getScenarioDef(scenarioId: string | null): ScenarioDef | undefined {
  if (!scenarioId) return undefined
  return ALL_SCENARIOS.find((s) => s.id === scenarioId)
}

/** Extract personality ID from scenario ID (e.g., "scarlett-surfing" -> "scarlett") */
function getPersonalityIdFromScenario(scenarioId: string | null): string | null {
  if (!scenarioId) return null
  return scenarioId.split('-')[0]
}

// ============================================================
// Audio Data Types
// ============================================================

interface MessageAudioData {
  audio: string // base64 MP3
  words: TTSWord[]
}

// ============================================================
// Component Props
// ============================================================

export interface ChatContainerProps {
  /** Called when LLM response is needed (text or audio) */
  onSendMessage?: (
    message: string,
    context: {
      personalityId: string
      messages: Array<{ role: 'user' | 'assistant'; content: string }>
      audioBase64?: string
      userContext?: UserContext | null
      scenarioId?: string
    }
  ) => Promise<{ reply: string; transcript?: string }>
  class?: string
  /** Whether user is authenticated */
  isAuthenticated?: boolean
  /** PKP auth context for translations */
  authContext?: PKPAuthContext | null
  /** Called when auth is required */
  onAuthRequired?: () => void
  /** Called when conversation view changes */
  onConversationChange?: (inConversation: boolean) => void
  /** Initial scenario ID from URL */
  initialScenarioId?: string
  /** Called when a scenario is selected (for URL navigation) */
  onScenarioSelect?: (scenarioId: string) => void
  /** Called when user wants to go back to scenario list */
  onBackToList?: () => void
}

// ============================================================
// Main Component
// ============================================================

export const ChatContainer: Component<ChatContainerProps> = (props) => {
  const { t } = useTranslation()
  const [local] = splitProps(props, [
    'onSendMessage',
    'class',
    'isAuthenticated',
    'authContext',
    'onAuthRequired',
    'onConversationChange',
    'initialScenarioId',
    'onScenarioSelect',
    'onBackToList',
  ])

  // ============================================================
  // Core State
  // ============================================================

  const [currentScenarioId, setCurrentScenarioId] = createSignal<string | null>(
    local.initialScenarioId || null
  )
  const [isTyping, setIsTyping] = createSignal(false)
  const [recordingDuration, setRecordingDuration] = createSignal(0)
  const [isProcessingAudio, setIsProcessingAudio] = createSignal(false)
  const [isRecording, setIsRecording] = createSignal(false)

  // Persisted messages (from IDB)
  const [persistedMessages, setPersistedMessages] = createSignal<Message[]>([])

  // Roleplay messages (ephemeral, signal state only)
  const [roleplayMessages, setRoleplayMessages] = createSignal<Message[]>([])

  // Survey state
  const [isProcessingSurvey, setIsProcessingSurvey] = createSignal(false)

  // Translation state
  const [translations, setTranslations] = createStore<Record<string, string>>({})
  const [translatingIds, setTranslatingIds] = createSignal<Set<string>>(new Set())

  // Audio/TTS state
  const [audioDataMap, setAudioDataMap] = createStore<Record<string, MessageAudioData>>({})
  const [playingMessageId, setPlayingMessageId] = createSignal<string | null>(null)
  const [loadingTtsIds, setLoadingTtsIds] = createSignal<Set<string>>(new Set())
  const [currentWordIndex, setCurrentWordIndex] = createSignal(-1)

  // Audio playback instance
  let audioPlayback: ReturnType<typeof createAudioPlayback> | null = null

  // Recording timer
  let recordingTimerRef: ReturnType<typeof setInterval> | null = null

  // Audio recorder instance
  const audioRecorder = createAudioRecorder()

  // Premium upgrade dialog state
  const [upgradeDialogOpen, setUpgradeDialogOpen] = createSignal(false)

  // Premium AI subscription hook (0.001 ETH / 30 days on Base Sepolia)
  const premiumLock = PREMIUM_AI_LOCK.testnet
  const unlockSubscription = useUnlockSubscription({
    lockAddress:
      premiumLock.lockAddress !== '0x0000000000000000000000000000000000000000'
        ? premiumLock.lockAddress
        : undefined,
  })

  // ============================================================
  // Derived State
  // ============================================================

  const currentScenarioDef = createMemo(() => getScenarioDef(currentScenarioId()))
  const currentPersonalityId = createMemo(() => getPersonalityIdFromScenario(currentScenarioId()))
  const isRoleplay = createMemo(() => currentScenarioDef()?.isRoleplay ?? false)

  const currentPersonality = createMemo(() => {
    const id = currentPersonalityId()
    if (!id) return null
    return AI_PERSONALITIES.find((p) => p.id === id) || null
  })

  // Use chat context for surveys and user profile
  const chatContext = useChatContext()

  // Unified messages (from either IDB or signal state based on mode)
  const messages = createMemo(() => (isRoleplay() ? roleplayMessages() : persistedMessages()))

  // Use context's survey state - it's already computed based on current personality
  // Note: chatContext.setCurrentScenarioId syncs with our local state
  createEffect(() => {
    chatContext.setCurrentScenarioId(currentScenarioId())
  })

  // Determine if input should be disabled
  const isNewConversation = createMemo(() => messages().length === 0)
  const inputDisabled = createMemo(() => {
    if (isRoleplay()) {
      // For roleplays: could check token limit here
      return false
    }
    // For default chats: disable input until surveys complete
    return isNewConversation() && !chatContext.surveysComplete()
  })

  // ============================================================
  // Scenario Groups for Picker
  // ============================================================

  const scenarioGroups = createMemo<PersonalityGroup[]>(() => [
    {
      id: 'scarlett',
      name: 'Scarlett',
      scenarios: SCARLETT_SCENARIO_DEFS.map((def) => ({
        id: def.id,
        title: def.titleKey,
        description: def.descriptionKey,
        image: def.image,
        isAdult: def.isAdult,
      })),
    },
    {
      id: 'violet',
      name: 'Violet',
      scenarios: VIOLET_SCENARIO_DEFS.map((def) => ({
        id: def.id,
        title: def.titleKey,
        description: def.descriptionKey,
        image: def.image,
        isAdult: def.isAdult,
      })),
    },
  ])

  // ============================================================
  // Effects
  // ============================================================

  // Sync state with URL when initialScenarioId changes
  createEffect(() => {
    const urlScenario = local.initialScenarioId
    if (urlScenario !== currentScenarioId()) {
      setCurrentScenarioId(urlScenario || null)
      setIsProcessingSurvey(false)
    }
  })

  // Notify parent when conversation view changes
  createEffect(() => {
    local.onConversationChange?.(currentPersonalityId() !== null)
  })

  // Load messages when scenario changes
  createEffect(async () => {
    const scenarioId = currentScenarioId()
    const roleplay = isRoleplay()

    if (!scenarioId) {
      setPersistedMessages([])
      setRoleplayMessages([])
      return
    }

    if (roleplay) {
      // Clear persisted, roleplay will be empty at start
      setPersistedMessages([])
      setRoleplayMessages([])

      // Add intro message for roleplay
      const scenarioDef = currentScenarioDef()
      const personality = currentPersonality()
      if (scenarioDef && personality) {
        const introMessage: Message = {
          id: `intro-${Date.now()}`,
          threadId: scenarioId,
          idx: 0,
          role: 'assistant',
          content: `*${scenarioDef.descriptionKey}*\n\nHey! ${personality.name === 'Scarlett' ? '✨' : '🎧'}`,
          createdAt: Date.now(),
        }
        setRoleplayMessages([introMessage])
      }
    } else {
      // Load from IDB
      setRoleplayMessages([])
      const thread = await getThread(scenarioId)
      if (thread) {
        // Thread exists, load messages
        const { getMessages } = await import('@/lib/chat/store')
        const msgs = await getMessages(thread.id)
        setPersistedMessages(msgs)
      } else {
        setPersistedMessages([])
      }
    }
  })

  // Recording duration timer
  createEffect(() => {
    if (isRecording()) {
      setRecordingDuration(0)
      recordingTimerRef = setInterval(() => {
        setRecordingDuration((d) => d + 1)
      }, 1000)
    } else {
      if (recordingTimerRef) {
        clearInterval(recordingTimerRef)
        recordingTimerRef = null
      }
    }
  })

  onCleanup(() => {
    if (recordingTimerRef) {
      clearInterval(recordingTimerRef)
    }
    if (audioPlayback) {
      audioPlayback.stop()
    }
  })

  // ============================================================
  // Message Handlers
  // ============================================================

  const addMessage = async (role: 'user' | 'assistant', content: string, metadata?: Record<string, unknown>) => {
    const scenarioId = currentScenarioId()
    if (!scenarioId) return

    const newMessage: Message = {
      id: `msg-${Date.now()}-${Math.random().toString(36).slice(2)}`,
      threadId: scenarioId,
      idx: messages().length,
      role,
      content,
      metadata,
      createdAt: Date.now(),
    }

    if (isRoleplay()) {
      setRoleplayMessages((prev) => [...prev, newMessage])
    } else {
      // Persist to IDB
      await addStoredMessage(scenarioId, role, content, metadata)
      setPersistedMessages((prev) => [...prev, newMessage])
    }
  }

  // ============================================================
  // Send Message
  // ============================================================

  const handleSend = async (content: string) => {
    const scenarioId = currentScenarioId()
    const personalityId = currentPersonalityId()
    const personality = currentPersonality()

    if (!scenarioId || !personalityId || !personality) return

    // Check authentication
    if (!local.isAuthenticated) {
      local.onAuthRequired?.()
      return
    }

    // Only persist for default chats
    if (!isRoleplay()) {
      await getOrCreateConversation(scenarioId, personality.name, personality.avatarUrl)
    }

    // Add user message
    await addMessage('user', content)

    // Get LLM response
    if (local.onSendMessage) {
      setIsTyping(true)
      try {
        const recentMessages = messages()
          .slice(-20)
          .map((m) => ({
            role: m.role as 'user' | 'assistant',
            content: m.content,
          }))
        recentMessages.push({ role: 'user', content })

        const { reply } = await local.onSendMessage(content, {
          personalityId,
          messages: recentMessages,
          userContext: chatContext.userContext(),
          scenarioId,
        })

        await addMessage('assistant', reply)
      } catch (error) {
        console.error('Failed to get LLM response:', error)
        await addMessage('assistant', "Sorry, I'm having trouble responding right now. Please try again.")
      } finally {
        setIsTyping(false)
      }
    }
  }

  // ============================================================
  // Audio Recording Handlers
  // ============================================================

  const handleStartRecording = async () => {
    // Check authentication
    if (!local.isAuthenticated) {
      local.onAuthRequired?.()
      return
    }

    try {
      setIsRecording(true)
      await audioRecorder.startRecording()
    } catch (error) {
      console.error('[ChatContainer] Failed to start recording:', error)
      setIsRecording(false)
    }
  }

  const handleStopRecording = async () => {
    setIsRecording(false)
    setIsProcessingAudio(true)

    try {
      const result = await audioRecorder.stopRecording()
      if (!result) {
        throw new Error('No audio recorded')
      }

      const scenarioId = currentScenarioId()
      const personalityId = currentPersonalityId()
      const personality = currentPersonality()

      if (!scenarioId || !personalityId || !personality) {
        throw new Error('No active conversation')
      }

      // Only persist for default chats
      if (!isRoleplay()) {
        await getOrCreateConversation(scenarioId, personality.name, personality.avatarUrl)
      }

      // Get LLM response with audio
      if (local.onSendMessage) {
        setIsTyping(true)
        try {
          const recentMessages = messages()
            .slice(-20)
            .map((m) => ({
              role: m.role as 'user' | 'assistant',
              content: m.content,
            }))

          const { reply, transcript } = await local.onSendMessage('', {
            personalityId,
            messages: recentMessages,
            audioBase64: result.base64,
            userContext: chatContext.userContext(),
            scenarioId,
          })

          // Add user message with transcript if available
          if (transcript) {
            await addMessage('user', transcript)
          }

          // Add AI response
          await addMessage('assistant', reply)
        } catch (error) {
          console.error('Failed to get LLM response:', error)
          await addMessage('assistant', "Sorry, I couldn't understand your voice message. Please try again.")
        } finally {
          setIsTyping(false)
        }
      }
    } catch (error) {
      console.error('[ChatContainer] Recording error:', error)
    } finally {
      setIsProcessingAudio(false)
    }
  }

  // ============================================================
  // Survey Handler
  // ============================================================

  const handleSurveySelect = async (opt: { id: string; label: string; labelKey?: string }) => {
    if (isProcessingSurvey() || isRoleplay()) return

    const survey = chatContext.nextSurvey()
    const personality = currentPersonality()
    const scenarioId = currentScenarioId()

    if (!survey || !personality || !scenarioId) return

    setIsProcessingSurvey(true)

    // Use the already-translated label for display
    const optionText = opt.label

    try {
      const thread = await getOrCreateConversation(scenarioId, personality.name, personality.avatarUrl)

      // Build batch of messages to save
      const messagesToSave: Array<{
        role: 'user' | 'assistant'
        content: string
        metadata?: Record<string, unknown>
      }> = []

      // If brand new thread, include welcome intro
      if (thread.messageCount === 0) {
        const welcomeKey = getWelcomeMessageKey(personality.id as PersonalityId)
        messagesToSave.push({
          role: 'assistant',
          content: t(welcomeKey),
          metadata: { isWelcome: true },
        })
      }

      // Add question
      messagesToSave.push({
        role: 'assistant',
        content: t(survey.questionKey),
        metadata: { isSurvey: true, surveyId: survey.id },
      })

      // Add answer
      messagesToSave.push({
        role: 'user',
        content: optionText,
        metadata: { isSurvey: true, surveyId: survey.id, optionId: opt.id },
      })

      // Save messages
      await addMessagesBatch(scenarioId, messagesToSave)

      // Update user profile via context
      await chatContext.saveSurveyResponse(survey.id, opt.id, optionText)

      // Refresh messages from IDB
      const thread2 = await getThread(scenarioId)
      if (thread2) {
        const { getMessages } = await import('@/lib/chat/store')
        const msgs = await getMessages(thread2.id)
        setPersistedMessages(msgs)
      }
    } finally {
      setIsProcessingSurvey(false)
    }
  }

  // ============================================================
  // Translation Handler
  // ============================================================

  const handleTranslate = async (messageId: string, text: string) => {
    if (!local.authContext) {
      local.onAuthRequired?.()
      return
    }

    if (translatingIds().has(messageId) || translations[messageId]) {
      return
    }

    setTranslatingIds((prev) => new Set(prev).add(messageId))

    try {
      const response = await translateText(
        {
          text,
          targetLanguage: 'zh', // Default to Chinese
        },
        local.authContext!
      )

      if (response.success && response.translation) {
        setTranslations(messageId, response.translation)
      }
    } catch (error) {
      console.error('Translation error:', error)
    } finally {
      setTranslatingIds((prev) => {
        const next = new Set(prev)
        next.delete(messageId)
        return next
      })
    }
  }

  // ============================================================
  // Audio Handlers
  // ============================================================

  const handlePlayAudio = async (messageId: string, text: string) => {
    if (!local.authContext) {
      local.onAuthRequired?.()
      return
    }

    // Check if we already have audio data
    if (audioDataMap[messageId]) {
      playAudioData(messageId, audioDataMap[messageId])
      return
    }

    // Mark as loading
    setLoadingTtsIds((prev) => new Set(prev).add(messageId))

    try {
      const response = await synthesizeSpeech(
        { text },
        local.authContext!
      )

      if (response.success && response.audio) {
        const audioData: MessageAudioData = {
          audio: response.audio,
          words: response.words || [],
        }
        setAudioDataMap(messageId, audioData)
        playAudioData(messageId, audioData)
      }
    } catch (error) {
      console.error('TTS error:', error)
    } finally {
      setLoadingTtsIds((prev) => {
        const next = new Set(prev)
        next.delete(messageId)
        return next
      })
    }
  }

  const playAudioData = (messageId: string, data: MessageAudioData) => {
    // Stop any existing playback
    if (audioPlayback) {
      audioPlayback.stop()
    }

    setPlayingMessageId(messageId)
    setCurrentWordIndex(-1)

    // Create playback instance with onEnd callback
    audioPlayback = createAudioPlayback({
      onEnd: () => {
        setPlayingMessageId(null)
        setCurrentWordIndex(-1)
      },
    })

    // Track word index during playback
    createEffect(() => {
      if (audioPlayback && playingMessageId() === messageId) {
        setCurrentWordIndex(audioPlayback.currentWordIndex())
      }
    })

    // Start playback
    audioPlayback.play(data.audio, data.words)
  }

  const handleStopAudio = () => {
    if (audioPlayback) {
      audioPlayback.stop()
    }
    setPlayingMessageId(null)
    setCurrentWordIndex(-1)
  }

  // ============================================================
  // Navigation Handlers
  // ============================================================

  const handleScenarioSelect = async (scenario: ScenarioItem) => {
    const personalityId = scenario.id.split('-')[0]
    const personality = AI_PERSONALITIES.find((p) => p.id === personalityId)

    if (!personality) return

    // Only persist for default chats
    if (!scenario.isRoleplay) {
      await getOrCreateConversation(scenario.id, personality.name, personality.avatarUrl)
      await markThreadRead(scenario.id)
    }

    // Navigate
    if (local.onScenarioSelect) {
      local.onScenarioSelect(scenario.id)
    } else {
      setCurrentScenarioId(scenario.id)
    }
  }

  const goBack = () => {
    if (local.onBackToList) {
      local.onBackToList()
    } else {
      setCurrentScenarioId(null)
      setIsProcessingSurvey(false)
    }

    // Clear roleplay messages
    if (isRoleplay()) {
      setRoleplayMessages([])
    }
  }

  // ============================================================
  // Build Chat Items
  // ============================================================

  const chatItems = createMemo<ChatItem[]>(() => {
    const personality = currentPersonality()
    const personalityId = currentPersonalityId()
    const scenarioId = currentScenarioId()
    const msgs = messages()
    const survey = chatContext.nextSurvey()
    const complete = chatContext.surveysComplete()
    const roleplay = isRoleplay()

    if (!personality || !personalityId || !scenarioId) return []

    const items: ChatItem[] = []
    const MAX_TOKENS = 64000
    let cumulativeTokens = 500 // System prompt

    // For brand new default chats, show welcome message
    if (msgs.length === 0 && !roleplay) {
      const welcomeKey = getWelcomeMessageKey(personalityId as PersonalityId)
      const welcomeText = t(welcomeKey)
      cumulativeTokens += Math.ceil(welcomeText.length / 4)

      items.push({
        type: 'message',
        id: 'welcome',
        props: {
          content: welcomeText,
          sender: 'ai',
          showTranslate: true,
          translation: translations['welcome'],
          isTranslating: translatingIds().has('welcome'),
          onTranslate: () => handleTranslate('welcome', welcomeText),
          tokensUsed: cumulativeTokens,
          maxTokens: MAX_TOKENS,
        },
      })
    }

    // Add conversation messages
    for (let i = 0; i < msgs.length; i++) {
      const m = msgs[i]
      const isAssistant = m.role === 'assistant'
      const audio = audioDataMap[m.id]
      const isThisPlaying = playingMessageId() === m.id
      const isLoadingTts = loadingTtsIds().has(m.id)

      cumulativeTokens += Math.ceil(m.content.length / 4)

      // Use stable key for welcome message
      const itemKey = i === 0 && m.metadata?.isWelcome ? 'welcome' : m.id

      // Build content with word highlighting (preserves emojis)
      let content: string | Array<{ text: string; isHighlighted: boolean }>
      if (isThisPlaying && audio?.words) {
        content = buildHighlightedContent(m.content, audio.words, currentWordIndex())
      } else {
        content = m.content
      }

      items.push({
        type: 'message',
        id: itemKey,
        props: {
          content,
          sender: m.role === 'user' ? 'user' : 'ai',
          showTranslate: isAssistant,
          translation: translations[m.id],
          isTranslating: translatingIds().has(m.id),
          onTranslate: isAssistant ? () => handleTranslate(m.id, m.content) : undefined,
          hasAudio: isAssistant,
          isPlayingAudio: isThisPlaying,
          isLoadingAudio: isLoadingTts,
          onPlayAudio: isAssistant ? () => handlePlayAudio(m.id, m.content) : undefined,
          onStopAudio: handleStopAudio,
          tokensUsed: isAssistant ? cumulativeTokens : undefined,
          maxTokens: isAssistant ? MAX_TOKENS : undefined,
        },
      })
    }

    // Show next survey (only for default chats)
    if (personalityId && survey && !complete && !roleplay) {
      const translatedOptions = survey.options.map((opt) => ({
        id: opt.id,
        label: t(opt.labelKey),
        labelKey: opt.labelKey,
      }))

      items.push({
        type: 'survey',
        id: `survey-${survey.id}`,
        props: {
          question: t(survey.questionKey),
          options: translatedOptions,
          onSelect: handleSurveySelect,
          disabled: isProcessingSurvey(),
        },
      })
    }

    return items
  })

  // ============================================================
  // Premium Upgrade Handlers
  // ============================================================

  const handleUpgradeClick = () => {
    // Check authentication first
    if (!local.isAuthenticated) {
      local.onAuthRequired?.()
      return
    }

    // Check if lock is deployed
    if (premiumLock.lockAddress === '0x0000000000000000000000000000000000000000') {
      console.warn('[ChatContainer] Premium AI lock not deployed yet')
      return
    }

    setUpgradeDialogOpen(true)
  }

  const handleUpgrade = async () => {
    await unlockSubscription.subscribe()
  }

  const handleUpgradeRetry = () => {
    unlockSubscription.reset()
  }

  // Close dialog on success after a short delay
  createEffect(() => {
    if (unlockSubscription.status() === 'complete') {
      setTimeout(() => {
        setUpgradeDialogOpen(false)
        unlockSubscription.reset()
      }, 2000)
    }
  })

  // ============================================================
  // Render
  // ============================================================

  // Don't show upgrade button if user already has a valid subscription
  const showUpgradeButton = createMemo(() => {
    return !unlockSubscription.hasValidKey()
  })

  return (
    <>
      <Show
        when={currentPersonalityId() && currentPersonality()}
        fallback={
          <ScenarioPicker
            groups={scenarioGroups()}
            onSelect={handleScenarioSelect}
            class={local.class}
          />
        }
      >
        <ChatPage
          items={chatItems()}
          title={currentPersonality()!.name}
          aiAvatarUrl={currentPersonality()!.avatarUrl}
          onBack={goBack}
          isTyping={isTyping()}
          showUpgrade={showUpgradeButton()}
          onUpgrade={handleUpgradeClick}
          inputProps={{
            onSend: handleSend,
            onStartRecording: handleStartRecording,
            onStopRecording: handleStopRecording,
            isRecording: isRecording(),
            recordingDuration: recordingDuration(),
            isProcessing: isProcessingAudio(),
            placeholder: inputDisabled()
              ? isRoleplay()
                ? 'Roleplay ended - go back to start a new one'
                : 'Complete the survey above...'
              : 'Type a message...',
            disabled: inputDisabled(),
          }}
          class={local.class}
        />
      </Show>

      {/* Premium Upgrade Dialog */}
      <PremiumUpgradeDialog
        open={upgradeDialogOpen()}
        onOpenChange={setUpgradeDialogOpen}
        currentStep={unlockSubscription.status()}
        statusMessage={unlockSubscription.statusMessage()}
        errorMessage={unlockSubscription.errorMessage()}
        priceEth={0.001}
        onUpgrade={handleUpgrade}
        onRetry={handleUpgradeRetry}
      />
    </>
  )
}

export default ChatContainer

// app/src/components/chat/ChatContainer.tsx
/**
 * ChatContainer - Main chat view with storage integration
 *
 * Handles:
 * - Personality list view (who to chat with)
 * - Individual chat view
 * - Navigation between them
 * - Message persistence
 *
 * Each AI personality has exactly one ongoing conversation.
 */

import { useState, useEffect, useMemo, useCallback, useRef } from 'react'
import { useTranslation } from 'react-i18next'
import { ChatListPage } from './ChatListPage'
import { ChatPage, type ChatItem } from './ChatPage'
import { PremiumUpgradeDialog } from '@/components/premium/PremiumUpgradeDialog'
import { useAIPersonalities } from '@/lib/chat/useAIPersonalities'
import { useUnlockSubscription } from '@/hooks/useUnlockSubscription'
import { PREMIUM_AI_LOCK } from '@/lib/contracts/addresses'
import { useThread } from '@/lib/chat/hooks'
import { useAudioRecorder } from '@/hooks/useAudioRecorder'
import { translateText, synthesizeSpeech, type TTSWord } from '@/lib/chat/service'
import { useAudioWithHighlight } from '@/lib/chat/useAudioWithHighlight'
import { useChatContext } from '@/lib/chat/useChatContext'
import { getWelcomeMessage, getSurveyFollowUp, PERSONALITY_SURVEYS } from '@/lib/chat/surveys'
import * as store from '@/lib/chat/store'
import type { ChatConversation } from './ChatList'
import type { Thread, PersonalityId, UserContext } from '@/lib/chat/types'
import type { SurveyOption } from './ChatSurveyMessage'
import type { PKPAuthContext } from '@/lib/lit/types'

/** Audio data stored per message */
interface MessageAudioData {
  audio: string  // base64 MP3
  words: TTSWord[]
}

export interface ChatContainerProps {
  /** Called when LLM response is needed (text or audio) */
  onSendMessage?: (
    message: string,
    context: {
      personalityId: string
      messages: Array<{ role: 'user' | 'assistant'; content: string }>
      /** Base64 audio for STT (if provided, message will be empty) */
      audioBase64?: string
      /** User context for personalization */
      userContext?: UserContext | null
    }
  ) => Promise<{ reply: string; transcript?: string }>
  className?: string
  /** Whether user is authenticated */
  isAuthenticated?: boolean
  /** PKP auth context for translations */
  authContext?: PKPAuthContext | null
  /** Called when auth is required */
  onAuthRequired?: () => void
  /** Called when conversation view changes (true = in conversation, false = in list) */
  onConversationChange?: (inConversation: boolean) => void
}

/**
 * ChatContainer - Manages chat state and navigation
 */
export function ChatContainer({
  onSendMessage,
  className,
  isAuthenticated = false,
  authContext,
  onAuthRequired,
  onConversationChange,
}: ChatContainerProps) {
  const { i18n } = useTranslation()
  const [currentPersonalityId, setCurrentPersonalityId] = useState<string | null>(null)
  const [threads, setThreads] = useState<Map<string, Thread>>(new Map())
  const [isTyping, setIsTyping] = useState(false)
  const [recordingDuration, setRecordingDuration] = useState(0)
  const [isProcessingAudio, setIsProcessingAudio] = useState(false)
  const recordingTimerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  // Premium upgrade dialog state
  const [upgradeDialogOpen, setUpgradeDialogOpen] = useState(false)

  // Premium AI subscription hook
  // Use testnet lock address (TODO: switch based on environment)
  const premiumLock = PREMIUM_AI_LOCK.testnet
  const userAddress = authContext?.pkpAddress as `0x${string}` | undefined

  const {
    subscribe: purchasePremium,
    status: upgradeStatus,
    statusMessage: upgradeStatusMessage,
    errorMessage: upgradeErrorMessage,
    reset: resetUpgrade,
  } = useUnlockSubscription(
    userAddress,
    premiumLock.lockAddress !== '0x0000000000000000000000000000000000000000'
      ? premiumLock.lockAddress
      : undefined,
    {
      walletClient: authContext?.walletClient ?? null,
    }
  )

  // Track all answered surveys for sequential display
  const [surveyAnswers, setSurveyAnswers] = useState<Array<{
    surveyId: string
    option: SurveyOption
  }>>([])

  // Track if user just answered (to show next survey after a brief moment)
  const [justAnswered, setJustAnswered] = useState(false)

  // Translation state: messageId -> translation text
  const [translations, setTranslations] = useState<Map<string, string>>(new Map())
  // Track which messages are currently being translated
  const [translatingIds, setTranslatingIds] = useState<Set<string>>(new Set())

  // Audio/TTS state: messageId -> { audio, words }
  const [audioDataMap, setAudioDataMap] = useState<Map<string, MessageAudioData>>(new Map())
  // Track which message is currently playing audio
  const [playingMessageId, setPlayingMessageId] = useState<string | null>(null)
  // Track which messages are loading TTS
  const [loadingTtsIds, setLoadingTtsIds] = useState<Set<string>>(new Set())

  // Audio playback with word highlighting
  const {
    play: playAudio,
    stop: stopAudio,
    isPlaying,
    currentWordIndex,
  } = useAudioWithHighlight({
    onEnd: () => setPlayingMessageId(null),
  })

  // Audio recording
  const {
    isRecording,
    startRecording,
    stopRecording,
    error: recordingError,
  } = useAudioRecorder()

  // Fetch AI personalities with real avatars from Lens
  const { personalities } = useAIPersonalities()

  // Recording duration timer
  useEffect(() => {
    if (isRecording) {
      setRecordingDuration(0)
      recordingTimerRef.current = setInterval(() => {
        setRecordingDuration((d) => d + 1)
      }, 1000)
    } else {
      if (recordingTimerRef.current) {
        clearInterval(recordingTimerRef.current)
        recordingTimerRef.current = null
      }
    }
    return () => {
      if (recordingTimerRef.current) {
        clearInterval(recordingTimerRef.current)
      }
    }
  }, [isRecording])

  // Log recording errors
  useEffect(() => {
    if (recordingError) {
      console.error('[ChatContainer] Recording error:', recordingError)
    }
  }, [recordingError])

  const {
    thread: currentThread,
    messages,
    addMessage,
    refresh: refreshThread,
  } = useThread(currentPersonalityId)

  // Load existing threads for all personalities
  useEffect(() => {
    async function loadThreads() {
      const allThreads = await store.getThreads()
      const threadMap = new Map<string, Thread>()
      for (const t of allThreads) {
        threadMap.set(t.tutorId, t)
      }
      setThreads(threadMap)
    }
    loadThreads()
  }, [])

  // Notify parent when conversation view changes
  useEffect(() => {
    onConversationChange?.(currentPersonalityId !== null)
  }, [currentPersonalityId, onConversationChange])

  // Convert personalities to ChatConversation format
  const conversations: ChatConversation[] = useMemo(
    () =>
      personalities.map((p) => {
        const thread = threads.get(p.id)
        return {
          id: p.id,
          name: p.name,
          avatarUrl: p.avatarUrl,
          lastMessage: thread?.lastMessagePreview ?? p.description,
          unreadCount: thread?.unreadCount ?? 0,
        }
      }),
    [threads, personalities]
  )

  // Get current personality
  const currentPersonality = useMemo(
    () => personalities.find((p) => p.id === currentPersonalityId),
    [currentPersonalityId, personalities]
  )

  // Get chat context with dynamic surveys for current personality
  const {
    nextSurvey,
    surveysComplete,
    saveSurveyResponse,
    userContext,
  } = useChatContext(currentPersonalityId as PersonalityId | null)

  // Handle survey option selection
  const handleSurveySelect = useCallback(async (opt: SurveyOption) => {
    if (!nextSurvey) return

    // Save response to IDB
    await saveSurveyResponse(nextSurvey.id, opt.id, opt.label)

    // Add to answered surveys list
    setSurveyAnswers(prev => [...prev, { surveyId: nextSurvey.id, option: opt }])

    // Brief pause before showing next survey
    setJustAnswered(true)
    setTimeout(() => setJustAnswered(false), 300)
  }, [nextSurvey, saveSurveyResponse])

  // Handle translate button click
  const handleTranslate = useCallback(
    async (messageId: string, text: string) => {
      // Check authentication
      if (!authContext) {
        onAuthRequired?.()
        return
      }

      // Already translating or already have translation
      if (translatingIds.has(messageId) || translations.has(messageId)) {
        return
      }

      // Get target language (user's language, default to zh)
      // Only translate if not English
      const userLang = i18n.language
      if (userLang === 'en') {
        // User is in English, translate to Chinese by default
        // (they're learning from English content)
      }
      const targetLanguage = (userLang === 'en' ? 'zh' : userLang) as 'zh' | 'vi' | 'id'

      // Mark as translating
      setTranslatingIds((prev) => new Set(prev).add(messageId))

      try {
        const response = await translateText({
          text,
          targetLanguage,
          authContext,
        })

        if (response.success && response.translation) {
          setTranslations((prev) => {
            const next = new Map(prev)
            next.set(messageId, response.translation)
            return next
          })
        } else {
          console.error('[ChatContainer] Translation failed:', response.error)
        }
      } catch (error) {
        console.error('[ChatContainer] Translation error:', error)
      } finally {
        setTranslatingIds((prev) => {
          const next = new Set(prev)
          next.delete(messageId)
          return next
        })
      }
    },
    [authContext, i18n.language, onAuthRequired, translatingIds, translations]
  )

  // Handle playing audio for a message (on-demand TTS)
  const handlePlayAudio = useCallback(
    async (messageId: string, text: string) => {
      console.log('[ChatContainer] handlePlayAudio called:', messageId, 'text length:', text.length)

      // Check authentication
      if (!authContext) {
        console.warn('[ChatContainer] No authContext for TTS')
        onAuthRequired?.()
        return
      }

      // Already loading?
      if (loadingTtsIds.has(messageId)) {
        console.log('[ChatContainer] TTS already loading for:', messageId)
        return
      }

      // Stop any existing playback
      if (isPlaying) {
        stopAudio()
      }

      // Check if we already have audio cached
      const cachedAudio = audioDataMap.get(messageId)
      if (cachedAudio) {
        console.log('[ChatContainer] Playing cached audio:', {
          messageId,
          audioLength: cachedAudio.audio.length,
          wordsCount: cachedAudio.words.length,
        })
        setPlayingMessageId(messageId)
        playAudio(cachedAudio.audio, cachedAudio.words)
        return
      }

      // Fetch TTS on-demand
      console.log('[ChatContainer] Fetching TTS on-demand for:', messageId)
      setLoadingTtsIds((prev) => new Set(prev).add(messageId))

      try {
        const response = await synthesizeSpeech({
          text,
          authContext,
        })

        if (response.success && response.audio) {
          // Debug: log what Kokoro returns for word tokens
          console.log('[ChatContainer] TTS words from Kokoro:', response.words?.slice(0, 15).map(w => JSON.stringify(w.text)))

          // Merge standalone quote tokens with adjacent words to fix spacing
          // Opening quote: merge with next word if preceded by sentence-end punct or nothing
          // Closing quote: merge with previous word if it ends with a letter
          const mergedWords: TTSWord[] = []
          const rawWords = response.words ?? []

          for (let i = 0; i < rawWords.length; i++) {
            const word = rawWords[i]
            const text = word.text.trim()

            // Skip empty
            if (!text) continue

            // Check for quote - include straight AND curly quotes using Unicode escapes
            // \u0022 = " (34, straight double)
            // \u0027 = ' (39, straight single)
            // \u201C = " (8220, left double)
            // \u201D = " (8221, right double)
            // \u2018 = ' (8216, left single)
            // \u2019 = ' (8217, right single)
            const isQuote = /^[\u0022\u0027\u201C\u201D\u2018\u2019]+$/.test(text)

            const nextWord = rawWords[i + 1]
            const nextText = nextWord?.text.trim() || ''
            const prevMerged = mergedWords[mergedWords.length - 1]
            const prevText = prevMerged?.text || ''

            // Debug: log char codes for short tokens to identify quote types
            if (text.length <= 2) {
              console.log('[ChatContainer] Short token:', {
                text,
                charCodes: [...text].map(c => c.charCodeAt(0)),
                isQuote,
                prevText: prevText.slice(-5),
                nextText: nextText.slice(0, 5),
              })
            }

            // Determine if this quote is opening or closing based on context
            const prevIsSentenceEnd = !prevText || /[.!?]$/.test(prevText)
            const nextStartsWithLetter = /^[a-zA-Z]/.test(nextText)
            const prevEndsWithLetter = /[a-zA-Z]$/.test(prevText)

            if (isQuote && prevIsSentenceEnd && nextStartsWithLetter) {
              // Opening quote: merge with next word
              console.log('[ChatContainer] Merging opening quote:', text, '+', nextText)
              mergedWords.push({
                ...nextWord,
                text: text + nextText,
                start: word.start,
              })
              i++ // Skip next word since we merged it
            } else if (isQuote && prevEndsWithLetter) {
              // Closing quote after word: merge with previous
              console.log('[ChatContainer] Merging closing quote (after letter):', prevText, '+', text)
              prevMerged.text = prevMerged.text + text
              prevMerged.end = word.end
            } else if (isQuote && prevMerged && /[…,;:]$/.test(prevText)) {
              // Closing quote after punct like ellipsis: merge with previous
              console.log('[ChatContainer] Merging closing quote (after punct):', prevText, '+', text)
              prevMerged.text = prevMerged.text + text
              prevMerged.end = word.end
            } else {
              mergedWords.push({ ...word, text })
            }
          }

          console.log('[ChatContainer] Merged words:', mergedWords.slice(0, 15).map(w => JSON.stringify(w.text)))

          // Cache the audio with merged words
          const audioData: MessageAudioData = {
            audio: response.audio,
            words: mergedWords,
          }
          setAudioDataMap((prev) => {
            const next = new Map(prev)
            next.set(messageId, audioData)
            return next
          })

          // Play it
          setPlayingMessageId(messageId)
          playAudio(response.audio, mergedWords)
        } else {
          console.error('[ChatContainer] TTS failed:', response.error)
        }
      } catch (error) {
        console.error('[ChatContainer] TTS error:', error)
      } finally {
        setLoadingTtsIds((prev) => {
          const next = new Set(prev)
          next.delete(messageId)
          return next
        })
      }
    },
    [authContext, onAuthRequired, loadingTtsIds, isPlaying, stopAudio, audioDataMap, playAudio]
  )

  // Handle stopping audio playback
  const handleStopAudio = useCallback(() => {
    stopAudio()
    setPlayingMessageId(null)
  }, [stopAudio])

  // Convert messages to ChatItem format, with onboarding items for new conversations
  const chatItems: ChatItem[] = useMemo(() => {
    const isNewConversation = messages.length === 0
    const items: ChatItem[] = []

    // For new conversations, show welcome message and surveys as sequential chat
    if (isNewConversation && currentPersonality && currentPersonalityId) {
      const personalityId = currentPersonalityId as PersonalityId
      const surveys = PERSONALITY_SURVEYS[personalityId] || []

      // 1. Welcome message
      const welcomeText = getWelcomeMessage(personalityId, currentPersonality.name)
      items.push({
        type: 'message',
        id: 'welcome',
        props: {
          content: welcomeText,
          sender: 'ai',
          showTranslate: true,
          translation: translations.get('welcome'),
          isTranslating: translatingIds.has('welcome'),
          onTranslate: () => handleTranslate('welcome', welcomeText),
        },
      })

      // 2. Show completed surveys as conversation history
      for (const answer of surveyAnswers) {
        const survey = surveys.find(s => s.id === answer.surveyId)
        if (!survey) continue

        // AI asks the survey question (as a message, not interactive survey)
        items.push({
          type: 'message',
          id: `survey-q-${answer.surveyId}`,
          props: {
            content: survey.question,
            sender: 'ai',
            showTranslate: true,
            translation: translations.get(`survey-q-${answer.surveyId}`),
            isTranslating: translatingIds.has(`survey-q-${answer.surveyId}`),
            onTranslate: () => handleTranslate(`survey-q-${answer.surveyId}`, survey.question),
          },
        })

        // User's answer (as a user message)
        items.push({
          type: 'message',
          id: `survey-a-${answer.surveyId}`,
          props: {
            content: answer.option.label,
            sender: 'user',
          },
        })

        // AI's follow-up response
        const responseText = getSurveyFollowUp(personalityId, answer.surveyId, answer.option)
        items.push({
          type: 'message',
          id: `survey-response-${answer.surveyId}`,
          props: {
            content: responseText,
            sender: 'ai',
            showTranslate: true,
            translation: translations.get(`survey-response-${answer.surveyId}`),
            isTranslating: translatingIds.has(`survey-response-${answer.surveyId}`),
            onTranslate: () => handleTranslate(`survey-response-${answer.surveyId}`, responseText),
          },
        })
      }

      // 3. Show next unanswered survey (if any and not in brief pause after answering)
      if (nextSurvey && !justAnswered) {
        items.push({
          type: 'survey',
          id: `survey-${nextSurvey.id}`,
          props: {
            question: nextSurvey.question,
            options: nextSurvey.options,
            onSelect: handleSurveySelect,
          },
        })
      }
    }

    // Add actual conversation messages
    items.push(
      ...messages.map((m) => {
        const isAssistant = m.role === 'assistant'
        const audioData = audioDataMap.get(m.id)
        const isThisMessagePlaying = playingMessageId === m.id && isPlaying
        const isLoadingTts = loadingTtsIds.has(m.id)

        // Build content - use word array with highlighting if this message is playing
        let content: string | Array<{ text: string; isHighlighted: boolean }>
        if (isThisMessagePlaying && audioData?.words) {
          // Map TTS words to ChatWord format with highlighting
          // Trim each word to remove any embedded whitespace from Kokoro
          // Don't filter - preserve index alignment for highlighting
          content = audioData.words.map((word, idx) => ({
            text: word.text.trim(),
            isHighlighted: idx === currentWordIndex,
          }))
        } else {
          content = m.content
        }

        return {
          type: 'message' as const,
          id: m.id,
          props: {
            content,
            sender: m.role === 'user' ? ('user' as const) : ('ai' as const),
            showTranslate: isAssistant,
            translation: translations.get(m.id),
            isTranslating: translatingIds.has(m.id),
            onTranslate: isAssistant ? () => handleTranslate(m.id, m.content) : undefined,
            // All AI messages can have TTS (on-demand)
            hasAudio: isAssistant,
            isPlayingAudio: isThisMessagePlaying,
            isLoadingAudio: isLoadingTts,
            onPlayAudio: isAssistant ? () => handlePlayAudio(m.id, m.content) : undefined,
            onStopAudio: handleStopAudio,
          },
        }
      })
    )

    return items
  }, [messages, currentPersonality, currentPersonalityId, nextSurvey, surveysComplete, surveyAnswers, justAnswered, handleSurveySelect, translations, translatingIds, handleTranslate, audioDataMap, playingMessageId, isPlaying, loadingTtsIds, currentWordIndex, handlePlayAudio, handleStopAudio])

  // Handle sending a message
  const handleSend = useCallback(
    async (content: string) => {
      if (!currentPersonalityId || !currentPersonality) return

      // Check authentication before sending
      if (!isAuthenticated) {
        onAuthRequired?.()
        return
      }

      // Ensure conversation exists
      await store.getOrCreateConversation(
        currentPersonality.id,
        currentPersonality.name,
        currentPersonality.avatarUrl
      )

      // Add user message
      await addMessage('user', content)

      // If we have an onSendMessage handler, call it for LLM response
      if (onSendMessage) {
        setIsTyping(true)
        try {
          // Build recent messages context
          const recentMessages = messages.slice(-20).map((m) => ({
            role: m.role as 'user' | 'assistant',
            content: m.content,
          }))
          recentMessages.push({ role: 'user', content })

          const { reply } = await onSendMessage(content, {
            personalityId: currentPersonalityId,
            messages: recentMessages,
            userContext,
          })

          // Add assistant response (TTS fetched on-demand when user clicks Play)
          await addMessage('assistant', reply)
        } catch (error) {
          console.error('Failed to get LLM response:', error)
          await addMessage(
            'assistant',
            "Sorry, I'm having trouble responding right now. Please try again."
          )
        } finally {
          setIsTyping(false)
        }
      }

      // Refresh threads to update last message preview
      const allThreads = await store.getThreads()
      const threadMap = new Map<string, Thread>()
      for (const t of allThreads) {
        threadMap.set(t.tutorId, t)
      }
      setThreads(threadMap)
    },
    [
      currentPersonalityId,
      currentPersonality,
      messages,
      addMessage,
      onSendMessage,
      isAuthenticated,
      onAuthRequired,
      userContext,
    ]
  )

  // Handle selecting a personality to chat with
  const handleSelectConversation = useCallback(
    async (conv: ChatConversation) => {
      const personality = personalities.find((p) => p.id === conv.id)
      if (!personality) return

      // Ensure conversation exists
      await store.getOrCreateConversation(
        personality.id,
        personality.name,
        personality.avatarUrl
      )

      // Mark as read
      await store.markThreadRead(personality.id)

      setCurrentPersonalityId(personality.id)
    },
    [personalities]
  )

  // Go back to list
  const goBack = useCallback(async () => {
    setCurrentPersonalityId(null)
    // Reset survey state
    setSurveyAnswers([])
    setJustAnswered(false)
    // Refresh thread list
    const allThreads = await store.getThreads()
    const threadMap = new Map<string, Thread>()
    for (const t of allThreads) {
      threadMap.set(t.tutorId, t)
    }
    setThreads(threadMap)
  }, [])

  // Handle starting voice recording
  const handleStartRecording = useCallback(() => {
    console.log('[ChatContainer] Starting recording...')
    startRecording()
  }, [startRecording])

  // Handle stopping voice recording and transcribing
  const handleStopRecording = useCallback(async () => {
    if (!currentPersonalityId || !currentPersonality || !onSendMessage) {
      console.error('[ChatContainer] Cannot process audio: missing personality or handler')
      return
    }

    // Check authentication before processing
    if (!isAuthenticated) {
      onAuthRequired?.()
      return
    }

    console.log('[ChatContainer] Stopping recording...')
    setIsProcessingAudio(true)

    try {
      const result = await stopRecording()
      if (!result) {
        console.error('[ChatContainer] No recording result')
        return
      }

      console.log('[ChatContainer] Recording stopped, base64 length:', result.base64.length)

      // Ensure conversation exists
      await store.getOrCreateConversation(
        currentPersonality.id,
        currentPersonality.name,
        currentPersonality.avatarUrl
      )

      // Build recent messages context (don't include user message yet - will add transcript)
      const recentMessages = messages.slice(-20).map((m) => ({
        role: m.role as 'user' | 'assistant',
        content: m.content,
      }))

      // Send audio to STT + LLM via Lit Action
      setIsTyping(true)
      const { reply, transcript } = await onSendMessage('', {
        personalityId: currentPersonalityId,
        messages: recentMessages,
        audioBase64: result.base64,
        userContext,
      })

      console.log('[ChatContainer] Got transcript:', transcript)
      console.log('[ChatContainer] Got reply:', reply.substring(0, 100) + '...')

      // Add user's transcribed message
      if (transcript) {
        await addMessage('user', transcript)
      }

      // Add assistant response (TTS fetched on-demand when user clicks Play)
      await addMessage('assistant', reply)

      // Refresh threads to update last message preview
      const allThreads = await store.getThreads()
      const threadMap = new Map<string, Thread>()
      for (const t of allThreads) {
        threadMap.set(t.tutorId, t)
      }
      setThreads(threadMap)

    } catch (error) {
      console.error('[ChatContainer] Recording/transcription error:', error)
      await addMessage(
        'assistant',
        "Sorry, I couldn't understand the audio. Please try again or type your message."
      )
    } finally {
      setIsProcessingAudio(false)
      setIsTyping(false)
    }
  }, [stopRecording, currentPersonalityId, currentPersonality, onSendMessage, isAuthenticated, onAuthRequired, messages, addMessage, userContext])

  // Determine if input should be disabled (during onboarding survey)
  const isNewConversation = messages.length === 0
  const inputDisabled = isNewConversation && !surveysComplete

  // Handle upgrade button click
  const handleUpgradeClick = useCallback(() => {
    resetUpgrade()
    setUpgradeDialogOpen(true)
  }, [resetUpgrade])

  // Handle upgrade purchase via Unlock Protocol
  const handleUpgrade = useCallback(async () => {
    // Check if lock is deployed
    if (premiumLock.lockAddress === '0x0000000000000000000000000000000000000000') {
      console.warn('[ChatContainer] Premium AI lock not deployed yet')
      return
    }
    await purchasePremium()
  }, [purchasePremium, premiumLock.lockAddress])

  // If we have a current personality, show the chat
  if (currentPersonalityId && currentPersonality) {
    return (
      <>
        <ChatPage
          items={chatItems}
          title={currentPersonality.name}
          aiAvatarUrl={currentPersonality.avatarUrl}
          onBack={goBack}
          isTyping={isTyping}
          showUpgrade={true}
          onUpgrade={handleUpgradeClick}
          inputProps={{
            onSend: handleSend,
            onStartRecording: handleStartRecording,
            onStopRecording: handleStopRecording,
            isRecording,
            recordingDuration,
            isProcessing: isProcessingAudio,
            placeholder: inputDisabled ? 'Complete the survey above...' : 'Type a message...',
            disabled: inputDisabled,
          }}
          className={className}
        />
        <PremiumUpgradeDialog
          open={upgradeDialogOpen}
          onOpenChange={setUpgradeDialogOpen}
          currentStep={upgradeStatus}
          statusMessage={upgradeStatusMessage}
          errorMessage={upgradeErrorMessage}
          onUpgrade={handleUpgrade}
          onRetry={resetUpgrade}
        />
      </>
    )
  }

  // Otherwise show the personality list
  return (
    <ChatListPage
      conversations={conversations}
      onSelectConversation={handleSelectConversation}
      className={className}
    />
  )
}
