// root/app/src/components/feed/VideoPlayer.tsx
import { useRef, useEffect } from 'react'
import { Play } from '@phosphor-icons/react'
import { cn } from '@/lib/utils'
import type { VideoPlayerProps } from './types'

/**
 * VideoPlayer - Clean video element with play/pause and mute controls
 * Handles video playback, poster images, and basic controls
 */
export function VideoPlayer({
  videoUrl,
  thumbnailUrl,
  isPlaying,
  isMuted,
  onTogglePlay,
  className
}: VideoPlayerProps) {
  const videoRef = useRef<HTMLVideoElement>(null)

  // Sync isPlaying prop with actual video playback state
  useEffect(() => {
    if (!videoRef.current || !videoUrl) return

    if (isPlaying) {
      videoRef.current.play().catch(e =>
        console.log('[VideoPlayer] Play failed:', e)
      )
    } else {
      videoRef.current.pause()
    }
  }, [isPlaying, videoUrl])

  // Sync isMuted prop with video element
  useEffect(() => {
    if (!videoRef.current) return
    videoRef.current.muted = isMuted
  }, [isMuted])

  return (
    <div className={cn('relative w-full h-full', className)}>
      {/* Video or Thumbnail */}
      {videoUrl ? (
        <video
          ref={videoRef}
          className="w-full h-full object-cover"
          loop
          playsInline
          poster={thumbnailUrl}
          onClick={onTogglePlay}
        />
      ) : thumbnailUrl ? (
        <img
          src={thumbnailUrl}
          alt="Video thumbnail"
          className="w-full h-full object-cover cursor-pointer"
          onClick={onTogglePlay}
        />
      ) : (
        <div className="w-full h-full bg-neutral-900 flex items-center justify-center">
          <span className="text-white/50">No media</span>
        </div>
      )}

      {/* Play/Pause Overlay - only show when paused */}
      {videoUrl && !isPlaying && (
        <div
          className="absolute inset-0 flex items-center justify-center bg-black/20 hover:bg-black/30 cursor-pointer transition-colors group"
          onClick={onTogglePlay}
        >
          <div className="w-20 h-20 bg-black/50 backdrop-blur-sm rounded-full flex items-center justify-center group-hover:bg-black/60 transition-colors">
            <Play className="w-10 h-10 text-white fill-white ml-1" weight="fill" />
          </div>
        </div>
      )}
    </div>
  )
}

// solidjs-app/src/components/feed/VideoPlayer.tsx
import { createSignal, createEffect, onMount, onCleanup, Show, type Component } from 'solid-js'
import { Play } from '@/components/icons'
import type { VideoPlayerProps } from './types'

/**
 * VideoPlayer - Simple video player with play/pause and mute controls
 * SolidJS port - simplified without XState machine for now
 */
export const VideoPlayer: Component<VideoPlayerProps> = (props) => {
  let videoRef: HTMLVideoElement | undefined

  const [isLoaded, setIsLoaded] = createSignal(false)
  const [hasStartedPlaying, setHasStartedPlaying] = createSignal(false)
  const [error, setError] = createSignal<string | null>(null)
  const [isLoading, setIsLoading] = createSignal(false)

  // Handle play/pause toggle - play directly in click handler for browser autoplay policy
  const handlePlayPause = () => {
    console.log('[VideoPlayer] handlePlayPause', {
      hasVideoRef: !!videoRef,
      videoUrl: props.videoUrl,
      isLoaded: isLoaded(),
      isPlaying: props.isPlaying,
      videoPaused: videoRef?.paused,
      readyState: videoRef?.readyState,
    })

    if (!videoRef || !props.videoUrl) return

    // Play/pause directly in click handler for browser autoplay policy compliance
    if (videoRef.paused) {
      console.log('[VideoPlayer] Calling play() directly in click handler')
      videoRef.play().catch((e) => {
        console.log('[VideoPlayer] play() failed:', e.name, e.message)
        if (e.name === 'NotAllowedError') {
          props.onPlayFailed?.()
        }
      })
    } else {
      videoRef.pause()
    }

    props.onTogglePlay()
  }

  // Load video when URL changes
  createEffect(() => {
    const url = props.videoUrl
    if (!url || !videoRef) return

    setIsLoading(true)
    setError(null)
    videoRef.src = url
    videoRef.load()
  })

  // Setup video element and event listeners
  onMount(() => {
    if (!videoRef) return

    const handleLoadedMetadata = () => {
      setIsLoaded(true)
      setIsLoading(false)
    }

    const handleError = () => {
      if (videoRef?.error) {
        const errorMsg = `Code ${videoRef.error.code}: ${videoRef.error.message || 'Unknown error'}`
        setError(errorMsg)
        setIsLoading(false)
      }
    }

    const handlePlaying = () => {
      setHasStartedPlaying(true)
    }

    const handleTimeUpdate = () => {
      props.onTimeUpdate?.(videoRef!.currentTime)
    }

    videoRef.addEventListener('loadedmetadata', handleLoadedMetadata)
    videoRef.addEventListener('error', handleError)
    videoRef.addEventListener('playing', handlePlaying)
    videoRef.addEventListener('timeupdate', handleTimeUpdate)

    onCleanup(() => {
      videoRef?.removeEventListener('loadedmetadata', handleLoadedMetadata)
      videoRef?.removeEventListener('error', handleError)
      videoRef?.removeEventListener('playing', handlePlaying)
      videoRef?.removeEventListener('timeupdate', handleTimeUpdate)
    })
  })

  // Sync isPlaying prop with video element
  createEffect(() => {
    if (!videoRef || !isLoaded()) return

    console.log('[VideoPlayer] Sync effect', {
      isPlaying: props.isPlaying,
      videoPaused: videoRef.paused,
    })

    if (props.isPlaying && videoRef.paused) {
      console.log('[VideoPlayer] Effect: calling play()')
      videoRef.play().catch((e) => {
        if (e.name === 'NotAllowedError') {
          props.onPlayFailed?.()
        }
      })
    } else if (!props.isPlaying && !videoRef.paused) {
      console.log('[VideoPlayer] Effect: calling pause()')
      videoRef.pause()
    }
  })

  // Sync isMuted prop with video element
  createEffect(() => {
    if (!videoRef) return
    videoRef.muted = props.isMuted
  })

  const showThumbnail = () => !!props.thumbnailUrl
  const showVideo = () => !!props.videoUrl
  // Show play button when paused (either before first play, or after user pauses)
  const showPlayButton = () => !props.isPlaying
  const showSpinner = () => isLoading() && (props.isPlaying || hasStartedPlaying()) && !showThumbnail()

  return (
    <div class={`relative w-full h-full bg-black ${props.class || ''}`}>
      {/* Thumbnail */}
      <Show when={showThumbnail()}>
        <img
          src={props.thumbnailUrl}
          alt="Video thumbnail"
          class="absolute inset-0 w-full h-full object-cover z-10"
        />
      </Show>

      {/* Video element */}
      <Show when={showVideo()}>
        <video
          ref={videoRef}
          class={`absolute inset-0 w-full h-full object-cover ${hasStartedPlaying() ? 'z-20' : 'z-0'}`}
          style={{
            'background-color': 'black',
          }}
          loop
          playsinline
          preload="auto"
          muted={props.isMuted}
          onClick={(e) => {
            e.stopPropagation()
            handlePlayPause()
          }}
        />
      </Show>

      {/* Fallback for no media */}
      <Show when={!props.videoUrl && !props.thumbnailUrl}>
        <div class="absolute inset-0 w-full h-full bg-background flex items-center justify-center z-0">
          <span class="text-foreground/50">No media</span>
        </div>
      </Show>

      {/* Error state */}
      <Show when={error()}>
        <div class="absolute inset-0 flex items-center justify-center bg-black/80 z-30">
          <div class="text-red-500 text-center p-4">
            <p class="font-semibold">Playback Error</p>
            <p class="text-sm mt-2">{error()}</p>
          </div>
        </div>
      </Show>

      {/* Loading Spinner */}
      <Show when={showSpinner()}>
        <div class="absolute inset-0 flex items-center justify-center z-30">
          <div class="w-16 h-16 border-4 border-white/30 border-t-white rounded-full animate-spin" />
        </div>
      </Show>

      {/* Play/Pause Overlay */}
      <Show when={showPlayButton()}>
        <div
          class="absolute inset-0 flex items-center justify-center bg-black/20 hover:bg-black/30 cursor-pointer transition-colors group z-30"
          onClick={(e) => {
            e.stopPropagation()
            handlePlayPause()
          }}
        >
          <div class="w-20 h-20 bg-black/50 backdrop-blur-sm rounded-full flex items-center justify-center group-hover:bg-black/60 transition-colors">
            <Play class="w-10 h-10 text-foreground fill-white ml-1" />
          </div>
        </div>
      </Show>
    </div>
  )
}
