// app/src/components/feed/VideoPlayer.tsx
import { useRef, useEffect } from 'react'
import { Play } from '@phosphor-icons/react'
import { cn } from '@/lib/utils'
import { useMachine } from '@xstate/react'
import { videoPlayerMachine } from './videoPlayerMachine'
import type { VideoPlayerProps } from './types'

/**
 * VideoPlayer - Clean video element with play/pause and mute controls
 * Handles video playback, poster images, and basic controls
 * Uses XState machine for reliable state management
 */
export function VideoPlayer({
  videoUrl,
  thumbnailUrl,
  isPlaying,
  isMuted,
  onTogglePlay,
  onPlayFailed,
  onTimeUpdate,
  captionTracks,
  className
}: VideoPlayerProps) {
  const videoRef = useRef<HTMLVideoElement>(null)
  const [state, send] = useMachine(videoPlayerMachine, {
    input: {
      videoUrl,
      thumbnailUrl,
      isMuted,
      autoplay: isPlaying,
    },
  })

  // Handle play/pause - delegates to state machine
  const handlePlayPause = () => {
    if (!videoRef.current || !videoUrl) return
    send({ type: 'TOGGLE_PLAY' })
    onTogglePlay()
  }

  // Load video when URL changes - with aggressive debouncing and error state tracking
  const lastLoadRef = useRef<string>('')
  const errorStateRef = useRef<boolean>(false)
  const timeoutRef = useRef<NodeJS.Timeout>()

  useEffect(() => {
    if (!videoUrl) return

    const loadVideo = () => {
      // Don't load if we're in error state and the URL hasn't actually changed
      if (errorStateRef.current && videoUrl === lastLoadRef.current) {
        console.log('[VideoPlayer] Skipping load - in error state:', videoUrl)
        return
      }

      // Only load if URL actually changed or we're not in error state
      if (videoUrl !== lastLoadRef.current) {
        console.log('[VideoPlayer] Loading video:', videoUrl)
        lastLoadRef.current = videoUrl
        errorStateRef.current = false // Reset error state
        send({ type: 'LOAD', videoUrl, thumbnailUrl })
      }
    }

    // Clear any existing timeout
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current)
    }

    // Aggressive debounce - 1000ms to prevent rapid-fire attempts
    timeoutRef.current = setTimeout(loadVideo, 1000)

    return () => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current)
      }
    }
  }, [videoUrl, thumbnailUrl, send])

  // Track error state to prevent immediate retries
  useEffect(() => {
    if (state.matches('error')) {
      console.log('[VideoPlayer] Entered error state, preventing retries for:', lastLoadRef.current)
      errorStateRef.current = true
      
      // Clear error state after 5 seconds to allow retries
      setTimeout(() => {
        errorStateRef.current = false
      }, 5000)
    }
  }, [state])

  // Setup video element and event listeners
  useEffect(() => {
    const video = videoRef.current
    if (!video || !state.context.videoUrl) return

    // Set video source
    video.src = state.context.videoUrl
    video.load()

    const handleLoadedMetadata = () => {
      send({ type: 'VIDEO_LOADED' })
    }

    const handleError = () => {
      if (video.error) {
        const errorMsg = `Code ${video.error.code}: ${video.error.message || 'Unknown error'}`
        // Only log non-empty errors
        if (video.error.message) {
        }
        send({ type: 'VIDEO_ERROR', error: errorMsg })
      }
    }

    const handlePlaying = () => {
      send({ type: 'PLAYING' })
    }

    const handlePause = () => {
      send({ type: 'PAUSED' })
    }

    const handleTimeUpdate = () => {
      if (onTimeUpdate) {
        onTimeUpdate(video.currentTime)
      }
    }

    video.addEventListener('loadedmetadata', handleLoadedMetadata)
    video.addEventListener('error', handleError)
    video.addEventListener('playing', handlePlaying)
    video.addEventListener('pause', handlePause)
    video.addEventListener('timeupdate', handleTimeUpdate)

    return () => {
      video.removeEventListener('loadedmetadata', handleLoadedMetadata)
      video.removeEventListener('error', handleError)
      video.removeEventListener('playing', handlePlaying)
      video.removeEventListener('pause', handlePause)
      video.removeEventListener('timeupdate', handleTimeUpdate)
    }
  }, [state.context.videoUrl, send, onTimeUpdate])

  // Sync isPlaying prop with state machine
  useEffect(() => {
    send({ type: 'SET_AUTOPLAY', autoplay: isPlaying })
  }, [isPlaying, send])

  // Sync actual video playback with state machine
  useEffect(() => {
    const video = videoRef.current
    if (!video) return

    const isInPlayingState = state.matches({ loaded: 'playing' }) || state.matches({ loaded: 'attemptingPlay' })

    if (isInPlayingState && video.paused) {
      video.play().catch((e) => {
        if (e.name === 'NotAllowedError') {
          send({ type: 'AUTOPLAY_BLOCKED' })
          onPlayFailed?.()
        }
      })
    } else if (!isInPlayingState && !video.paused) {
      video.pause()
    }
  }, [state.value, send, onPlayFailed])

  // Sync isMuted prop with video element
  useEffect(() => {
    const video = videoRef.current
    if (!video) return
    video.muted = isMuted
  }, [isMuted])

  const showThumbnail = !!state.context.thumbnailUrl
  const showVideo = !!state.context.videoUrl
  const hasStartedPlaying = state.context.hasStartedPlaying
  const isLoading = state.matches('loading') || state.matches({ loaded: 'attemptingPlay' })
  // Show play button if not autoplay and hasn't started playing yet (including during loading)
  const showPlayButton = !state.context.shouldAutoplay && !hasStartedPlaying
  // Show spinner only when loading, user has interacted, AND no thumbnail available
  // If we have a thumbnail, it serves as the loading state - no spinner needed
  const showSpinner = isLoading && (state.context.shouldAutoplay || hasStartedPlaying) && !showThumbnail

  return (
    <div className={cn('relative w-full h-full bg-black', className)}>
      {/* Thumbnail - always show when available, z-10 to appear above video until it has visible frames */}
      {showThumbnail && (
        <img
          src={state.context.thumbnailUrl}
          alt="Video thumbnail"
          className="absolute inset-0 w-full h-full object-cover z-10"
        />
      )}

      {/* Video element - z-20 when playing (above thumbnail), z-0 when paused (below thumbnail) */}
      {showVideo && (
        <video
          ref={videoRef}
          className={cn(
            "absolute inset-0 w-full h-full object-cover",
            hasStartedPlaying ? "z-20" : "z-0"
          )}
          style={{
            backgroundColor: 'black',
            objectFit: 'cover',
            willChange: 'transform',
          }}
          loop
          playsInline
          preload="auto"
          muted={isMuted}
          onClick={(e) => {
            e.stopPropagation()
            handlePlayPause()
          }}
        >
          {/* Native caption tracks */}
          {captionTracks?.map((track) => (
            <track
              key={track.srclang}
              kind="captions"
              src={track.src}
              srcLang={track.srclang}
              label={track.label}
              default={track.default}
            />
          ))}
        </video>
      )}

      {/* Fallback for no media */}
      {!state.context.videoUrl && !state.context.thumbnailUrl && (
        <div className="absolute inset-0 w-full h-full bg-background flex items-center justify-center z-0">
          <span className="text-foreground/50">No media</span>
        </div>
      )}

      {/* Error state */}
      {state.matches('error') && state.context.error && (
        <div className="absolute inset-0 flex items-center justify-center bg-black/80 z-30">
          <div className="text-red-500 text-center p-4">
            <p className="font-semibold">Playback Error</p>
            <p className="text-sm mt-2">{state.context.error}</p>
          </div>
        </div>
      )}

      {/* Loading Spinner - show when loading or attempting to play, z-30 to be above everything */}
      {showSpinner && (
        <div className="absolute inset-0 flex items-center justify-center z-30">
          <div className="w-16 h-16 border-4 border-white/30 border-t-white rounded-full animate-spin" />
        </div>
      )}

      {/* Play/Pause Overlay - only show when paused, z-30 to be above everything */}
      {showPlayButton && (
        <div
          className="absolute inset-0 flex items-center justify-center bg-black/20 hover:bg-black/30 cursor-pointer transition-colors group z-30"
          onClick={(e) => {
            e.stopPropagation()
            handlePlayPause()
          }}
        >
          <div className="w-20 h-20 bg-black/50 backdrop-blur-sm rounded-full flex items-center justify-center group-hover:bg-black/60 transition-colors">
            <Play className="w-10 h-10 text-foreground fill-white ml-1" weight="fill" />
          </div>
        </div>
      )}
    </div>
  )
}

// solidjs-app/src/components/feed/VideoPlayer.tsx
import { createSignal, createEffect, onMount, onCleanup, Show, type Component } from 'solid-js'
import { Play } from '@/components/icons'
import type { VideoPlayerProps } from './types'

/**
 * VideoPlayer - Simple video player with play/pause and mute controls
 * SolidJS port - simplified without XState machine for now
 */
export const VideoPlayer: Component<VideoPlayerProps> = (props) => {
  let videoRef: HTMLVideoElement | undefined

  const [isLoaded, setIsLoaded] = createSignal(false)
  const [hasStartedPlaying, setHasStartedPlaying] = createSignal(false)
  const [error, setError] = createSignal<string | null>(null)
  const [isLoading, setIsLoading] = createSignal(false)

  // Handle play/pause toggle - play directly in click handler for browser autoplay policy
  const handlePlayPause = () => {
    console.log('[VideoPlayer] handlePlayPause', {
      hasVideoRef: !!videoRef,
      videoUrl: props.videoUrl,
      isLoaded: isLoaded(),
      isPlaying: props.isPlaying,
      videoPaused: videoRef?.paused,
      readyState: videoRef?.readyState,
    })

    if (!videoRef || !props.videoUrl) return

    // Play/pause directly in click handler for browser autoplay policy compliance
    if (videoRef.paused) {
      console.log('[VideoPlayer] Calling play() directly in click handler')
      videoRef.play().catch((e) => {
        console.log('[VideoPlayer] play() failed:', e.name, e.message)
        if (e.name === 'NotAllowedError') {
          props.onPlayFailed?.()
        }
      })
    } else {
      videoRef.pause()
    }

    props.onTogglePlay()
  }

  // Load video when URL changes
  createEffect(() => {
    const url = props.videoUrl
    if (!url || !videoRef) return

    setIsLoading(true)
    setError(null)
    videoRef.src = url
    videoRef.load()
  })

  // Setup video element and event listeners
  onMount(() => {
    if (!videoRef) return

    const handleLoadedMetadata = () => {
      setIsLoaded(true)
      setIsLoading(false)
    }

    const handleError = () => {
      if (videoRef?.error) {
        const errorMsg = `Code ${videoRef.error.code}: ${videoRef.error.message || 'Unknown error'}`
        setError(errorMsg)
        setIsLoading(false)
      }
    }

    const handlePlaying = () => {
      setHasStartedPlaying(true)
    }

    const handleTimeUpdate = () => {
      props.onTimeUpdate?.(videoRef!.currentTime)
    }

    videoRef.addEventListener('loadedmetadata', handleLoadedMetadata)
    videoRef.addEventListener('error', handleError)
    videoRef.addEventListener('playing', handlePlaying)
    videoRef.addEventListener('timeupdate', handleTimeUpdate)

    onCleanup(() => {
      videoRef?.removeEventListener('loadedmetadata', handleLoadedMetadata)
      videoRef?.removeEventListener('error', handleError)
      videoRef?.removeEventListener('playing', handlePlaying)
      videoRef?.removeEventListener('timeupdate', handleTimeUpdate)
    })
  })

  // Sync isPlaying prop with video element
  createEffect(() => {
    if (!videoRef || !isLoaded()) return

    console.log('[VideoPlayer] Sync effect', {
      isPlaying: props.isPlaying,
      videoPaused: videoRef.paused,
    })

    if (props.isPlaying && videoRef.paused) {
      console.log('[VideoPlayer] Effect: calling play()')
      videoRef.play().catch((e) => {
        if (e.name === 'NotAllowedError') {
          props.onPlayFailed?.()
        }
      })
    } else if (!props.isPlaying && !videoRef.paused) {
      console.log('[VideoPlayer] Effect: calling pause()')
      videoRef.pause()
    }
  })

  // Sync isMuted prop with video element
  createEffect(() => {
    if (!videoRef) return
    videoRef.muted = props.isMuted
  })

  const showThumbnail = () => !!props.thumbnailUrl
  const showVideo = () => !!props.videoUrl
  // Show play button when paused (either before first play, or after user pauses)
  const showPlayButton = () => !props.isPlaying
  const showSpinner = () => isLoading() && (props.isPlaying || hasStartedPlaying()) && !showThumbnail()

  return (
    <div class={`relative w-full h-full bg-black ${props.class || ''}`}>
      {/* Thumbnail */}
      <Show when={showThumbnail()}>
        <img
          src={props.thumbnailUrl}
          alt="Video thumbnail"
          class="absolute inset-0 w-full h-full object-cover z-10"
        />
      </Show>

      {/* Video element */}
      <Show when={showVideo()}>
        <video
          ref={videoRef}
          class={`absolute inset-0 w-full h-full object-cover ${hasStartedPlaying() ? 'z-20' : 'z-0'}`}
          style={{
            'background-color': 'black',
          }}
          loop
          playsinline
          preload="auto"
          muted={props.isMuted}
          onClick={(e) => {
            e.stopPropagation()
            handlePlayPause()
          }}
        />
      </Show>

      {/* Fallback for no media */}
      <Show when={!props.videoUrl && !props.thumbnailUrl}>
        <div class="absolute inset-0 w-full h-full bg-background flex items-center justify-center z-0">
          <span class="text-foreground/50">No media</span>
        </div>
      </Show>

      {/* Error state */}
      <Show when={error()}>
        <div class="absolute inset-0 flex items-center justify-center bg-black/80 z-30">
          <div class="text-red-500 text-center p-4">
            <p class="font-semibold">Playback Error</p>
            <p class="text-sm mt-2">{error()}</p>
          </div>
        </div>
      </Show>

      {/* Loading Spinner */}
      <Show when={showSpinner()}>
        <div class="absolute inset-0 flex items-center justify-center z-30">
          <div class="w-16 h-16 border-4 border-white/30 border-t-white rounded-full animate-spin" />
        </div>
      </Show>

      {/* Play/Pause Overlay */}
      <Show when={showPlayButton()}>
        <div
          class="absolute inset-0 flex items-center justify-center bg-black/20 hover:bg-black/30 cursor-pointer transition-colors group z-30"
          onClick={(e) => {
            e.stopPropagation()
            handlePlayPause()
          }}
        >
          <div class="w-20 h-20 bg-black/50 backdrop-blur-sm rounded-full flex items-center justify-center group-hover:bg-black/60 transition-colors">
            <Play class="w-10 h-10 text-foreground fill-white ml-1" />
          </div>
        </div>
      </Show>
    </div>
  )
}
